function build_hpt_v2_1to1_switchlevel()
% build_hpt_v2_1to1_switchlevel
% Reference-structure HPT topology model.
%
% The model follows the supplied topology diagram:
%   - Main transformer: W1/W2 per phase.
%   - New flexible distribution transformer: W3/W4 per phase.
%   - Energy converter: fed from W4 through an RL filter.
%   - Regulating converter: drives W5 of the series transformers.
%   - Series injection transformers: W6 is inserted in each load phase.
%   - Energy and regulating converters share the DC link.
%
% This is a switch-level topology skeleton.  Each converter leg is built from
% individual IGBT blocks.  Converter gates are held off by default; control/PWM
% migration and parameter calibration should be done in a later step.

M = 'hpt_v2_1to1_switchlevel';
if bdIsLoaded(M)
    close_system(M, 0);
end
new_system(M);
load_system(M);
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
addpath(fileparts(thisDir));

f0 = 50;
Ts = 20e-6;
Vmv = 10e3;
Vlv = 400;
Srated = 400e3;
Saux = 120e3;
Sser = 30e3;
Vaux = 400;
Vw5 = 400;
Vw6 = 100;
Rtake = 0.05;
Ltake = 3e-3;
Cdc = 2200e-6;
Rchop = (800^2) / Saux;

Zb = Vmv^2 / Srated;
scr = 3;
Zg = Zb / scr;
Rg = Zg / sqrt(1 + 49);
Lg = 7 * Rg / (2 * pi * f0);

P = @(x, y, w, h) [x y x+w y+h];
set_param(M, 'Solver', 'ode23tb', 'StopTime', '0.2');
mw = get_param(M, 'ModelWorkspace');
assignin(mw, 'hpt_pwm_fs', 2000);
assignin(mw, 'hpt_m_energy', 0.00);
assignin(mw, 'hpt_m_reg', 0.10);
assignin(mw, 'hpt_ctrl_Ts', Ts);
assignin(mw, 'hpt_grid_f0', f0);
assignin(mw, 'hpt_vdc_ref', 800.0);
assignin(mw, 'hpt_vdc_kp', 0.10);
assignin(mw, 'hpt_vdc_ki', 0.20);
assignin(mw, 'hpt_energy_id_max', 20.0);
assignin(mw, 'hpt_energy_i_kp', 0.50);
assignin(mw, 'hpt_energy_i_ki', 100.0);
assignin(mw, 'hpt_m_energy_max', 0.95);
assignin(mw, 'hpt_energy_vff_gain', 1.06);
assignin(mw, 'hpt_energy_control_sign', -1.0);
assignin(mw, 'hpt_energy_bridge_polarity', -1.0);
assignin(mw, 'hpt_energy_openloop_amp', 0.0);
assignin(mw, 'hpt_energy_openloop_phase', 0.0);
assignin(mw, 'hpt_vref_lv', 207.0);
assignin(mw, 'hpt_vreg_kp', 20.0);
assignin(mw, 'hpt_vreg_ki', 0.0);
assignin(mw, 'hpt_m_reg_max', 0.80);
assignin(mw, 'hpt_pll_kp', 80.0);
assignin(mw, 'hpt_pll_ki', 2500.0);
assignin(mw, 'hpt_inj_phase_offset', -1.05);
assignin(mw, 'hpt_swell_gain_scale', 1.0);
assignin(mw, 'hpt_sac_enable', 0.0);
assignin(mw, 'hpt_sac_energy_enable', 0.0);
assignin(mw, 'hpt_sac_policy_mode', 0.0);
assignin(mw, 'hpt_sac_actor_select_mode', 0.0);
assignin(mw, 'hpt_sac_vref_phase', 230.0);
assignin(mw, 'hpt_sac_vdc_ref', 800.0);
assignin(mw, 'hpt_sac_reg_max', 0.80);
assignin(mw, 'hpt_sac_energy_max', 0.95);
assignin(mw, 'hpt_sac_i_base_peak', sqrt(2) * Srated / (sqrt(3) * Vlv));
assignin(mw, 'hpt_sac_reg_polarity', 1.0);
assignin(mw, 'hpt_sac_reg_d_gain', 1.00);
assignin(mw, 'hpt_sac_reg_q_gain', 0.0);
assignin(mw, 'hpt_sac_dynamic_reg_limit', 0.80);
assignin(mw, 'hpt_sac_topology_id', 1.0);
assignin(mw, 'hpt_sac_fixed_reg_d', 0.0);
assignin(mw, 'hpt_sac_fixed_reg_q', 0.0);
assignin(mw, 'hpt_sac_fixed_energy_d', 0.0);
assignin(mw, 'hpt_sac_fixed_energy_q', 0.0);
assignin(mw, 'hpt_sac_guard_enable', 0.0);

add_block('powerlib/powergui', [M '/powergui'], 'Position', P(20, 20, 70, 40));
set_param([M '/powergui'], 'SimulationMode', 'Discrete', 'SampleTime', num2str(Ts));

% Grid and weak-grid impedance.
add_block('powerlib/Electrical Sources/Three-Phase Source', [M '/Grid'], ...
    'Position', P(60, 115, 60, 90));
set_param([M '/Grid'], 'Voltage', num2str(Vmv), 'Frequency', num2str(f0), ...
    'PhaseAngle', '0', 'InternalConnection', 'Yg', ...
    'SpecifyImpedance', 'off', 'Resistance', '1e-3', 'Inductance', '1e-5');

add_block('powerlib/Elements/Three-Phase Series RLC Branch', [M '/Zg'], ...
    'Position', P(155, 120, 55, 70));
set_param([M '/Zg'], 'BranchType', 'RL', 'Resistance', num2str(Rg), ...
    'Inductance', num2str(Lg));

add_block('powerlib/Measurements/Three-Phase V-I Measurement', [M '/MeasMV'], ...
    'Position', P(245, 115, 70, 90));
set_param([M '/MeasMV'], 'VoltageMeasurement', 'phase-to-ground', ...
    'CurrentMeasurement', 'no');

% Main transformer W1/W2.
for k = 1:3
    y = 70 + (k-1) * 115;
    blk = [M sprintf('/Main_W1W2_%d', k)];
    add_block('powerlib/Elements/Linear Transformer', blk, ...
        'Position', P(375, y, 95, 78));
    set_param(blk, 'ThreeWindings', 'off', ...
        'NominalPower', ['[' num2str(Srated/3) ',' num2str(f0) ']'], ...
        'winding1', ['[' num2str(Vmv/sqrt(3)) ',0.005,0.025]'], ...
        'winding2', ['[' num2str(Vlv/sqrt(3)) ',0.005,0.025]']);
end

% New flexible distribution transformer W3/W4.
for k = 1:3
    x = 300 + (k-1) * 125;
    blk = [M sprintf('/Flex_W3W4_%d', k)];
    add_block('powerlib/Elements/Linear Transformer', blk, ...
        'Position', P(x, 430, 82, 78));
    set_param(blk, 'ThreeWindings', 'off', ...
        'NominalPower', ['[' num2str(Saux/3) ',' num2str(f0) ']'], ...
        'winding1', ['[' num2str(Vlv/sqrt(3)) ',0.005,0.02]'], ...
        'winding2', ['[' num2str(Vaux/sqrt(3)) ',0.005,0.02]']);
end

% Series injection transformer W5/W6.  W6 is in the load path; W5 is fed by
% the regulating converter.
for k = 1:3
    y = 70 + (k-1) * 115;
    blk = [M sprintf('/Series_W5W6_%d', k)];
    add_block('powerlib/Elements/Linear Transformer', blk, ...
        'Position', P(650, y, 95, 72));
    set_param(blk, 'ThreeWindings', 'off', ...
        'NominalPower', ['[' num2str(Sser) ',' num2str(f0) ']'], ...
        'winding1', ['[' num2str(Vw5) ',0.002,0.03]'], ...
        'winding2', ['[' num2str(Vw6) ',0.002,0.03]']);
end

add_block('powerlib/Measurements/Three-Phase V-I Measurement', [M '/MeasLV'], ...
    'Position', P(805, 135, 70, 100));
set_param([M '/MeasLV'], 'VoltageMeasurement', 'phase-to-ground', ...
    'CurrentMeasurement', 'no');

add_block('powerlib/Elements/Three-Phase Series RLC Load', [M '/Load'], ...
    'Position', P(950, 150, 70, 80));
set_param([M '/Load'], 'NominalVoltage', num2str(Vlv), ...
    'NominalFrequency', num2str(f0), 'ActivePower', num2str(Srated), ...
    'InductivePower', '0', 'CapacitivePower', '0', ...
    'Configuration', 'Y (grounded)');

% Energy converter chain: W4 -> measurement -> RL filter -> ShVSC.
add_block('powerlib/Measurements/Three-Phase V-I Measurement', [M '/MeasEnergy'], ...
    'Position', P(690, 455, 70, 95));
set_param([M '/MeasEnergy'], 'VoltageMeasurement', 'phase-to-ground', ...
    'CurrentMeasurement', 'yes');

add_block('powerlib/Elements/Three-Phase Series RLC Branch', [M '/Energy_RL'], ...
    'Position', P(800, 470, 60, 65));
set_param([M '/Energy_RL'], 'BranchType', 'RL', 'Resistance', num2str(Rtake), ...
    'Inductance', num2str(Ltake));

add_voltage_regulator(M, 1010, 260);
add_energy_controller(M, 1010, 395);
add_hpt_sac_controller(M, 1010, 570);
add_energy_converter_subsystem(M, 910, 430);
add_regulating_converter_subsystem(M, 250, 665);

add_block('powerlib/Elements/Series RLC Branch', [M '/Cdc'], ...
    'Position', P(1160, 470, 40, 85));
set_param([M '/Cdc'], 'BranchType', 'C', 'Capacitance', num2str(Cdc), ...
    'Setx0', 'on', 'InitialVoltage', '800');

add_block('powerlib/Measurements/Voltage Measurement', [M '/MeasVdc'], ...
    'Position', P(1230, 465, 45, 45));

add_block('powerlib/Power Electronics/IGBT', [M '/Chop'], ...
    'Position', P(1325, 465, 40, 55));
add_block('powerlib/Elements/Series RLC Branch', [M '/Rchop'], ...
    'Position', P(1325, 550, 45, 55));
set_param([M '/Rchop'], 'BranchType', 'R', 'Resistance', num2str(Rchop));

% Ground references for the single-phase winding groups.
add_block('powerlib/Elements/Ground', [M '/W1_neutral_ground'], ...
    'Position', P(325, 395, 25, 25));
add_block('powerlib/Elements/Ground', [M '/W2_neutral_ground'], ...
    'Position', P(545, 395, 25, 25));
add_block('powerlib/Elements/Ground', [M '/W3_neutral_ground'], ...
    'Position', P(265, 555, 25, 25));
add_block('powerlib/Elements/Ground', [M '/W4_neutral_ground'], ...
    'Position', P(645, 555, 25, 25));

% DC-link overvoltage chopper gate.
add_block('simulink/Sources/Constant', [M '/Chop_gate'], ...
    'Position', P(1215, 575, 60, 25), 'Value', '850');
add_block('simulink/Logic and Bit Operations/Relational Operator', [M '/Chop_cmp'], ...
    'Position', P(1290, 545, 40, 35));
set_param([M '/Chop_cmp'], 'Operator', '>');
add_block('simulink/Sources/Constant', [M '/SAC_enable'], ...
    'Position', P(1205, 355, 55, 25), 'Value', 'hpt_sac_enable');
add_block('simulink/Sources/Constant', [M '/SAC_energy_enable'], ...
    'Position', P(1205, 455, 55, 25), 'Value', 'hpt_sac_energy_enable');
add_block('simulink/Signal Routing/Switch', [M '/RegCommandSelect'], ...
    'Position', P(1280, 300, 50, 50));
set_param([M '/RegCommandSelect'], 'Criteria', 'u2 >= Threshold', 'Threshold', '0.5');
add_block('simulink/Signal Routing/Switch', [M '/EnergyCommandSelect'], ...
    'Position', P(1280, 405, 50, 50));
set_param([M '/EnergyCommandSelect'], 'Criteria', 'u2 >= Threshold', 'Threshold', '0.5');

% Logging.
add_block('simulink/Sinks/To Workspace', [M '/Vmv_abc'], ...
    'Position', P(1125, 115, 85, 25), 'VariableName', 'Vmv_abc', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Vlv_abc'], ...
    'Position', P(1125, 150, 85, 25), 'VariableName', 'Vlv_abc', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Vdc'], ...
    'Position', P(1290, 465, 70, 25), 'VariableName', 'Vdc', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Mreg_cmd'], ...
    'Position', P(1210, 270, 80, 25), 'VariableName', 'Mreg_cmd', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Mref6_cmd'], ...
    'Position', P(1210, 305, 80, 25), 'VariableName', 'Mref6_cmd', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Menergy_cmd'], ...
    'Position', P(1210, 395, 90, 25), 'VariableName', 'Menergy_cmd', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Energy_Vabc'], ...
    'Position', P(1125, 425, 90, 25), 'VariableName', 'Energy_Vabc', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Energy_Iabc'], ...
    'Position', P(1125, 455, 90, 25), 'VariableName', 'Energy_Iabc', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/Energy_dbg'], ...
    'Position', P(1210, 425, 90, 25), 'VariableName', 'Energy_dbg', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/HPTSAC_obs'], ...
    'Position', P(1210, 570, 90, 25), 'VariableName', 'HPTSAC_obs', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));
add_block('simulink/Sinks/To Workspace', [M '/HPTSAC_action'], ...
    'Position', P(1210, 600, 90, 25), 'VariableName', 'HPTSAC_action', ...
    'SaveFormat', 'Array', 'SampleTime', num2str(Ts));

% Main power path and transformer taps.
for k = 1:3
    add_line(M, ph([M '/Grid'], 'RConn', k), ph([M '/Zg'], 'LConn', k), ...
        'autorouting', 'on');
    add_line(M, ph([M '/Zg'], 'RConn', k), ph([M '/MeasMV'], 'LConn', k), ...
        'autorouting', 'on');
    add_line(M, ph([M '/MeasMV'], 'RConn', k), ...
        ph([M sprintf('/Main_W1W2_%d', k)], 'LConn', 1), 'autorouting', 'on');

    % W2 phase conductor -> W6 series winding -> load.
    add_line(M, ph([M sprintf('/Main_W1W2_%d', k)], 'RConn', 1), ...
        ph([M sprintf('/Series_W5W6_%d', k)], 'RConn', 1), 'autorouting', 'on');
    add_line(M, ph([M sprintf('/Series_W5W6_%d', k)], 'RConn', 2), ...
        ph([M '/MeasLV'], 'LConn', k), 'autorouting', 'on');
    add_line(M, ph([M '/MeasLV'], 'RConn', k), ph([M '/Load'], 'LConn', k), ...
        'autorouting', 'on');

    % W3 is tapped from the W2 side and magnetically feeds W4.
    add_line(M, ph([M sprintf('/Main_W1W2_%d', k)], 'RConn', 1), ...
        ph([M sprintf('/Flex_W3W4_%d', k)], 'LConn', 1), 'autorouting', 'on');
    add_line(M, ph([M sprintf('/Flex_W3W4_%d', k)], 'RConn', 1), ...
        ph([M '/MeasEnergy'], 'LConn', k), 'autorouting', 'on');
    add_line(M, ph([M '/MeasEnergy'], 'RConn', k), ...
        ph([M '/Energy_RL'], 'LConn', k), 'autorouting', 'on');
    add_line(M, ph([M '/Energy_RL'], 'RConn', k), ...
        ph([M '/EnergyConverter'], 'LConn', k), 'autorouting', 'on');

    % W5 is driven by one full H-bridge per phase; W6 is the line-side
    % series winding.
    add_line(M, ph([M sprintf('/Series_W5W6_%d', k)], 'LConn', 1), ...
        ph([M '/RegulatingConverter'], 'LConn', 2*k-1), 'autorouting', 'on');
    add_line(M, ph([M sprintf('/Series_W5W6_%d', k)], 'LConn', 2), ...
        ph([M '/RegulatingConverter'], 'LConn', 2*k), 'autorouting', 'on');
end

% Common/grounded neutral groups.
connect3(M, 'Main_W1W2', 'LConn', 2);
add_line(M, ph([M '/Main_W1W2_3'], 'LConn', 2), ...
    ph([M '/W1_neutral_ground'], 'LConn', 1), 'autorouting', 'on');

connect3(M, 'Main_W1W2', 'RConn', 2);
add_line(M, ph([M '/Main_W1W2_3'], 'RConn', 2), ...
    ph([M '/W2_neutral_ground'], 'LConn', 1), 'autorouting', 'on');

connect3(M, 'Flex_W3W4', 'LConn', 2);
add_line(M, ph([M '/Flex_W3W4_3'], 'LConn', 2), ...
    ph([M '/W3_neutral_ground'], 'LConn', 1), 'autorouting', 'on');

connect3(M, 'Flex_W3W4', 'RConn', 2);
add_line(M, ph([M '/Flex_W3W4_3'], 'RConn', 2), ...
    ph([M '/W4_neutral_ground'], 'LConn', 1), 'autorouting', 'on');

% Shared DC link and chopper.
dcPos = ph([M '/Cdc'], 'LConn', 1);
dcNeg = ph([M '/Cdc'], 'RConn', 1);
add_line(M, dcPos, ph([M '/EnergyConverter'], 'RConn', 1), 'autorouting', 'on');
add_line(M, ph([M '/EnergyConverter'], 'RConn', 2), dcNeg, 'autorouting', 'on');
add_line(M, dcPos, ph([M '/RegulatingConverter'], 'RConn', 1), 'autorouting', 'on');
add_line(M, ph([M '/RegulatingConverter'], 'RConn', 2), dcNeg, 'autorouting', 'on');
add_line(M, ph([M '/MeasVdc'], 'LConn', 1), dcPos, 'autorouting', 'on');
add_line(M, ph([M '/MeasVdc'], 'LConn', 2), dcNeg, 'autorouting', 'on');
add_line(M, dcPos, ph([M '/Chop'], 'LConn', 1), 'autorouting', 'on');
add_line(M, ph([M '/Chop'], 'RConn', 1), ph([M '/Rchop'], 'LConn', 1), ...
    'autorouting', 'on');
add_line(M, ph([M '/Rchop'], 'RConn', 1), dcNeg, 'autorouting', 'on');

% Signal wiring.
add_line(M, 'MeasVdc/1', 'Chop_cmp/1', 'autorouting', 'on');
add_line(M, 'Chop_gate/1', 'Chop_cmp/2', 'autorouting', 'on');
add_line(M, 'Chop_cmp/1', 'Chop/1', 'autorouting', 'on');
add_line(M, 'MeasMV/1', 'Vmv_abc/1', 'autorouting', 'on');
add_line(M, 'MeasLV/1', 'Vlv_abc/1', 'autorouting', 'on');
add_line(M, 'MeasLV/1', 'VoltageRegulator/1', 'autorouting', 'on');
add_line(M, 'MeasLV/1', 'HPTSACController/1', 'autorouting', 'on');
add_line(M, 'VoltageRegulator/1', 'RegCommandSelect/3', 'autorouting', 'on');
add_line(M, 'HPTSACController/1', 'RegCommandSelect/1', 'autorouting', 'on');
add_line(M, 'SAC_enable/1', 'RegCommandSelect/2', 'autorouting', 'on');
add_line(M, 'RegCommandSelect/1', 'RegulatingConverter/1', 'autorouting', 'on');
add_line(M, 'RegCommandSelect/1', 'Mref6_cmd/1', 'autorouting', 'on');
add_line(M, 'VoltageRegulator/2', 'Mreg_cmd/1', 'autorouting', 'on');
add_line(M, 'MeasVdc/1', 'Vdc/1', 'autorouting', 'on');
add_line(M, 'MeasVdc/1', 'HPTSACController/2', 'autorouting', 'on');
add_line(M, 'MeasVdc/1', 'EnergyController/1', 'autorouting', 'on');
add_line(M, 'MeasEnergy/1', 'EnergyController/2', 'autorouting', 'on');
add_line(M, 'MeasEnergy/2', 'EnergyController/3', 'autorouting', 'on');
add_line(M, 'MeasEnergy/1', 'HPTSACController/3', 'autorouting', 'on');
add_line(M, 'MeasEnergy/2', 'HPTSACController/4', 'autorouting', 'on');
add_line(M, 'EnergyController/1', 'EnergyCommandSelect/3', 'autorouting', 'on');
add_line(M, 'HPTSACController/2', 'EnergyCommandSelect/1', 'autorouting', 'on');
add_line(M, 'SAC_energy_enable/1', 'EnergyCommandSelect/2', 'autorouting', 'on');
add_line(M, 'EnergyCommandSelect/1', 'EnergyConverter/1', 'autorouting', 'on');
add_line(M, 'EnergyCommandSelect/1', 'Menergy_cmd/1', 'autorouting', 'on');
add_line(M, 'EnergyController/2', 'Energy_dbg/1', 'autorouting', 'on');
add_line(M, 'MeasEnergy/1', 'Energy_Vabc/1', 'autorouting', 'on');
add_line(M, 'MeasEnergy/2', 'Energy_Iabc/1', 'autorouting', 'on');
add_line(M, 'HPTSACController/3', 'HPTSAC_obs/1', 'autorouting', 'on');
add_line(M, 'HPTSACController/4', 'HPTSAC_action/1', 'autorouting', 'on');

decorate_model(M);

try
    set_param(M, 'ZoomFactor', 'FitSystem');
catch
end
save_system(M, fullfile(fileparts(mfilename('fullpath')), [M '.slx']));
fprintf('Built %s.slx with explicit switch-level Energy and Regulating converters.\\n', M);
end

function connect3(M, prefix, kind, idx)
add_line(M, ph([M '/' prefix '_1'], kind, idx), ...
    ph([M '/' prefix '_2'], kind, idx), 'autorouting', 'on');
add_line(M, ph([M '/' prefix '_2'], kind, idx), ...
    ph([M '/' prefix '_3'], kind, idx), 'autorouting', 'on');
end

function decorate_model(M)
blocks = find_system(M, 'Type', 'Block');
for i = 1:numel(blocks)
    try
        set_param(blocks{i}, 'ShowName', 'off', 'FontName', 'auto', 'FontSize', '10');
    catch
    end
    apply_text_free_icon(blocks{i});
end
annotations = find_system(M, 'FindAll', 'on', 'Type', 'annotation');
for i = 1:numel(annotations)
    try
        delete(annotations(i));
    catch
    end
end
end

function apply_text_free_icon(blockPath)
try
    maskType = get_param(blockPath, 'MaskType');
catch
    maskType = '';
end
try
    blockType = get_param(blockPath, 'BlockType');
catch
    blockType = '';
end

icon = '';
switch maskType
    case 'IGBT'
        icon = [ ...
            'plot([20 80 80 20 20],[10 10 90 90 10]);' newline ...
            'plot([35 35],[20 80]); plot([35 65],[50 50]);' newline ...
            'plot([65 65],[25 75]); plot([58 72],[35 35]); plot([58 72],[65 65]);' newline ...
            'plot([20 35],[50 50]); plot([65 80],[50 50]);' ...
            ];
    case 'Linear Transformer'
        icon = [ ...
            'plot([8 92],[50 50],''w'');' newline ...
            'plot([44 44],[15 85]); plot([56 56],[15 85]);' newline ...
            'plot([20 30 20 30 20 30],[25 35 45 55 65 75]);' newline ...
            'plot([80 70 80 70 80 70],[25 35 45 55 65 75]);' ...
            ];
    case {'Three-Phase V-I Measurement', 'Voltage Measurement'}
        icon = [ ...
            'plot([10 90 90 10 10],[20 20 80 80 20]);' newline ...
            'plot([20 80],[50 50]); plot([68 80 68],[42 50 58]);' ...
            ];
    case {'Three-Phase Series RLC Branch', 'Series RLC Branch'}
        icon = [ ...
            'plot([5 20 30 40 50 60 70 80 95],[50 50 35 65 35 65 35 50 50]);' ...
            ];
    case 'Three-Phase Source'
        icon = [ ...
            'plot([50+35*cos(0:0.2:6.3)],[50+35*sin(0:0.2:6.3)]);' newline ...
            'plot([20 35 50 65 80],[50 35 65 35 50]);' ...
            ];
    case 'Three-Phase Series RLC Load'
        icon = [ ...
            'plot([10 25 35 45 55 65 75 90],[50 50 35 65 35 65 50 50]);' newline ...
            'plot([90 90],[35 65]);' ...
            ];
    case 'powergui'
        icon = 'plot([10 90 90 10 10],[10 10 90 90 10]);';
    otherwise
        if strcmp(blockType, 'Constant')
            icon = 'plot([20 80 80 20 20],[30 30 70 70 30]);';
        elseif strcmp(blockType, 'ToWorkspace')
            icon = 'plot([10 90 90 10 10],[25 25 75 75 25]);';
        end
end

if ~isempty(icon)
    try
        set_param(blockPath, 'MaskDisplay', icon);
    catch
    end
end
end

function add_voltage_regulator(M, x, y)
P = @(a, b, w, h) [a b a+w b+h];
S = [M '/VoltageRegulator'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 205, 145));
set_param(S, 'ShowName', 'on');
open_system(S);

add_block('simulink/Sources/In1', [S '/Vabc'], 'Position', P(35, 78, 30, 18));
ctrl = [S '/PLL_dq_voltage_loop'];
add_block('simulink/User-Defined Functions/MATLAB Function', ctrl, ...
    'Position', P(120, 45, 180, 95));
set_matlab_function_code(ctrl, pll_dq_controller_code());
paramNames = {'Ts', 'GridF0', 'Vref', 'VregKp', 'VregKi', ...
    'Mmax', 'PllKp', 'PllKi', 'InjPhase', 'SwellGain'};
paramValues = {'hpt_ctrl_Ts', 'hpt_grid_f0', 'hpt_vref_lv', ...
    'hpt_vreg_kp', 'hpt_vreg_ki', 'hpt_m_reg_max', ...
    'hpt_pll_kp', 'hpt_pll_ki', 'hpt_inj_phase_offset', ...
    'hpt_swell_gain_scale'};
for pidx = 1:numel(paramNames)
    add_block('simulink/Sources/Constant', [S '/' paramNames{pidx}], ...
        'Position', P(35, 125 + (pidx-1)*32, 55, 20), ...
        'Value', paramValues{pidx});
    add_line(S, [paramNames{pidx} '/1'], ...
        sprintf('PLL_dq_voltage_loop/%d', pidx+1), 'autorouting', 'on');
end
add_block('simulink/Sinks/Out1', [S '/m_ref6'], 'Position', P(365, 62, 30, 18));
add_block('simulink/Sinks/Out1', [S '/ctrl_dbg'], 'Position', P(365, 112, 30, 18));

add_line(S, 'Vabc/1', 'PLL_dq_voltage_loop/1', 'autorouting', 'on');
add_line(S, 'PLL_dq_voltage_loop/1', 'm_ref6/1', 'autorouting', 'on');
add_line(S, 'PLL_dq_voltage_loop/2', 'ctrl_dbg/1', 'autorouting', 'on');
end

function add_energy_controller(M, x, y)
P = @(a, b, w, h) [a b a+w b+h];
S = [M '/EnergyController'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 185, 70));
set_param(S, 'ShowName', 'on');
open_system(S);

add_block('simulink/Sources/In1', [S '/Vdc'], 'Position', P(35, 48, 30, 18));
add_block('simulink/Sources/In1', [S '/Vabc'], 'Position', P(35, 83, 30, 18));
add_block('simulink/Sources/In1', [S '/Iabc'], 'Position', P(35, 118, 30, 18));
ctrl = [S '/Vdc_dq_current_loop'];
add_block('simulink/User-Defined Functions/MATLAB Function', ctrl, ...
    'Position', P(115, 25, 190, 110));
set_matlab_function_code(ctrl, energy_controller_code());
paramNames = {'Ts', 'GridF0', 'VdcRef', 'VdcKp', 'VdcKi', ...
    'IdMax', 'CurrentKp', 'CurrentKi', 'Mmax', 'PllKp', 'PllKi', ...
    'VffGain', 'ControlSign', 'Polarity', 'OpenAmp', 'OpenPhase'};
paramValues = {'hpt_ctrl_Ts', 'hpt_grid_f0', 'hpt_vdc_ref', ...
    'hpt_vdc_kp', 'hpt_vdc_ki', 'hpt_energy_id_max', ...
    'hpt_energy_i_kp', 'hpt_energy_i_ki', 'hpt_m_energy_max', ...
    'hpt_pll_kp', 'hpt_pll_ki', 'hpt_energy_vff_gain', ...
    'hpt_energy_control_sign', 'hpt_energy_bridge_polarity', ...
    'hpt_energy_openloop_amp', 'hpt_energy_openloop_phase'};
for pidx = 1:numel(paramNames)
    add_block('simulink/Sources/Constant', [S '/' paramNames{pidx}], ...
        'Position', P(35, 95 + (pidx-1)*30, 55, 20), ...
        'Value', paramValues{pidx});
    add_line(S, [paramNames{pidx} '/1'], sprintf('Vdc_dq_current_loop/%d', pidx+3), ...
        'autorouting', 'on');
end
add_block('simulink/Sinks/Out1', [S '/m_energy_abc'], 'Position', P(360, 65, 30, 18));
add_block('simulink/Sinks/Out1', [S '/energy_dbg'], 'Position', P(360, 105, 30, 18));

add_line(S, 'Vdc/1', 'Vdc_dq_current_loop/1', 'autorouting', 'on');
add_line(S, 'Vabc/1', 'Vdc_dq_current_loop/2', 'autorouting', 'on');
add_line(S, 'Iabc/1', 'Vdc_dq_current_loop/3', 'autorouting', 'on');
add_line(S, 'Vdc_dq_current_loop/1', 'm_energy_abc/1', 'autorouting', 'on');
add_line(S, 'Vdc_dq_current_loop/2', 'energy_dbg/1', 'autorouting', 'on');
end

function add_energy_converter_subsystem(M, x, y)
P = @(a, b, w, h) [a b a+w b+h];
S = [M '/EnergyConverter'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 165, 130));
set_param(S, 'ShowName', 'on');
set_converter_mask(S, 'energy');
open_system(S);

add_block('simulink/Sources/In1', [S '/m_energy_abc'], ...
    'Position', P(70, 15, 30, 18));
add_block('simulink/Signal Routing/Demux', [S '/m_energy_demux'], ...
    'Position', P(120, 5, 10, 70), 'Outputs', '3');
add_line(S, 'm_energy_abc/1', 'm_energy_demux/1', 'autorouting', 'on');
for k = 1:3
    add_pmio(S, sprintf('AC_%d', k), 'Left', P(20, 45 + (k-1)*45, 24, 24));
end
add_pmio(S, 'DC_pos', 'Right', P(520, 45, 24, 24));
add_pmio(S, 'DC_neg', 'Right', P(520, 210, 24, 24));

add_universal_energy_bridge(S, 175, 55);
for k = 1:3
    add_line(S, ph([S sprintf('/AC_%d', k)], 'RConn', 1), ...
        ph([S '/E_UniversalBridge'], 'LConn', k), 'autorouting', 'on');
end
add_line(S, ph([S '/E_UniversalBridge'], 'RConn', 1), ...
    ph([S '/DC_pos'], 'RConn', 1), 'autorouting', 'on');
add_line(S, ph([S '/E_UniversalBridge'], 'RConn', 2), ...
    ph([S '/DC_neg'], 'RConn', 1), 'autorouting', 'on');

end

function add_universal_energy_bridge(M, x, y)
P = @(a, b, w, h) [a b a+w b+h];
ub = [M '/E_UniversalBridge'];
add_block('powerlib/Power Electronics/Universal Bridge', ub, ...
    'Position', P(x, y, 105, 130));
set_param(ub, 'Arms', '3', 'Device', 'IGBT / Diodes', ...
    'Ron', '1e-3', 'Lon', '0', 'ForwardVoltages', '[0.8 0.8]', ...
    'SnubberResistance', '1e5', 'SnubberCapacitance', 'inf');
add_block('simulink/Signal Routing/Mux', [M '/E_gate_mux'], ...
    'Position', P(x-20, y+16, 10, 100), 'Inputs', '6');
phaseNames = {'A', 'B', 'C'};
for k = 1:3
    add_spwm_gate_to_mux(M, phaseNames{k}, x-145, y + 12 + (k-1)*38, k);
end
add_line(M, 'E_gate_mux/1', 'E_UniversalBridge/1', 'autorouting', 'on');
end

function add_spwm_gate_to_mux(M, tag, x, y, phaseIdx)
P = @(a, b, w, h) [a b a+w b+h];
carrier = [M '/E_carrier_' tag];
cmp = [M '/E_cmp_' tag];
inv = [M '/E_not_' tag];
add_block('simulink/Sources/Repeating Sequence', carrier, ...
    'Position', P(x, y+22, 45, 22));
set_param(carrier, 'rep_seq_t', '[0 0.5/hpt_pwm_fs 1/hpt_pwm_fs]', ...
    'rep_seq_y', '[-1 1 -1]');
add_block('simulink/Logic and Bit Operations/Relational Operator', cmp, ...
    'Position', P(x+75, y, 35, 28));
set_param(cmp, 'Operator', '>');
add_block('simulink/Logic and Bit Operations/Logical Operator', inv, ...
    'Position', P(x+75, y+40, 35, 28));
set_param(inv, 'Operator', 'NOT');
add_line(M, sprintf('m_energy_demux/%d', phaseIdx), ...
    ['E_cmp_' tag '/1'], 'autorouting', 'on');
add_line(M, ['E_carrier_' tag '/1'], ['E_cmp_' tag '/2'], 'autorouting', 'on');
add_line(M, ['E_cmp_' tag '/1'], sprintf('E_gate_mux/%d', 2*phaseIdx-1), ...
    'autorouting', 'on');
add_line(M, ['E_cmp_' tag '/1'], ['E_not_' tag '/1'], 'autorouting', 'on');
add_line(M, ['E_not_' tag '/1'], sprintf('E_gate_mux/%d', 2*phaseIdx), ...
    'autorouting', 'on');
end

function add_regulating_converter_subsystem(M, x, y)
P = @(a, b, w, h) [a b a+w b+h];
S = [M '/RegulatingConverter'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 430, 190));
set_param(S, 'ShowName', 'on');
set_converter_mask(S, 'regulating');
open_system(S);

add_block('simulink/Sources/In1', [S '/m_ref6'], ...
    'Position', P(70, 15, 30, 18));
add_block('simulink/Signal Routing/Demux', [S '/m_ref_demux'], ...
    'Position', P(120, 5, 10, 85), 'Outputs', '6');
add_line(S, 'm_ref6/1', 'm_ref_demux/1', 'autorouting', 'on');
phaseNames = {'A', 'B', 'C'};
for k = 1:3
    add_pmio(S, sprintf('W5_%s_1', phaseNames{k}), 'Left', ...
        P(20, 65 + (k-1)*130, 24, 24));
    add_pmio(S, sprintf('W5_%s_2', phaseNames{k}), 'Left', ...
        P(20, 95 + (k-1)*130, 24, 24));
end
add_pmio(S, 'DC_pos', 'Right', P(520, 45, 24, 24));
add_pmio(S, 'DC_neg', 'Right', P(520, 455, 24, 24));

add_universal_hbridge3_converter(S, 'R', 170, 55);
for k = 1:3
    connect_universal_hbridge_phase(S, ...
        ph([S sprintf('/W5_%s_1', phaseNames{k})], 'RConn', 1), ...
        ph([S sprintf('/W5_%s_2', phaseNames{k})], 'RConn', 1), ...
        'R', k);
end
connect_universal_hbridge_dc(S, 'R', ph([S '/DC_pos'], 'RConn', 1), ...
    ph([S '/DC_neg'], 'RConn', 1));

end

function set_converter_mask(blockPath, iconKind)
switch iconKind
    case 'energy'
        displayCode = [ ...
            'color(''black'');' newline ...
            'plot([10 90 90 10 10],[10 10 90 90 10]);' newline ...
            'plot([20 80],[78 78]); plot([20 80],[22 22]);' newline ...
            'plot([28 28],[22 78]); plot([50 50],[22 78]); plot([72 72],[22 78]);' newline ...
            'plot([10 20],[65 65]); plot([10 20],[50 50]); plot([10 20],[35 35]);' newline ...
            'plot([80 90],[65 65]); plot([80 90],[35 35]);' ...
            ];
    otherwise
        displayCode = [ ...
            'color(''black'');' newline ...
            'plot([5 95 95 5 5],[10 10 90 90 10]);' newline ...
            'plot([15 85],[78 78]); plot([15 85],[22 22]);' newline ...
            'plot([18 18],[22 78]); plot([32 32],[22 78]);' newline ...
            'plot([45 45],[22 78]); plot([59 59],[22 78]);' newline ...
            'plot([72 72],[22 78]); plot([86 86],[22 78]);' newline ...
            'plot([5 15],[75 75]); plot([5 15],[60 60]); plot([5 15],[45 45]);' newline ...
            'plot([5 15],[30 30]); plot([5 15],[15 15]); plot([5 15],[10 10]);' newline ...
            'plot([85 95],[75 75]); plot([85 95],[25 25]);' ...
            ];
end
set_param(blockPath, 'Mask', 'on', 'MaskIconOpaque', 'opaque', ...
    'MaskIconFrame', 'on', 'MaskIconUnits', 'autoscale', ...
    'MaskDisplay', displayCode);
end

function add_pmio(sys, name, side, position)
blk = [sys '/' name];
add_block('built-in/PMIOPort', blk, 'Position', position);
set_param(blk, 'Side', side, 'ShowName', 'off');
end

function add_switch_bridge(M, prefix, x, y)
P = @(a, b, w, h) [a b a+w b+h];
phaseNames = {'A', 'B', 'C'};
phaseAngles = {'0', '-2*pi/3', '2*pi/3'};
for k = 1:3
    sx = x + (k-1) * 60;
    upper = [M '/' prefix '_S' phaseNames{k} 'U'];
    lower = [M '/' prefix '_S' phaseNames{k} 'L'];
    add_block('powerlib/Power Electronics/IGBT', upper, ...
        'Position', P(sx, y, 42, 58));
    add_block('powerlib/Power Electronics/IGBT', lower, ...
        'Position', P(sx, y+78, 42, 58));
    add_antiparallel_diode(M, upper, [prefix '_D' phaseNames{k} 'U'], sx+7, y+16);
    add_antiparallel_diode(M, lower, [prefix '_D' phaseNames{k} 'L'], sx+7, y+94);
    phaseExpr = phaseAngles{k};
    if startsWith(prefix, 'E')
        refIndex = k;
    else
        refIndex = 0;
    end
    add_spwm_gate_pair(M, prefix, phaseNames{k}, sx-95, y+22, ...
        modulation_expr(prefix), phaseExpr, ...
        [prefix '_S' phaseNames{k} 'U'], [prefix '_S' phaseNames{k} 'L'], refIndex);
end
end

function add_hbridge3_converter(M, prefix, x, y)
P = @(a, b, w, h) [a b a+w b+h];
phaseNames = {'A', 'B', 'C'};
phaseAngles = {'0', '-2*pi/3', '2*pi/3'};
for k = 1:3
    sy = y + (k-1) * 130;
    for leg = 1:2
        sx = x + (leg-1) * 145;
        tag = [phaseNames{k} num2str(leg)];
        upper = [M '/' prefix '_S' tag 'U'];
        lower = [M '/' prefix '_S' tag 'L'];
        add_block('powerlib/Power Electronics/IGBT', upper, ...
            'Position', P(sx, sy, 42, 58));
        add_block('powerlib/Power Electronics/IGBT', lower, ...
            'Position', P(sx, sy+68, 42, 58));
        if leg == 1
            phaseExpr = phaseAngles{k};
        else
            phaseExpr = ['(' phaseAngles{k} ')+pi'];
        end
        add_spwm_gate_pair(M, prefix, tag, sx-95, sy+22, ...
            modulation_expr(prefix), phaseExpr, ...
            [prefix '_S' tag 'U'], [prefix '_S' tag 'L'], (k-1)*2 + leg);
    end
end
end

function add_universal_hbridge3_converter(M, prefix, x, y)
P = @(a, b, w, h) [a b a+w b+h];
phaseNames = {'A', 'B', 'C'};
phaseAngles = {'0', '-2*pi/3', '2*pi/3'};
for k = 1:3
    sy = y + (k-1) * 130;
    bridge = [M '/' prefix '_UB_' phaseNames{k}];
    gateMux = [M '/' prefix '_gate_mux_' phaseNames{k}];
    add_block('powerlib/Power Electronics/Universal Bridge', bridge, ...
        'Position', P(x+155, sy+8, 70, 100));
    set_param(bridge, 'Arms', '2', 'Device', 'IGBT / Diodes', ...
        'SnubberResistance', '1e5', 'SnubberCapacitance', '1e-9');
    add_block('simulink/Signal Routing/Mux', gateMux, ...
        'Position', P(x+105, sy+28, 8, 62), 'Inputs', '4');

    tag1 = [phaseNames{k} '1'];
    tag2 = [phaseNames{k} '2'];
    add_spwm_gate_pair_to_ports(M, prefix, tag1, x-95, sy+8, ...
        modulation_expr(prefix), phaseAngles{k}, ...
        [prefix '_gate_mux_' phaseNames{k} '/1'], ...
        [prefix '_gate_mux_' phaseNames{k} '/2'], (k-1)*2 + 1);
    add_spwm_gate_pair_to_ports(M, prefix, tag2, x-95, sy+68, ...
        modulation_expr(prefix), ['(' phaseAngles{k} ')+pi'], ...
        [prefix '_gate_mux_' phaseNames{k} '/3'], ...
        [prefix '_gate_mux_' phaseNames{k} '/4'], (k-1)*2 + 2);
    add_line(M, [prefix '_gate_mux_' phaseNames{k} '/1'], ...
        [prefix '_UB_' phaseNames{k} '/1'], 'autorouting', 'on');
end
end

function expr = modulation_expr(prefix)
if startsWith(prefix, 'E')
    expr = 'hpt_m_energy';
else
    expr = 'hpt_m_reg';
end
end

function add_spwm_gate_pair(M, prefix, tag, x, y, amplitudeExpr, phaseExpr, upperName, lowerName, refIndex)
P = @(a, b, w, h) [a b a+w b+h];
ref = [M '/' prefix '_ref_' tag];
mod = [M '/' prefix '_mod_' tag];
carrier = [M '/' prefix '_carrier_' tag];
cmp = [M '/' prefix '_cmp_' tag];
inv = [M '/' prefix '_not_' tag];
useDynamicReference = refIndex > 0 && ...
    (~isempty(find_system(M, 'SearchDepth', 1, 'Name', 'm_ref_demux')) || ...
     ~isempty(find_system(M, 'SearchDepth', 1, 'Name', 'm_energy_demux')));
if ~useDynamicReference
    add_block('simulink/Sources/Sine Wave', ref, 'Position', P(x, y, 45, 25));
    set_param(ref, 'Amplitude', amplitudeExpr, 'Frequency', '2*pi*50', ...
        'Phase', phaseExpr, 'SampleTime', '0');
end
add_block('simulink/Sources/Repeating Sequence', carrier, ...
    'Position', P(x, y+42, 45, 25));
set_param(carrier, 'rep_seq_t', '[0 0.5/hpt_pwm_fs 1/hpt_pwm_fs]', ...
    'rep_seq_y', '[-1 1 -1]');
add_block('simulink/Logic and Bit Operations/Relational Operator', cmp, ...
    'Position', P(x+122, y+13, 35, 30));
set_param(cmp, 'Operator', '>');
add_block('simulink/Logic and Bit Operations/Logical Operator', inv, ...
    'Position', P(x+177, y+50, 35, 30));
set_param(inv, 'Operator', 'NOT');
if useDynamicReference
    if startsWith(prefix, 'E')
        sourceDemux = 'm_energy_demux';
    else
        sourceDemux = 'm_ref_demux';
    end
    add_line(M, sprintf('%s/%d', sourceDemux, refIndex), ...
        [prefix '_cmp_' tag '/1'], 'autorouting', 'on');
else
    add_line(M, [prefix '_ref_' tag '/1'], [prefix '_cmp_' tag '/1'], ...
        'autorouting', 'on');
end
add_line(M, [prefix '_carrier_' tag '/1'], [prefix '_cmp_' tag '/2'], ...
    'autorouting', 'on');
add_line(M, [prefix '_cmp_' tag '/1'], [upperName '/1'], 'autorouting', 'on');
add_line(M, [prefix '_cmp_' tag '/1'], [prefix '_not_' tag '/1'], ...
    'autorouting', 'on');
add_line(M, [prefix '_not_' tag '/1'], [lowerName '/1'], 'autorouting', 'on');
end

function add_spwm_gate_pair_to_ports(M, prefix, tag, x, y, amplitudeExpr, phaseExpr, upperPort, lowerPort, refIndex)
P = @(a, b, w, h) [a b a+w b+h];
ref = [M '/' prefix '_ref_' tag];
carrier = [M '/' prefix '_carrier_' tag];
cmp = [M '/' prefix '_cmp_' tag];
inv = [M '/' prefix '_not_' tag];
useDynamicReference = refIndex > 0 && ...
    (~isempty(find_system(M, 'SearchDepth', 1, 'Name', 'm_ref_demux')) || ...
     ~isempty(find_system(M, 'SearchDepth', 1, 'Name', 'm_energy_demux')));
if ~useDynamicReference
    add_block('simulink/Sources/Sine Wave', ref, 'Position', P(x, y, 45, 25));
    set_param(ref, 'Amplitude', amplitudeExpr, 'Frequency', '2*pi*50', ...
        'Phase', phaseExpr, 'SampleTime', '0');
end
add_block('simulink/Sources/Repeating Sequence', carrier, ...
    'Position', P(x, y+42, 45, 25));
set_param(carrier, 'rep_seq_t', '[0 0.5/hpt_pwm_fs 1/hpt_pwm_fs]', ...
    'rep_seq_y', '[-1 1 -1]');
add_block('simulink/Logic and Bit Operations/Relational Operator', cmp, ...
    'Position', P(x+122, y+13, 35, 30));
set_param(cmp, 'Operator', '>');
add_block('simulink/Logic and Bit Operations/Logical Operator', inv, ...
    'Position', P(x+177, y+50, 35, 30));
set_param(inv, 'Operator', 'NOT');
if useDynamicReference
    if startsWith(prefix, 'E')
        sourceDemux = 'm_energy_demux';
    else
        sourceDemux = 'm_ref_demux';
    end
    add_line(M, sprintf('%s/%d', sourceDemux, refIndex), ...
        [prefix '_cmp_' tag '/1'], 'autorouting', 'on');
else
    add_line(M, [prefix '_ref_' tag '/1'], [prefix '_cmp_' tag '/1'], ...
        'autorouting', 'on');
end
add_line(M, [prefix '_carrier_' tag '/1'], [prefix '_cmp_' tag '/2'], ...
    'autorouting', 'on');
add_line(M, [prefix '_cmp_' tag '/1'], upperPort, 'autorouting', 'on');
add_line(M, [prefix '_cmp_' tag '/1'], [prefix '_not_' tag '/1'], ...
    'autorouting', 'on');
add_line(M, [prefix '_not_' tag '/1'], lowerPort, 'autorouting', 'on');
end

function connect_phase_to_bridge(M, phasePort, prefix, phaseIdx)
phaseNames = {'A', 'B', 'C'};
upper = [M '/' prefix '_S' phaseNames{phaseIdx} 'U'];
lower = [M '/' prefix '_S' phaseNames{phaseIdx} 'L'];
add_line(M, phasePort, ph(upper, 'RConn', 1), 'autorouting', 'on');
add_line(M, phasePort, ph(lower, 'LConn', 1), 'autorouting', 'on');
end

function connect_hbridge_phase(M, leftPort, rightPort, prefix, phaseIdx)
phaseNames = {'A', 'B', 'C'};
leg1Upper = [M '/' prefix '_S' phaseNames{phaseIdx} '1U'];
leg1Lower = [M '/' prefix '_S' phaseNames{phaseIdx} '1L'];
leg2Upper = [M '/' prefix '_S' phaseNames{phaseIdx} '2U'];
leg2Lower = [M '/' prefix '_S' phaseNames{phaseIdx} '2L'];
add_line(M, leftPort, ph(leg1Upper, 'RConn', 1), 'autorouting', 'on');
add_line(M, leftPort, ph(leg1Lower, 'LConn', 1), 'autorouting', 'on');
add_line(M, rightPort, ph(leg2Upper, 'RConn', 1), 'autorouting', 'on');
add_line(M, rightPort, ph(leg2Lower, 'LConn', 1), 'autorouting', 'on');
end

function connect_universal_hbridge_phase(M, leftPort, rightPort, prefix, phaseIdx)
phaseNames = {'A', 'B', 'C'};
bridge = [M '/' prefix '_UB_' phaseNames{phaseIdx}];
add_line(M, leftPort, ph(bridge, 'LConn', 1), 'autorouting', 'on');
add_line(M, rightPort, ph(bridge, 'LConn', 2), 'autorouting', 'on');
end

function connect_bridge_dc(M, prefix, dcPos, dcNeg)
phaseNames = {'A', 'B', 'C'};
for k = 1:3
    upper = [M '/' prefix '_S' phaseNames{k} 'U'];
    lower = [M '/' prefix '_S' phaseNames{k} 'L'];
    add_line(M, dcPos, ph(upper, 'LConn', 1), 'autorouting', 'on');
    add_line(M, ph(lower, 'RConn', 1), dcNeg, 'autorouting', 'on');
end
end

function connect_hbridge_dc(M, prefix, dcPos, dcNeg)
phaseNames = {'A', 'B', 'C'};
for k = 1:3
    for leg = 1:2
        tag = [phaseNames{k} num2str(leg)];
        upper = [M '/' prefix '_S' tag 'U'];
        lower = [M '/' prefix '_S' tag 'L'];
        add_line(M, dcPos, ph(upper, 'LConn', 1), 'autorouting', 'on');
        add_line(M, ph(lower, 'RConn', 1), dcNeg, 'autorouting', 'on');
    end
end
end

function connect_universal_hbridge_dc(M, prefix, dcPos, dcNeg)
phaseNames = {'A', 'B', 'C'};
for k = 1:3
    bridge = [M '/' prefix '_UB_' phaseNames{k}];
    add_line(M, dcPos, ph(bridge, 'RConn', 1), 'autorouting', 'on');
    add_line(M, ph(bridge, 'RConn', 2), dcNeg, 'autorouting', 'on');
end
end

function add_antiparallel_diode(M, switchPath, diodeName, x, y)
P = @(a, b, w, h) [a b a+w b+h];
diode = [M '/' diodeName];
add_block('powerlib/Power Electronics/Diode', diode, ...
    'Position', P(x, y, 28, 26));
set_param(diode, 'Ron', '1e-3', 'Lon', '0', 'Vf', '0.8', ...
    'UseSnubber', 'off');
add_line(M, ph(switchPath, 'RConn', 1), ph(diode, 'LConn', 1), ...
    'autorouting', 'on');
add_line(M, ph(diode, 'RConn', 1), ph(switchPath, 'LConn', 1), ...
    'autorouting', 'on');
end

function set_matlab_function_code(blockPath, codeText)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = codeText;
end

function codeText = pll_dq_controller_code()
codeText = strjoin({ ...
    ['function [m_ref6, ctrl_dbg] = fcn(Vabc, ts, grid_f0, vref_lv, ', ...
    'vreg_kp, vreg_ki, m_max, pll_kp, pll_ki, inj_phase, swell_gain)'], ...
    '%#codegen', ...
    'persistent theta xi_pll xi_a xi_b xi_c t_ctrl v_rms_f', ...
    'if isempty(theta)', ...
    '    theta = 0;', ...
    '    xi_pll = 0;', ...
    '    xi_a = 0;', ...
    '    xi_b = 0;', ...
    '    xi_c = 0;', ...
    '    t_ctrl = 0;', ...
    '    v_rms_f = 0;', ...
    'end', ...
    't_ctrl = t_ctrl + ts;', ...
    'm_ref6 = zeros(6, 1);', ...
    'ctrl_dbg = zeros(7, 1);', ...
    'va = Vabc(1);', ...
    'vb = Vabc(2);', ...
    'vc = Vabc(3);', ...
    'alpha = (2/3) * (va - 0.5*vb - 0.5*vc);', ...
    'beta = (sqrt(3)/3) * (vb - vc);', ...
    'theta_meas = atan2(beta, alpha);', ...
    'pll_err = atan2(sin(theta_meas - theta), cos(theta_meas - theta));', ...
    'xi_pll = xi_pll + pll_ki * pll_err * ts;', ...
    'omega = 2*pi*grid_f0 + pll_kp * pll_err + xi_pll;', ...
    'theta = theta + omega * ts;', ...
    'theta = theta - 2*pi*floor(theta/(2*pi));', ...
    'ct = cos(theta);', ...
    'st = sin(theta);', ...
    'vd = alpha*ct + beta*st;', ...
    'vq = -alpha*st + beta*ct;', ...
    'v_rms = sqrt(max((va*va + vb*vb + vc*vc) / 3, 0));', ...
    'if v_rms_f == 0', ...
    '    v_rms_f = v_rms;', ...
    'end', ...
    'alpha_v = min(max(ts / 0.005, 0), 1);', ...
    'v_rms_f = v_rms_f + alpha_v * (v_rms - v_rms_f);', ...
    'v_meas = v_rms_f;', ...
    'v_err = vref_lv - v_meas;', ...
    'err_pu = v_err / max(vref_lv, 1e-6);', ...
    'phi = inj_phase;', ...
    'if abs(err_pu) < 0.002', ...
    '    kp_eff = 0;', ...
    '    ki_eff = 0;', ...
    '    xi_a = 0;', ...
    '    xi_b = 0;', ...
    '    xi_c = 0;', ...
    '    err_eff = 0;', ...
    'elseif err_pu >= 0', ...
    '    kp_eff = abs(vreg_kp);', ...
    '    ki_eff = abs(vreg_ki);', ...
    '    err_eff = err_pu;', ...
    'else', ...
    '    kp_eff = abs(vreg_kp) * swell_gain;', ...
    '    ki_eff = abs(vreg_ki) * swell_gain;', ...
    '    err_eff = err_pu;', ...
    '    if kp_eff == 0 && ki_eff == 0', ...
    '        xi_a = 0;', ...
    '        xi_b = 0;', ...
    '        xi_c = 0;', ...
    '    end', ...
    'end', ...
    'if t_ctrl > 0.02', ...
    '    xi_a = xi_a + ki_eff * err_eff * ts;', ...
    'else', ...
    '    xi_a = 0;', ...
    'end', ...
    'm_unsat = kp_eff * err_eff + xi_a;', ...
    'm_cmd = min(max(m_unsat, -m_max), m_max);', ...
    'if m_cmd ~= m_unsat', ...
    '    xi_a = m_cmd - kp_eff * err_eff;', ...
    'end', ...
    'ma = m_cmd * sin(theta + phi);', ...
    'mb = m_cmd * sin(theta + phi - 2*pi/3);', ...
    'mc = m_cmd * sin(theta + phi + 2*pi/3);', ...
    'm_amp = sqrt((ma*ma + mb*mb + mc*mc) / 3);', ...
    'm_ref6 = [ma; -ma; mb; -mb; mc; -mc];', ...
    'ctrl_dbg = [theta; vd; vq; v_meas; v_err; m_amp; phi];', ...
    'end' ...
    }, newline);
end

function codeText = energy_controller_code()
codeText = strjoin({ ...
    ['function [m_abc, dbg] = fcn(vdc, Vabc, Iabc, ts, grid_f0, vdc_ref, ', ...
    'vdc_kp, vdc_ki, id_max, cur_kp, cur_ki, mmax, pll_kp, pll_ki, ', ...
    'vff_gain, control_sign, polarity, open_amp, open_phase)'], ...
    '%#codegen', ...
    'persistent theta xi_pll xi_vdc xi_id xi_iq t_ctrl', ...
    'if isempty(theta)', ...
    '    theta = 0;', ...
    '    xi_pll = 0;', ...
    '    xi_vdc = 0;', ...
    '    xi_id = 0;', ...
    '    xi_iq = 0;', ...
    '    t_ctrl = 0;', ...
    'end', ...
    't_ctrl = t_ctrl + ts;', ...
    'va = Vabc(1); vb = Vabc(2); vc = Vabc(3);', ...
    'ia = Iabc(1); ib = Iabc(2); ic = Iabc(3);', ...
    'valpha = (2/3) * (va - 0.5*vb - 0.5*vc);', ...
    'vbeta = (sqrt(3)/3) * (vb - vc);', ...
    'ialpha = (2/3) * (ia - 0.5*ib - 0.5*ic);', ...
    'ibeta = (sqrt(3)/3) * (ib - ic);', ...
    'theta_meas = atan2(vbeta, valpha);', ...
    'pll_err = atan2(sin(theta_meas - theta), cos(theta_meas - theta));', ...
    'xi_pll = xi_pll + pll_ki * pll_err * ts;', ...
    'omega = 2*pi*grid_f0 + pll_kp * pll_err + xi_pll;', ...
    'theta = theta + omega * ts;', ...
    'theta = theta - 2*pi*floor(theta/(2*pi));', ...
    'ct = cos(theta); st = sin(theta);', ...
    'if open_amp > 0', ...
    '    mo = min(open_amp, mmax);', ...
    '    ma = mo * sin(theta + open_phase);', ...
    '    mb = mo * sin(theta + open_phase - 2*pi/3);', ...
    '    mc = mo * sin(theta + open_phase + 2*pi/3);', ...
    '    p_ac = va*ia + vb*ib + vc*ic;', ...
    '    m_abc = polarity * [ma; mb; mc];', ...
    '    dbg = [theta; 0; 0; 0; 0; 0; vdc; vdc_ref-vdc; p_ac; ma; mb; mc];', ...
    '    return;', ...
    'end', ...
    'vd = valpha*ct + vbeta*st;', ...
    'vq = -valpha*st + vbeta*ct;', ...
    'id = ialpha*ct + ibeta*st;', ...
    'iq = -ialpha*st + ibeta*ct;', ...
    'err = vdc_ref - vdc;', ...
    'if abs(err) < 3 || t_ctrl < 0.02', ...
    '    xi_vdc = 0;', ...
    '    id_ref = 0;', ...
    'else', ...
    '    xi_vdc = xi_vdc + vdc_ki * err * ts;', ...
    '    id_unsat = vdc_kp * err + xi_vdc;', ...
    '    id_ref = min(max(id_unsat, -id_max), id_max);', ...
    '    if id_ref ~= id_unsat', ...
    '        xi_vdc = id_ref - vdc_kp * err;', ...
    '    end', ...
    'end', ...
    'iq_ref = 0;', ...
    'eid = id_ref - id;', ...
    'eiq = iq_ref - iq;', ...
    'xi_id = xi_id + cur_ki * eid * ts;', ...
    'xi_iq = xi_iq + cur_ki * eiq * ts;', ...
    'vd_ctrl = cur_kp * eid + xi_id;', ...
    'vq_ctrl = cur_kp * eiq + xi_iq;', ...
    'vconv_d = vff_gain * vd - control_sign * vd_ctrl;', ...
    'vconv_q = vff_gain * vq - control_sign * vq_ctrl;', ...
    'conv_alpha = vconv_d*ct - vconv_q*st;', ...
    'conv_beta = vconv_d*st + vconv_q*ct;', ...
    'ma_unsat = 2 * conv_alpha / max(abs(vdc), 50);', ...
    'mb_unsat = 2 * (-0.5*conv_alpha + (sqrt(3)/2)*conv_beta) / max(abs(vdc), 50);', ...
    'mc_unsat = 2 * (-0.5*conv_alpha - (sqrt(3)/2)*conv_beta) / max(abs(vdc), 50);', ...
    'ma = min(max(ma_unsat, -mmax), mmax);', ...
    'mb = min(max(mb_unsat, -mmax), mmax);', ...
    'mc = min(max(mc_unsat, -mmax), mmax);', ...
    'if abs(ma) >= mmax || abs(mb) >= mmax || abs(mc) >= mmax', ...
    '    xi_id = xi_id - cur_ki * eid * ts;', ...
    '    xi_iq = xi_iq - cur_ki * eiq * ts;', ...
    'end', ...
    'm_abc = polarity * [ma; mb; mc];', ...
    'p_ac = va*ia + vb*ib + vc*ic;', ...
    'dbg = [theta; vd; vq; id; iq; id_ref; vdc; err; p_ac; ma; mb; mc];', ...
    'end' ...
    }, newline);
end

function h = ph(blk, kind, idx)
P = get_param(blk, 'PortHandles');
h = P.(kind)(idx);
end
