% Export strong-dq and final family-SAC traces for a boundary-expansion case.
%
% Case: topology2 A-phase LVRT, 0.50 pu, 200 ms.  The switch-level
% boundary matrix reports strong dq fail and family SAC r6 pass.

rootDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
simDir = fullfile(rootDir, 'version_2', 'simulink');
addpath(genpath(simDir));
cd(simDir);

commonParams = struct( ...
    'hpt_m_reg_max', 0.6, ...
    'hpt_sac_reg_max', 0.6, ...
    'hpt_sac_reg_q_gain', -1.0, ...
    'hpt_inj_phase_offset', -1.05, ...
    'hpt_energy_i_kp', 0.25, ...
    'hpt_energy_i_ki', 45.0, ...
    'hpt_energy_vff_gain', 0.2, ...
    'hpt_energy_control_sign', -1.0, ...
    'hpt_energy_bridge_polarity', -1.0, ...
    'hpt_sac_fault_time_norm_s', 0.12, ...
    'hpt_sac_recovery_time_norm_s', 0.12, ...
    'hpt_vreg_kp', 5.6, ...
    'hpt_vreg_ki', 0.35, ...
    'hpt_vdc_kp', 0.0, ...
    'hpt_vdc_ki', 0.0, ...
    'hpt_conventional_energy_scale', 0.0, ...
    'hpt_conventional_recovery_reg_gain', 2.4, ...
    'hpt_conventional_recovery_reg_max', 0.44);

hpt_trace_topology = "topology2";
hpt_trace_fault_pu = 0.50;
hpt_trace_fault_phase_pu = [0.50, 1.0, 1.0];
hpt_trace_fault_duration = 0.200;
hpt_trace_fault_start = 0.080;
hpt_trace_fault_stop_margin = 0.125;
hpt_trace_actor_filter_tau = 0.001;
hpt_trace_model_params = commonParams;
hpt_trace_sample_stride = 100;

% Strong conventional dq trace.
hpt_trace_policy_mode = 0.0;
hpt_trace_actor_select_mode = 0.0;
hpt_trace_run_label = "r6_boundary_pu0500_d200ms_strong_dq";
run(fullfile(simDir, 'collectors', 'collect_hpt_v2_trajectory_trace.m'));

% Final family SAC r6 trace.  The actor archive must already be exported as
% version_2/simulink/hpt_sac_actor_weights_dynamic.mat.
hpt_trace_policy_mode = 1.0;
hpt_trace_actor_select_mode = 3.0;
hpt_trace_run_label = "r6_boundary_pu0500_d200ms_family_sac";
simDir = fullfile(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))), ...
    'version_2', 'simulink');
run(fullfile(simDir, 'collectors', 'collect_hpt_v2_trajectory_trace.m'));
