%% run_pipeline_scenarios.m
% Re-run 350 fixed scenarios with Mode-7 (FAHC) using the strategy table
% generated by ai/msffn_pipeline.py.
%
% Prerequisites:
%   1. scenario_table_hpt_v2.csv exists (run generate_hpt_v2_scenario_table.py first)
%   2. msffn_fahc_strategy_table.csv exists (run ai/msffn_pipeline.py first)
%   3. hpt_switching_model.slx exists in ../simulink/ (run build_hpt_switching_model.m)
%
% Output:
%   ../data/raw_switching_hpt_v2_pipeline/  — 350 .mat files, Mode 7 + MSFFN strategies
%
% Usage:
%   matlab -batch "run_pipeline_scenarios"   % from data_collection/ directory
%   OR open in MATLAB and press Run

clear; clc;
addpath('../simulink');

%% Paths (all absolute, derived from this script's location)
% Strategy table and output dir can be overridden via environment variables:
%   HPT_PIPELINE_STRATEGY_TABLE — path to a specific strategy CSV
%   HPT_PIPELINE_OUT_DIR        — path to a specific output directory
SCRIPT_DIR    = fileparts(mfilename('fullpath'));
PROJECT_ROOT  = fullfile(SCRIPT_DIR, '..');
SCENARIO_TABLE = fullfile(SCRIPT_DIR, 'scenario_table_hpt_v2.csv');

env_strat = getenv('HPT_PIPELINE_STRATEGY_TABLE');
if ~isempty(env_strat)
    STRATEGY_TABLE = env_strat;
else
    STRATEGY_TABLE = fullfile(SCRIPT_DIR, 'msffn_fahc_strategy_table.csv');
end

env_out = getenv('HPT_PIPELINE_OUT_DIR');
if ~isempty(env_out)
    OUT_DIR = env_out;
else
    OUT_DIR = fullfile(PROJECT_ROOT, 'data', 'raw_switching_hpt_v2_pipeline');
end

%% Pre-flight checks
if ~exist(SCENARIO_TABLE, 'file')
    error('[pipeline] Scenario table not found: %s\n  Run: python data_collection/generate_hpt_v2_scenario_table.py', SCENARIO_TABLE);
end
if ~exist(STRATEGY_TABLE, 'file')
    error('[pipeline] MSFFN strategy table not found: %s\n  Run: python ai/msffn_pipeline.py', STRATEGY_TABLE);
end

fprintf('[pipeline] Scenario table : %s\n', SCENARIO_TABLE);
fprintf('[pipeline] Strategy table : %s\n', STRATEGY_TABLE);
fprintf('[pipeline] Output dir     : %s\n', OUT_DIR);

%% Configure env vars for run_switching_scenarios.m
setenv('HPT_SCENARIO_TABLE',      SCENARIO_TABLE);
setenv('HPT_FAHC_STRATEGY_TABLE', STRATEGY_TABLE);
setenv('HPT_CONTROLLER_MODE',     '7');
setenv('HPT_SWITCHING_OUT_DIR',   OUT_DIR);

% Clear other table env vars so they don't interfere
setenv('HPT_PPO_ACTION_TABLE', '');
setenv('HPT_RCN_REF_TABLE',    '');

fprintf('[pipeline] Controller mode: 7 (FAHC + MSFFN strategies)\n');
fprintf('[pipeline] Starting simulation...\n\n');

%% Run
run('run_switching_scenarios.m');

%% Clean up env vars
setenv('HPT_SCENARIO_TABLE',      '');
setenv('HPT_FAHC_STRATEGY_TABLE', '');
setenv('HPT_CONTROLLER_MODE',     '');
setenv('HPT_SWITCHING_OUT_DIR',   '');

fprintf('\n[pipeline] Done. Run LVRT metrics:\n');
fprintf('  python ai/lvrt_metrics.py --raw-dir data/raw_switching_hpt_v2_pipeline\n');
fprintf('  python ai/control_method_comparison.py\n');
