%% build_hpt_switching_model.m
% Build a switching-level Specialized Power Systems HPT model.
%
% Scope:
%   - Main power path: 10 kV source -> series injection transformer ->
%     10 kV/400 V line-frequency transformer -> 400 V load
%   - Energy-extraction converter: shunt VSC at the 400 V bus, maintaining DC link
%   - Regulation converter: three single-phase H-bridges injecting series voltage
%   - Shared DC-link capacitor, L/R shunt filters, three-phase AC fault
%   - Measurement/logging outputs for verification

clear; clc;
run('parameters.m');

MODEL = 'hpt_switching_model';

if bdIsLoaded(MODEL)
    close_system(MODEL, 0);
end
if exist([MODEL '.slx'], 'file')
    delete([MODEL '.slx']);
end

new_system(MODEL);
open_system(MODEL);

Ts_switch = 1e-5;
set_param(MODEL, ...
    'Solver', 'ode3', ...
    'SolverType', 'Fixed-step', ...
    'FixedStep', num2str(Ts_switch), ...
    'StopTime', '0.05', ...
    'ReturnWorkspaceOutputs', 'on');

%% Utility positions
pos = @(x,y,w,h) [x y x+w y+h];

%% Powergui
add_block('powerlib/powergui', [MODEL '/powergui'], ...
    'SimulationMode', 'Discrete', ...
    'SampleTime', num2str(Ts_switch), ...
    'Position', pos(30,30,110,45));

add_block('simulink/Sources/Constant', [MODEL '/Sc_id'], ...
    'Value', '0', 'Position', pos(30,120,60,30));
add_block('simulink/Sources/Constant', [MODEL '/T_fault'], ...
    'Value', '99', 'Position', pos(30,165,60,30));
add_block('simulink/Sources/Constant', [MODEL '/FaultVariant'], ...
    'Value', '1', 'Position', pos(30,210,60,30));
add_block('simulink/Sources/Constant', [MODEL '/FaultMag'], ...
    'Value', '1', 'Position', pos(30,255,60,30));
add_block('simulink/Sources/Constant', [MODEL '/ControllerMode'], ...
    'Value', '2', 'Position', pos(30,300,60,30));
add_block('simulink/Sources/Constant', [MODEL '/RL_Energy_Bias'], ...
    'Value', '0', 'Position', pos(30,345,60,30));
add_block('simulink/Sources/Constant', [MODEL '/RL_Reg_Bias'], ...
    'Value', '0', 'Position', pos(30,390,60,30));
add_block('simulink/Sources/Constant', [MODEL '/RL_Current_Bias'], ...
    'Value', '0', 'Position', pos(30,435,60,30));
add_block('simulink/Sources/Constant', [MODEL '/VDC_Ref_Delta'], ...
    'Value', '0', 'Position', pos(30,480,60,30));
add_block('simulink/Sources/Constant', [MODEL '/V2_Ref_Delta'], ...
    'Value', '0', 'Position', pos(30,525,60,30));
add_block('simulink/Sources/Constant', [MODEL '/ILim_Delta'], ...
    'Value', '0', 'Position', pos(30,570,60,30));
add_block('simulink/Sources/Constant', [MODEL '/FAHC_Strategy'], ...
    'Value', '0', 'Position', pos(30,615,60,30));

%% Grid source and main transformer
add_block('powerlib/Electrical Sources/Three-Phase Source', [MODEL '/Grid'], ...
    'Voltage', num2str(V_grid_ll), ...
    'Frequency', num2str(f_grid), ...
    'SpecifyImpedance', 'on', ...
    'Resistance', num2str(real(Z_grid)), ...
    'Inductance', num2str(imag(Z_grid)/w_grid), ...
    'Position', pos(80,560,95,95));

add_block('powerlib/Measurements/Three-Phase V-I Measurement', [MODEL '/Meas_Primary'], ...
    'VoltageMeasurement', 'phase-to-ground', ...
    'CurrentMeasurement', 'yes', ...
    'OutputType', 'Complex', ...
    'Position', pos(230,560,95,95));

%% Regulation converter: series VSC injection H-bridges
for k = 1:3
    y = 440 + (k-1)*115;
    add_block('powerlib/Power Electronics/Universal Bridge', ...
        sprintf('%s/Regulation_VSC_phase_%d', MODEL, k), ...
        'Arms', '2', ...
        'Device', 'IGBT / Diodes', ...
        'SnubberResistance', '1e5', ...
        'SnubberCapacitance', '1e-9', ...
        'Ron', '1e-3', ...
        'Measurements', 'All voltages and currents', ...
        'Position', pos(1120,y+390,120,90));
    add_block('powerlib/Elements/Linear Transformer', ...
        sprintf('%s/Series_Injection_Transformer_%d', MODEL, k), ...
        'UNITS', 'pu', ...
        'NominalPower', ['[', num2str(S_pe/3), ' ', num2str(f_grid), ']'], ...
        'winding1', ['[', num2str(V_dc_ref/2), ' 0.001 0.001]'], ...
        'winding2', ['[', num2str(V_se_max), ' 0.001 0.001]'], ...
        'ThreeWindings', 'off', ...
        'RmLm', '[500 500]', ...
        'Position', pos(400,y,105,90));
end

add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/Regulation_VSC_SPWM'], ...
    'Position', pos(880,850,170,105));
vse_code = [
"function [gsea,gseb,gsec] = vse_spwm(t,sc_id,t_fault,variant,fault_mag,v2abc,i2abc,vdc," ...
"controller_mode,rl_energy_bias,rl_reg_bias,rl_current_bias," ...
"vdc_ref_delta,v2_ref_delta,ilim_delta,fahc_strategy)" newline ...
"%#codegen" newline ...
"persistent ivac last_t" newline ...
"if isempty(ivac) || t < 1e-9" newline ...
"    ivac = 0; last_t = t;" newline ...
"end" newline ...
"dt = max(0, min(1e-4, t - last_t));" newline ...
"last_t = t;" newline ...
"f1 = 50; fc = 5000;" newline ...
"theta = 2*pi*f1*t;" newline ...
"carrier = 2*abs(2*(fc*t - floor(fc*t + 0.5))) - 1;" newline ...
"v2 = real(v2abc);" newline ...
"i2 = real(i2abc);" newline ...
"vll = sqrt(((v2(1)-v2(2))^2 + (v2(2)-v2(3))^2 + (v2(3)-v2(1))^2)/3);" newline ...
"vpu = vll / 400;" newline ...
"ipu = max(abs(i2)) / 816.5;" newline ...
"sag = max(0, 0.98 - vpu);" newline ...
"m = min(0.24, max(0.02, 0.045 + 0.42*sag));" newline ...
"if int32(controller_mode) == 4" newline ...
"    ev = 1.0 - vpu;" newline ...
"    ivac = min(0.20, max(-0.20, ivac + ev*dt*80));" newline ...
"    m = 0.030 + 0.55*max(0, ev) + 0.18*ivac;" newline ...
"    if abs(vdc) < 720" newline ...
"        m = min(m, 0.06);" newline ...
"    end" newline ...
"    if abs(vdc) > 960" newline ...
"        m = min(m, 0.04);" newline ...
"    end" newline ...
"end" newline ...
"if int32(controller_mode) == 5" newline ...
"    ev = 1.0 - vpu;" newline ...
"    reg_bias = min(1.0, max(-1.0, rl_reg_bias));" newline ...
"    cur_bias = min(1.0, max(-1.0, rl_current_bias));" newline ...
"    ivac = min(0.24, max(-0.24, ivac + ev*dt*(80 + 40*max(0, reg_bias))));" newline ...
"    m = 0.030 + (0.55 + 0.20*reg_bias)*max(0, ev) + 0.18*ivac + 0.05*reg_bias;" newline ...
"    if abs(vdc) < 720" newline ...
"        m = min(m, 0.08 + 0.03*max(0, reg_bias));" newline ...
"    end" newline ...
"    if abs(vdc) > 960" newline ...
"        m = min(m, 0.04 + 0.02*max(0, cur_bias));" newline ...
"    end" newline ...
"end" newline ...
"if int32(controller_mode) == 3" newline ...
"    [~, m_ai] = dnn_frt_policy(abs(vdc)/800, vpu, ipu, double(t >= t_fault), sc_id);" newline ...
"    m = m_ai;" newline ...
"end" newline ...
"if int32(controller_mode) == 6 || int32(controller_mode) == 7" newline ...
"    if int32(controller_mode) == 7" newline ...
"        strat = int32(0);" newline ...
"        if t >= t_fault + 0.005; strat = int32(fahc_strategy); end" newline ...
"        if strat == 1; vdc_ref_eff = 760.0; ilim_eff = 2.8;" newline ...
"        elseif strat == 2; vdc_ref_eff = 740.0; ilim_eff = 2.8;" newline ...
"        elseif strat == 3; vdc_ref_eff = 720.0; ilim_eff = 2.5;" newline ...
"        else; vdc_ref_eff = 800.0; ilim_eff = 3.0; end" newline ...
"        v2_ref_eff = 400.0;" newline ...
"    else" newline ...
"        v2_ref_eff = 400.0;" newline ...
"        vdc_ref_eff = max(720.0, min(840.0, 800.0 + vdc_ref_delta));" newline ...
"        ilim_eff   = max(2.5,   min(3.5,   3.0   + ilim_delta));" newline ...
"    end" newline ...
"    ev = (v2_ref_eff / 400.0) - vpu;" newline ...
"    ivac = min(0.20, max(-0.20, ivac + ev*dt*80));" newline ...
"    m = 0.030 + 0.55*max(0, ev) + 0.18*ivac;" newline ...
"    if abs(vdc) < 720.0" newline ...
"        m = min(m, 0.06);" newline ...
"    end" newline ...
"    if abs(vdc) > 960.0" newline ...
"        m = min(m, 0.04);" newline ...
"    end" newline ...
"    if ipu > ilim_eff" newline ...
"        m = min(m, 0.02);" newline ...
"    end" newline ...
"end" newline ...
"if int32(sc_id) == 6 || int32(sc_id) == 7" newline ...
"    if t >= t_fault" newline ...
"        if int32(controller_mode) ~= 3 && int32(controller_mode) ~= 4 && int32(controller_mode) ~= 6 && int32(controller_mode) ~= 7" newline ...
"            m = 0.015;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"ipu_limit = 2.0;" newline ...
"if int32(controller_mode) == 5" newline ...
"    ipu_limit = 2.0 + 0.8*max(0, min(1.0, rl_current_bias));" newline ...
"end" newline ...
"if ipu > ipu_limit && int32(controller_mode) ~= 6 && int32(controller_mode) ~= 7" newline ...
"    m = min(m, 0.02 + 0.04*max(0, min(1.0, rl_current_bias)));" newline ...
"end" newline ...
"m = min(0.30, max(0.0, m));" newline ...
"va_ref = m*sin(theta);" newline ...
"vb_ref = m*sin(theta - 2*pi/3);" newline ...
"vc_ref = m*sin(theta + 2*pi/3);" newline ...
"ga = va_ref >= carrier;" newline ...
"gb = vb_ref >= carrier;" newline ...
"gc = vc_ref >= carrier;" newline ...
"gsea = double([ga; ~ga; ~ga; ga]);" newline ...
"gseb = double([gb; ~gb; ~gb; gb]);" newline ...
"gsec = double([gc; ~gc; ~gc; gc]);" newline ...
"if t >= t_fault && (int32(sc_id) == 4 || int32(sc_id) == 8)" newline ...
"    idx = max(1,min(4,int32(variant)));" newline ...
"    scale = max(0,min(1,1 - fault_mag));" newline ...
"    if idx == 1, gsea(1) = gsea(1)*scale; end" newline ...
"    if idx == 2, gsea(2) = gsea(2)*scale; end" newline ...
"    if idx == 3, gsea(3) = gsea(3)*scale; end" newline ...
"    if idx == 4, gsea(4) = gsea(4)*scale; end" newline ...
"end" newline ...
];
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [MODEL '/Regulation_VSC_SPWM']);
chart.Script = char(strjoin(vse_code, ''));

add_block('powerlib/Elements/Three-Phase Transformer (Two Windings)', [MODEL '/Main_Line_Frequency_Transformer'], ...
    'NominalPower', ['[', num2str(S_rated), ' ', num2str(f_grid), ']'], ...
    'Winding1Connection', 'Delta (D1)', ...
    'Winding2Connection', 'Yg', ...
    'Winding1', ['[', num2str(V_primary), ' 0.002 0.01]'], ...
    'Winding2', ['[', num2str(V_secondary), ' 0.002 0.01]'], ...
    'Rm', '500', ...
    'Lm', '500', ...
    'Position', pos(575,545,135,135));

add_block('powerlib/Measurements/Three-Phase V-I Measurement', [MODEL '/Meas_Secondary'], ...
    'VoltageMeasurement', 'phase-to-ground', ...
    'CurrentMeasurement', 'yes', ...
    'OutputType', 'Complex', ...
    'Position', pos(770,560,95,95));

%% Load and AC fault on secondary bus
add_block('powerlib/Elements/Three-Phase Parallel RLC Load', [MODEL '/LV_Load'], ...
    'NominalVoltage', num2str(V_secondary), ...
    'NominalFrequency', num2str(f_grid), ...
    'ActivePower', num2str(S_rated * 0.8), ...
    'InductivePower', num2str(S_rated * 0.2), ...
    'CapacitivePower', '0', ...
    'Position', pos(945,540,100,80));

add_block('powerlib/Elements/Three-Phase Fault', [MODEL '/LV_AC_Fault'], ...
    'InitialStates', '0', ...
    'FaultA', 'on', 'FaultB', 'on', 'FaultC', 'on', 'GroundFault', 'on', ...
    'SwitchTimes', '[99 100]', ...
    'FaultResistance', '0.01', ...
    'GroundResistance', '0.01', ...
    'Position', pos(945,665,100,90));

%% Energy-extraction converter: shunt VSC filter branches on LV bus
for k = 1:3
    y = 210 + (k-1)*60;
    add_block('powerlib/Elements/Series RLC Branch', sprintf('%s/Energy_Filter_%d', MODEL, k), ...
        'BranchType', 'RL', ...
        'Resistance', num2str(R_sh), ...
        'Inductance', num2str(L_sh), ...
        'Position', pos(780,y,105,32));
end

%% Energy-extraction Universal Bridge and DC link
add_block('powerlib/Power Electronics/Universal Bridge', [MODEL '/Energy_Extraction_VSC'], ...
    'Arms', '3', ...
    'Device', 'IGBT / Diodes', ...
    'SnubberResistance', '1e5', ...
    'SnubberCapacitance', '1e-9', ...
    'Ron', '1e-3', ...
    'Measurements', 'All voltages and currents', ...
    'Position', pos(965,185,145,165));

add_block('powerlib/Elements/Series RLC Branch', [MODEL '/DC_Link_Capacitor'], ...
    'BranchType', 'C', ...
    'Capacitance', num2str(C_dc), ...
    'Setx0', 'on', ...
    'InitialVoltage', num2str(V_dc_init), ...
    'Position', pos(1325,300,90,45));

add_block('powerlib/Elements/Series RLC Branch', [MODEL '/DC_Link_Damping_Resistor'], ...
    'BranchType', 'R', ...
    'Resistance', '8.2', ...
    'Position', pos(1325,375,90,35));

add_block('powerlib/Elements/Breaker', [MODEL '/DC_Link_Cap_Breaker'], ...
    'InitialState', '1', ...
    'SwitchingTimes', '[99]', ...
    'External', 'off', ...
    'BreakerResistance', '0.01', ...
    'Position', pos(1255,300,50,45));

add_block('powerlib/Measurements/Voltage Measurement', [MODEL '/Meas_DC_Link_Voltage'], ...
    'OutputType', 'Magnitude', ...
    'Position', pos(1325,220,85,45));

%% PWM gate generator
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/Energy_VSC_SPWM'], ...
    'Position', pos(880,20,175,105));

gate_code = [
"function g = spwm_gates(t,sc_id,t_fault,variant,fault_mag,vdc,v2abc,i2abc," ...
"controller_mode,rl_energy_bias,rl_reg_bias,rl_current_bias," ...
"vdc_ref_delta,v2_ref_delta,ilim_delta,fahc_strategy)" newline ...
"%#codegen" newline ...
"persistent ivdc last_t" newline ...
"if isempty(ivdc) || t < 1e-9" newline ...
"    ivdc = 0; last_t = t;" newline ...
"end" newline ...
"dt = max(0, min(1e-4, t - last_t));" newline ...
"last_t = t;" newline ...
"f1 = 50; fc = 5000;" newline ...
"theta = 2*pi*f1*t;" newline ...
"carrier = 2*abs(2*(fc*t - floor(fc*t + 0.5))) - 1;" newline ...
"v2 = real(v2abc);" newline ...
"i2 = real(i2abc);" newline ...
"vll = sqrt(((v2(1)-v2(2))^2 + (v2(2)-v2(3))^2 + (v2(3)-v2(1))^2)/3);" newline ...
"vpu = vll / 400;" newline ...
"ipu = max(abs(i2)) / 816.5;" newline ...
"if int32(controller_mode) == 7" newline ...
"    strat = int32(0);" newline ...
"    if t >= t_fault + 0.005; strat = int32(fahc_strategy); end" newline ...
"    if strat == 1; vdc_ref_eff = 760.0;" newline ...
"    elseif strat == 2; vdc_ref_eff = 740.0;" newline ...
"    elseif strat == 3; vdc_ref_eff = 720.0;" newline ...
"    else; vdc_ref_eff = 800.0; end" newline ...
"elseif int32(controller_mode) == 6" newline ...
"    vdc_ref_eff = max(720.0, min(840.0, 800.0 + vdc_ref_delta));" newline ...
"else" newline ...
"    vdc_ref_eff = 800.0;" newline ...
"end" newline ...
"evdc = (vdc_ref_eff - abs(vdc)) / vdc_ref_eff;" newline ...
"ivdc = min(0.35, max(-0.35, ivdc + evdc*dt*350));" newline ...
"m = 0.68 + 0.30*evdc + 0.08*ivdc;" newline ...
"if int32(controller_mode) == 3" newline ...
"    [m_ai, ~] = dnn_frt_policy(abs(vdc)/800, vpu, ipu, double(t >= t_fault), sc_id);" newline ...
"    m = m_ai;" newline ...
"end" newline ...
"if int32(sc_id) == 6 || int32(sc_id) == 7" newline ...
"    if t >= t_fault" newline ...
"        if int32(controller_mode) ~= 3 && int32(controller_mode) ~= 4 && int32(controller_mode) ~= 6 && int32(controller_mode) ~= 7" newline ...
"            m = min(m, 0.32);" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if int32(controller_mode) == 4" newline ...
"    if t >= t_fault && (int32(sc_id) == 6 || int32(sc_id) == 7)" newline ...
"        m = min(m, 0.42);" newline ...
"    end" newline ...
"end" newline ...
"if int32(controller_mode) == 5" newline ...
"    e_bias = min(1.0, max(-1.0, rl_energy_bias));" newline ...
"    cur_bias = min(1.0, max(-1.0, rl_current_bias));" newline ...
"    m = m + 0.14*e_bias;" newline ...
"    if t >= t_fault && (int32(sc_id) == 6 || int32(sc_id) == 7)" newline ...
"        m = min(m, 0.42 + 0.16*max(0, e_bias));" newline ...
"    end" newline ...
"    if ipu > 2.0 + 0.8*max(0, cur_bias)" newline ...
"        m = min(m, 0.20 + 0.08*max(0, cur_bias));" newline ...
"    end" newline ...
"end" newline ...
"if int32(controller_mode) == 6 || int32(controller_mode) == 7" newline ...
"    if t >= t_fault && (int32(sc_id) == 6 || int32(sc_id) == 7)" newline ...
"        m = min(m, 0.42);" newline ...
"    end" newline ...
"end" newline ...
"% Protection floors anchored to 800V (LVRT criterion is absolute)" newline ...
"if abs(vdc) > 920.0 || ipu > 2.0" newline ...
"    m = min(m, 0.25);" newline ...
"end" newline ...
"if abs(vdc) > 1048.0 || ipu > 3.0" newline ...
"    m = min(m, 0.12);" newline ...
"end" newline ...
"if abs(vdc) < 780.0" newline ...
"    m = max(m, 0.64);" newline ...
"end" newline ...
"if abs(vdc) < 740.0" newline ...
"    m = max(m, 0.78);" newline ...
"end" newline ...
"if abs(vdc) < 700.0" newline ...
"    m = max(m, 0.86);" newline ...
"end" newline ...
"if abs(vdc) < 600.0" newline ...
"    m = max(m, 0.90);" newline ...
"end" newline ...
"m = min(0.92, max(0.20, m));" newline ...
"va = m*sin(theta);" newline ...
"vb = m*sin(theta - 2*pi/3);" newline ...
"vc = m*sin(theta + 2*pi/3);" newline ...
"ga = va >= carrier;" newline ...
"gb = vb >= carrier;" newline ...
"gc = vc >= carrier;" newline ...
"g = double([ga; ~ga; gb; ~gb; gc; ~gc]);" newline ...
"if t >= t_fault && (int32(sc_id) == 3 || int32(sc_id) == 8)" newline ...
"    idx = max(1,min(6,int32(variant)));" newline ...
"    scale = max(0,min(1,1 - fault_mag));" newline ...
"    g(idx) = g(idx)*scale;" newline ...
"end" newline ...
];
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [MODEL '/Energy_VSC_SPWM']);
chart.Script = char(strjoin(gate_code, ''));

add_block('simulink/Sources/Clock', [MODEL '/Clock'], ...
    'Position', pos(710,55,55,30));

%% Power calculation and logging
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/Power_Calc'], ...
    'Position', pos(1160,520,170,95));
pwr_code = [
"function [P,Q] = power_calc(vabc,iabc)" newline ...
"%#codegen" newline ...
"P = sum(vabc .* iabc);" newline ...
"alpha_v = (2/3)*(vabc(1)-0.5*vabc(2)-0.5*vabc(3));" newline ...
"beta_v = (2/3)*(sqrt(3)/2)*(vabc(2)-vabc(3));" newline ...
"alpha_i = (2/3)*(iabc(1)-0.5*iabc(2)-0.5*iabc(3));" newline ...
"beta_i = (2/3)*(sqrt(3)/2)*(iabc(2)-iabc(3));" newline ...
"Q = 1.5*(beta_v*alpha_i - alpha_v*beta_i);" newline ...
];
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [MODEL '/Power_Calc']);
chart.Script = char(strjoin(pwr_code, ''));

add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/Power_Calc_Secondary'], ...
    'Position', pos(1160,640,170,95));
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [MODEL '/Power_Calc_Secondary']);
chart.Script = char(strjoin(pwr_code, ''));

add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/DQ_Features'], ...
    'Position', pos(1160,760,190,125));
dq_code = [
"function [Ish_dq,Ise_dq,mode] = dq_features(t,i1abc,i2abc,vdc,sc_id,t_fault,~)" newline ...
"%#codegen" newline ...
"% Ish_dq(1): dc_err_proxy = 0.05*(800-Vdc) + 0.02*(id1-id2)" newline ...
"% Ish_dq(2): Iq2_kA = iq2/1000 (secondary q-axis current, kA units)" newline ...
"theta = 2*pi*50*t;" newline ...
"c = [cos(theta); cos(theta-2*pi/3); cos(theta+2*pi/3)];" newline ...
"s = [-sin(theta); -sin(theta-2*pi/3); -sin(theta+2*pi/3)];" newline ...
"id2 = (2/3)*sum(i2abc .* c);" newline ...
"iq2 = (2/3)*sum(i2abc .* s);" newline ...
"id1 = (2/3)*sum(i1abc .* c);" newline ...
"iq1 = (2/3)*sum(i1abc .* s);" newline ...
"fault = double(t >= t_fault);" newline ...
"dc_sig = 0.05*(800-vdc) + 0.02*(id1-id2);" newline ...
"Ish_dq = [dc_sig; iq2/1000];" newline ...
"Ise_dq = [(id1-id2)/1000; (iq1-iq2)/1000];" newline ...
"mode = 1 + fault * double(sc_id > 0);" newline ...
];
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [MODEL '/DQ_Features']);
chart.Script = char(strjoin(dq_code, ''));

log_names = {'V1_abc','I1_abc','V2_abc','I2_abc','V_dc','P1','Q1', ...
             'P2','Q2','Ish_dq','Ise_dq','mode'};
log_xy = [245 500; 245 690; 770 500; 770 700; 1435 225; ...
          1370 525; 1370 570; 1370 645; 1370 690; ...
          1370 765; 1370 810; 1370 855];
for k = 1:numel(log_names)
    add_block('simulink/Sinks/To Workspace', [MODEL '/' log_names{k}], ...
        'VariableName', log_names{k}, ...
        'SaveFormat', 'Array', ...
        'SampleTime', num2str(T_sample), ...
        'MaxDataPoints', 'inf', ...
        'Position', pos(log_xy(k,1),log_xy(k,2),115,30));
end

%% Electrical connections: source -> measurement -> transformer -> bus
for k = 1:3
    connect_port(MODEL, 'Grid', 'RConn', k, 'Meas_Primary', 'LConn', k);
    connect_port(MODEL, 'Meas_Primary', 'RConn', k, sprintf('Series_Injection_Transformer_%d', k), 'RConn', 1);
    connect_port(MODEL, sprintf('Series_Injection_Transformer_%d', k), 'RConn', 2, 'Main_Line_Frequency_Transformer', 'LConn', k);
    connect_port(MODEL, sprintf('Regulation_VSC_phase_%d', k), 'LConn', 1, sprintf('Series_Injection_Transformer_%d', k), 'LConn', 1);
    connect_port(MODEL, sprintf('Regulation_VSC_phase_%d', k), 'LConn', 2, sprintf('Series_Injection_Transformer_%d', k), 'LConn', 2);
    connect_port(MODEL, 'Main_Line_Frequency_Transformer', 'RConn', k, 'Meas_Secondary', 'LConn', k);
    connect_port(MODEL, 'Meas_Secondary', 'RConn', k, 'LV_Load', 'LConn', k);
    connect_port(MODEL, 'Meas_Secondary', 'RConn', k, 'LV_AC_Fault', 'LConn', k);
    connect_port(MODEL, 'Meas_Secondary', 'RConn', k, sprintf('Energy_Filter_%d', k), 'LConn', 1);
    connect_port(MODEL, sprintf('Energy_Filter_%d', k), 'RConn', 1, 'Energy_Extraction_VSC', 'LConn', k);
end

% DC link across bridge + and - terminals.
connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 1, 'DC_Link_Cap_Breaker', 'LConn', 1);
connect_port(MODEL, 'DC_Link_Cap_Breaker', 'RConn', 1, 'DC_Link_Capacitor', 'LConn', 1);
connect_port(MODEL, 'DC_Link_Capacitor', 'RConn', 1, 'Energy_Extraction_VSC', 'RConn', 2);
connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 1, 'DC_Link_Damping_Resistor', 'LConn', 1);
connect_port(MODEL, 'DC_Link_Damping_Resistor', 'RConn', 1, 'Energy_Extraction_VSC', 'RConn', 2);
connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 1, 'Meas_DC_Link_Voltage', 'LConn', 1);
connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 2, 'Meas_DC_Link_Voltage', 'LConn', 2);
for k = 1:3
    connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 1, sprintf('Regulation_VSC_phase_%d', k), 'RConn', 1);
    connect_port(MODEL, 'Energy_Extraction_VSC', 'RConn', 2, sprintf('Regulation_VSC_phase_%d', k), 'RConn', 2);
end

%% Signal connections
add_signal_goto(MODEL, 'Goto_Clock', 'hpt_clk', 780,55);
add_signal_goto(MODEL, 'Goto_ScId', 'hpt_sc_id', 125,120);
add_signal_goto(MODEL, 'Goto_TFault', 'hpt_t_fault', 125,165);
add_signal_goto(MODEL, 'Goto_FaultVariant', 'hpt_variant', 125,210);
add_signal_goto(MODEL, 'Goto_FaultMag', 'hpt_fault_mag', 125,255);
add_signal_goto(MODEL, 'Goto_ControllerMode', 'hpt_ctrl_mode', 125,300);
add_signal_goto(MODEL, 'Goto_RLEnergyBias', 'hpt_rl_energy_bias', 125,345);
add_signal_goto(MODEL, 'Goto_RLRegBias', 'hpt_rl_reg_bias', 125,390);
add_signal_goto(MODEL, 'Goto_RLCurrentBias', 'hpt_rl_current_bias', 125,435);
add_signal_goto(MODEL, 'Goto_VDCRefDelta',   'hpt_vdc_ref_delta',   125,480);
add_signal_goto(MODEL, 'Goto_V2RefDelta',    'hpt_v2_ref_delta',    125,525);
add_signal_goto(MODEL, 'Goto_ILimDelta',     'hpt_ilim_delta',      125,570);
add_signal_goto(MODEL, 'Goto_FAHCStrategy',  'hpt_fahc_strategy',   125,615);
add_signal_goto(MODEL, 'Goto_Vdc', 'hpt_vdc', 1425,250);
add_signal_goto(MODEL, 'Goto_V2abc', 'hpt_v2abc', 885,590);
add_signal_goto(MODEL, 'Goto_I2abc', 'hpt_i2abc', 885,705);
add_signal_goto(MODEL, 'Goto_I1abc', 'hpt_i1abc', 330,705);

add_line(MODEL, 'Clock/1', 'Goto_Clock/1', 'autorouting', 'on');
add_line(MODEL, 'Sc_id/1', 'Goto_ScId/1', 'autorouting', 'on');
add_line(MODEL, 'T_fault/1', 'Goto_TFault/1', 'autorouting', 'on');
add_line(MODEL, 'FaultVariant/1', 'Goto_FaultVariant/1', 'autorouting', 'on');
add_line(MODEL, 'FaultMag/1', 'Goto_FaultMag/1', 'autorouting', 'on');
add_line(MODEL, 'ControllerMode/1', 'Goto_ControllerMode/1', 'autorouting', 'on');
add_line(MODEL, 'RL_Energy_Bias/1', 'Goto_RLEnergyBias/1', 'autorouting', 'on');
add_line(MODEL, 'RL_Reg_Bias/1', 'Goto_RLRegBias/1', 'autorouting', 'on');
add_line(MODEL, 'RL_Current_Bias/1', 'Goto_RLCurrentBias/1', 'autorouting', 'on');
add_line(MODEL, 'VDC_Ref_Delta/1',  'Goto_VDCRefDelta/1',  'autorouting', 'on');
add_line(MODEL, 'V2_Ref_Delta/1',   'Goto_V2RefDelta/1',   'autorouting', 'on');
add_line(MODEL, 'ILim_Delta/1',     'Goto_ILimDelta/1',    'autorouting', 'on');
add_line(MODEL, 'FAHC_Strategy/1',  'Goto_FAHCStrategy/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_DC_Link_Voltage/1', 'Goto_Vdc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/1', 'Goto_V2abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/2', 'Goto_I2abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Primary/2', 'Goto_I1abc/1', 'autorouting', 'on');

add_controller_inputs(MODEL, 'Energy_VSC_SPWM', 760,20);
add_line(MODEL, 'From_Clock_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/1', 'autorouting', 'on');
add_line(MODEL, 'From_ScId_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/2', 'autorouting', 'on');
add_line(MODEL, 'From_TFault_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/3', 'autorouting', 'on');
add_line(MODEL, 'From_FaultVariant_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/4', 'autorouting', 'on');
add_line(MODEL, 'From_FaultMag_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/5', 'autorouting', 'on');
add_line(MODEL, 'From_Vdc_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/6', 'autorouting', 'on');
add_line(MODEL, 'From_V2abc_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/7', 'autorouting', 'on');
add_line(MODEL, 'From_I2abc_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/8', 'autorouting', 'on');
add_line(MODEL, 'From_ControllerMode_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/9', 'autorouting', 'on');
add_line(MODEL, 'From_RLEnergyBias_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/10', 'autorouting', 'on');
add_line(MODEL, 'From_RLRegBias_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/11', 'autorouting', 'on');
add_line(MODEL, 'From_RLCurrentBias_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/12', 'autorouting', 'on');
add_line(MODEL, 'From_VDCRefDelta_Energy_VSC_SPWM/1',  'Energy_VSC_SPWM/13', 'autorouting', 'on');
add_line(MODEL, 'From_V2RefDelta_Energy_VSC_SPWM/1',   'Energy_VSC_SPWM/14', 'autorouting', 'on');
add_line(MODEL, 'From_ILimDelta_Energy_VSC_SPWM/1',    'Energy_VSC_SPWM/15', 'autorouting', 'on');
add_line(MODEL, 'From_FAHCStrategy_Energy_VSC_SPWM/1', 'Energy_VSC_SPWM/16', 'autorouting', 'on');
add_line(MODEL, 'Energy_VSC_SPWM/1', 'Energy_Extraction_VSC/1', 'autorouting', 'on');

add_controller_inputs(MODEL, 'Regulation_VSC_SPWM', 760,850);
add_line(MODEL, 'From_Clock_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/1', 'autorouting', 'on');
add_line(MODEL, 'From_ScId_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/2', 'autorouting', 'on');
add_line(MODEL, 'From_TFault_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/3', 'autorouting', 'on');
add_line(MODEL, 'From_FaultVariant_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/4', 'autorouting', 'on');
add_line(MODEL, 'From_FaultMag_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/5', 'autorouting', 'on');
add_line(MODEL, 'From_V2abc_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/6', 'autorouting', 'on');
add_line(MODEL, 'From_I2abc_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/7', 'autorouting', 'on');
add_line(MODEL, 'From_Vdc_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/8', 'autorouting', 'on');
add_line(MODEL, 'From_ControllerMode_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/9', 'autorouting', 'on');
add_line(MODEL, 'From_RLEnergyBias_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/10', 'autorouting', 'on');
add_line(MODEL, 'From_RLRegBias_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/11', 'autorouting', 'on');
add_line(MODEL, 'From_RLCurrentBias_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/12', 'autorouting', 'on');
add_line(MODEL, 'From_VDCRefDelta_Regulation_VSC_SPWM/1',  'Regulation_VSC_SPWM/13', 'autorouting', 'on');
add_line(MODEL, 'From_V2RefDelta_Regulation_VSC_SPWM/1',   'Regulation_VSC_SPWM/14', 'autorouting', 'on');
add_line(MODEL, 'From_ILimDelta_Regulation_VSC_SPWM/1',    'Regulation_VSC_SPWM/15', 'autorouting', 'on');
add_line(MODEL, 'From_FAHCStrategy_Regulation_VSC_SPWM/1', 'Regulation_VSC_SPWM/16', 'autorouting', 'on');
add_line(MODEL, 'Regulation_VSC_SPWM/1', 'Regulation_VSC_phase_1/1', 'autorouting', 'on');
add_line(MODEL, 'Regulation_VSC_SPWM/2', 'Regulation_VSC_phase_2/1', 'autorouting', 'on');
add_line(MODEL, 'Regulation_VSC_SPWM/3', 'Regulation_VSC_phase_3/1', 'autorouting', 'on');

add_line(MODEL, 'Meas_Primary/1', 'Power_Calc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Primary/2', 'Power_Calc/2', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/1', 'Power_Calc_Secondary/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/2', 'Power_Calc_Secondary/2', 'autorouting', 'on');
add_line(MODEL, 'Meas_Primary/1', 'V1_abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Primary/2', 'I1_abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/1', 'V2_abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_Secondary/2', 'I2_abc/1', 'autorouting', 'on');
add_line(MODEL, 'Meas_DC_Link_Voltage/1', 'V_dc/1', 'autorouting', 'on');
add_line(MODEL, 'Power_Calc/1', 'P1/1', 'autorouting', 'on');
add_line(MODEL, 'Power_Calc/2', 'Q1/1', 'autorouting', 'on');
add_line(MODEL, 'Power_Calc_Secondary/1', 'P2/1', 'autorouting', 'on');
add_line(MODEL, 'Power_Calc_Secondary/2', 'Q2/1', 'autorouting', 'on');

add_signal_from(MODEL, 'From_Clock_DQ', 'hpt_clk', 1110,760);
add_signal_from(MODEL, 'From_I1abc_DQ', 'hpt_i1abc', 1110,785);
add_signal_from(MODEL, 'From_I2abc_DQ', 'hpt_i2abc', 1110,810);
add_signal_from(MODEL, 'From_Vdc_DQ', 'hpt_vdc', 1110,835);
add_signal_from(MODEL, 'From_ScId_DQ', 'hpt_sc_id', 1110,860);
add_signal_from(MODEL, 'From_TFault_DQ', 'hpt_t_fault', 1110,885);
add_signal_from(MODEL, 'From_FaultMag_DQ', 'hpt_fault_mag', 1110,910);
add_line(MODEL, 'From_Clock_DQ/1', 'DQ_Features/1', 'autorouting', 'on');
add_line(MODEL, 'From_I1abc_DQ/1', 'DQ_Features/2', 'autorouting', 'on');
add_line(MODEL, 'From_I2abc_DQ/1', 'DQ_Features/3', 'autorouting', 'on');
add_line(MODEL, 'From_Vdc_DQ/1', 'DQ_Features/4', 'autorouting', 'on');
add_line(MODEL, 'From_ScId_DQ/1', 'DQ_Features/5', 'autorouting', 'on');
add_line(MODEL, 'From_TFault_DQ/1', 'DQ_Features/6', 'autorouting', 'on');
add_line(MODEL, 'From_FaultMag_DQ/1', 'DQ_Features/7', 'autorouting', 'on');
add_line(MODEL, 'DQ_Features/1', 'Ish_dq/1', 'autorouting', 'on');
add_line(MODEL, 'DQ_Features/2', 'Ise_dq/1', 'autorouting', 'on');
add_line(MODEL, 'DQ_Features/3', 'mode/1', 'autorouting', 'on');

save_system(MODEL);
fprintf('\n=== Switching model "%s.slx" created ===\n', MODEL);
fprintf('Smoke test: load_system(''%s''); sim(''%s'')\n', MODEL, MODEL);

function connect_port(model, src_blk, src_kind, src_idx, dst_blk, dst_kind, dst_idx)
    src = get_param([model '/' src_blk], 'PortHandles');
    dst = get_param([model '/' dst_blk], 'PortHandles');
    add_line(model, src.(src_kind)(src_idx), dst.(dst_kind)(dst_idx), 'autorouting', 'on');
end

function add_signal_goto(model, name, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [model '/' name], ...
        'GotoTag', tag, ...
        'TagVisibility', 'local', ...
        'ShowName', 'off', ...
        'Position', [x y x+55 y+18]);
end

function add_signal_from(model, name, tag, x, y)
    add_block('simulink/Signal Routing/From', [model '/' name], ...
        'GotoTag', tag, ...
        'ShowName', 'off', ...
        'Position', [x y x+55 y+18]);
end

function add_controller_inputs(model, target, x, y)
    tags = {'hpt_clk','hpt_sc_id','hpt_t_fault','hpt_variant','hpt_fault_mag', ...
            'hpt_vdc','hpt_v2abc','hpt_i2abc','hpt_ctrl_mode', ...
            'hpt_rl_energy_bias','hpt_rl_reg_bias','hpt_rl_current_bias', ...
            'hpt_vdc_ref_delta','hpt_v2_ref_delta','hpt_ilim_delta','hpt_fahc_strategy'};
    names = {'Clock','ScId','TFault','FaultVariant','FaultMag', ...
             'Vdc','V2abc','I2abc','ControllerMode', ...
             'RLEnergyBias','RLRegBias','RLCurrentBias', ...
             'VDCRefDelta','V2RefDelta','ILimDelta','FAHCStrategy'};
    for k = 1:numel(tags)
        add_signal_from(model, ['From_' names{k} '_' target], tags{k}, x, y + 25*(k-1));
    end
end
