%% build_hpt_model.m
% Programmatically builds the HPT Simulink model using Simscape Electrical
% (Specialized Power Systems toolbox, available in MATLAB R2022a+)
%
% Run this script once to generate hpt_main_model.slx
% Then use run_scenarios.m for simulations.
%
% HPT Topology:
%   10kV Grid --- [Line Z] --- [Main Transformer T_main] --- [400V Bus]
%                                    |                           |
%                              [T_se series]                 [T_sh shunt]
%                              [VSC_se 3xH-bridge]          [VSC_sh 3-phase]
%                                    |___________________________|
%                                              [C_dc]
%
% Reference: Tang Aihong et al., 基于多控制模式的HPT潮流计算模型

clear; clc;
run('parameters.m');

MODEL_NAME = 'hpt_main_model';

%% Create new model (close existing if open)
if bdIsLoaded(MODEL_NAME)
    close_system(MODEL_NAME, 0);
end
new_system(MODEL_NAME);
open_system(MODEL_NAME);

% Set solver settings
set_param(MODEL_NAME, ...
    'Solver',       'ode23tb', ...   % Stiff solver for power electronics
    'StopTime',     '2.0', ...
    'MaxStep',      num2str(T_sim_step), ...
    'FixedStep',    num2str(T_sim_step));

%% ========== LAYOUT POSITIONS ==========
% Using [x y width height] in pixels
POS_GRID    = [50,  200, 200, 200];
POS_TMAIN   = [350, 200, 200, 300];
POS_LOAD    = [750, 350, 150, 150];
POS_VSC_SH  = [700, 100, 200, 200];
POS_VSC_SE  = [350, 550, 200, 200];
POS_CDC     = [600, 400, 100, 100];
POS_CTRL    = [900, 200, 300, 400];
POS_MEAS    = [600, 200, 150, 150];

%% ========== POWERGUI BLOCK ==========
% Required for Simscape Electrical (Specialized Power Systems)
add_block('powerlib/powergui', [MODEL_NAME, '/powergui'], ...
    'SimulationMode', 'Discrete', ...
    'SampleTime', num2str(T_sim_step), ...
    'Position', [20, 20, 120, 70]);

%% ========== 1. GRID SOURCE (10kV, 3-phase) ==========
add_block('powerlib/Electrical Sources/Three-Phase Source', ...
    [MODEL_NAME, '/Grid_Source'], ...
    'Voltage', num2str(V_grid_ll), ...
    'Frequency', num2str(f_grid), ...
    'Impedance', 'Z1', ...   % Use impedance branch
    'R1', num2str(real(Z_grid)), ...
    'X1', num2str(imag(Z_grid)), ...
    'Position', [50, 200, 150, 280]);

%% ========== 2. MAIN TRANSFORMER (10kV/400V, Delta-Y, 400kVA) ==========
add_block('powerlib/Elements/Three-Phase Transformer (Two Windings)', ...
    [MODEL_NAME, '/T_main'], ...
    'NominalPower', num2str(S_rated), ...
    'Frequency', num2str(f_grid), ...
    'Winding1', [num2str(V_primary), ' 0'], ... % Delta, 10kV
    'Winding2', [num2str(V_secondary), ' 0'], ...% Wye grounded, 400V
    'R1pu', num2str(Tr_resist/2), ...
    'L1pu', num2str(Tr_leakage/2), ...
    'R2pu', num2str(Tr_resist/2), ...
    'L2pu', num2str(Tr_leakage/2), ...
    'Rm',   '500', ...       % Core loss resistance (pu, large = low loss)
    'Lm',   '500', ...       % Magnetizing inductance (pu)
    'Position', POS_TMAIN);

%% ========== 3. VSC_sh — 3-Phase Shunt Converter ==========
% Connected in shunt on secondary side via T_sh coupling transformer
% Maintains V_dc, provides reactive compensation

% Shunt coupling transformer (1:1, low leakage)
add_block('powerlib/Elements/Three-Phase Transformer (Two Windings)', ...
    [MODEL_NAME, '/T_sh'], ...
    'NominalPower', num2str(S_pe), ...
    'Frequency', num2str(f_grid), ...
    'Winding1', [num2str(V_secondary), ' 1'], ... % Wye grounded
    'Winding2', [num2str(V_secondary), ' 1'], ...
    'R1pu', num2str(Tsh_leakage/2), ...
    'L1pu', num2str(Tsh_leakage/2), ...
    'R2pu', num2str(Tsh_leakage/2), ...
    'L2pu', num2str(Tsh_leakage/2), ...
    'Position', [POS_TMAIN(1)+300, POS_TMAIN(2)-100, ...
                 POS_TMAIN(1)+500, POS_TMAIN(2)+100]);

% Filter inductors for VSC_sh (one per phase)
for ph = {'a', 'b', 'c'}
    add_block('powerlib/Elements/Series RLC Branch', ...
        [MODEL_NAME, '/L_sh_', ph{1}], ...
        'BranchType', 'RL', ...
        'R', num2str(R_sh), ...
        'L', num2str(L_sh), ...
        'Position', [750, 100 + (find(strcmp({'a','b','c'}, ph{1}))-1)*80, ...
                     850, 140 + (find(strcmp({'a','b','c'}, ph{1}))-1)*80]);
end

% VSC_sh IGBT bridge (6-pulse, 3-phase)
add_block('powerlib/Power Electronics/Universal Bridge', ...
    [MODEL_NAME, '/VSC_sh'], ...
    'Arms', '3', ...
    'DeviceType', '1', ...   % 1 = IGBT/Diode
    'Ron', '1e-3', ...
    'Snubber_Rs', '1e5', ...
    'Snubber_Cs', '1e-9', ...
    'Position', POS_VSC_SH);

%% ========== 4. VSC_se — 3x Single-Phase H-Bridge Series Converters ==========
% Three independent H-bridges (one per phase), connected in series via T_se
% Injects V_se for voltage regulation and power flow control

for ph_idx = 1:3
    ph_names = {'a', 'b', 'c'};
    ph = ph_names{ph_idx};
    y_offset = (ph_idx-1) * 200;

    % Series isolation transformer (T_se per phase)
    add_block('powerlib/Elements/Linear Transformer', ...
        [MODEL_NAME, '/T_se_', ph], ...
        'NominalPower', num2str(S_pe/3), ...
        'Frequency', num2str(f_grid), ...
        'Winding1', [num2str(V_grid_ph / Tse_ratio), ' 0'], ...
        'Winding2', [num2str(V_dc_ref/2), ' 0'], ...
        'R1', num2str(Tse_leakage/2), ...
        'L1', num2str(Tse_leakage/2), ...
        'R2', num2str(Tse_leakage/2), ...
        'L2', num2str(Tse_leakage/2), ...
        'Position', [300, 550+y_offset, 450, 650+y_offset]);

    % Single-phase H-bridge for VSC_se
    add_block('powerlib/Power Electronics/Full-Bridge (Thyristor)', ...
        [MODEL_NAME, '/VSC_se_', ph], ...
        'Position', [480, 550+y_offset, 600, 650+y_offset]);
    % Note: Use IGBT H-bridge via Universal Bridge (single-phase, 2-arm)
    set_param([MODEL_NAME, '/VSC_se_', ph], ...
        'DeviceType', '1');  % IGBT
end

%% ========== 5. DC LINK CAPACITOR ==========
add_block('powerlib/Elements/Series RLC Branch', ...
    [MODEL_NAME, '/C_dc'], ...
    'BranchType', 'C', ...
    'C', num2str(C_dc), ...
    'InitialVoltage', num2str(V_dc_init), ...
    'Position', POS_CDC);

%% ========== 6. LOAD (configurable) ==========
% Parallel RLC load on secondary bus
add_block('powerlib/Elements/Three-Phase Parallel RLC Load', ...
    [MODEL_NAME, '/Load'], ...
    'NominalVoltage', num2str(V_secondary), ...
    'NominalFrequency', num2str(f_grid), ...
    'ActivPower', num2str(S_rated * 0.8), ...  % 80% rated
    'ReactivPower', num2str(S_rated * 0.6), ... % Inductive
    'Position', POS_LOAD);

%% ========== 7. FAULT INJECTION SWITCHES ==========
% Breaker for AC short circuit (secondary side)
add_block('powerlib/Elements/Three-Phase Fault', ...
    [MODEL_NAME, '/Fault_AC'], ...
    'FaultA', '1', 'FaultB', '1', 'FaultC', '1', 'GroundFault', '0', ...
    'SwitchTimes', '[1.0 1.2]', ...  % Fault at t=1.0s, cleared at t=1.2s
    'TransitionStatus', '[0 1 0]', ... % Off-On-Off
    'Position', [700, 450, 820, 530]);

% DC capacitor disconnect switch (ideal breaker in series with C_dc)
add_block('powerlib/Elements/Breaker', ...
    [MODEL_NAME, '/Cap_Disconnect'], ...
    'SwitchTimes', '[1.0]', ...
    'InitialState', '1', ...  % Initially closed
    'Position', [POS_CDC(1)-60, POS_CDC(2), POS_CDC(1)-10, POS_CDC(4)]);

%% ========== 8. MEASUREMENT BLOCKS ==========
% Three-phase voltage/current measurements at key nodes

% Primary side (10kV)
add_block('powerlib/Measurements/Three-Phase V-I Measurement', ...
    [MODEL_NAME, '/Meas_Primary'], ...
    'VoltagePhasePhase', '1', ...
    'Position', [200, 200, 300, 280]);

% Secondary side (400V)
add_block('powerlib/Measurements/Three-Phase V-I Measurement', ...
    [MODEL_NAME, '/Meas_Secondary'], ...
    'VoltagePhasePhase', '1', ...
    'Position', [600, 200, 700, 280]);

% DC bus voltage
add_block('powerlib/Measurements/Voltage Measurement', ...
    [MODEL_NAME, '/Meas_Vdc'], ...
    'Position', [620, 390, 680, 430]);

% Power measurement (via scope and calculation)
add_block('powerlib/Measurements/Three-Phase Active & Reactive Power', ...
    [MODEL_NAME, '/Power_Primary'], ...
    'Position', [200, 320, 340, 380]);
add_block('powerlib/Measurements/Three-Phase Active & Reactive Power', ...
    [MODEL_NAME, '/Power_Secondary'], ...
    'Position', [600, 320, 740, 380]);

%% ========== 9. DATA LOGGING (To Workspace) ==========
add_block('simulink/Sinks/To Workspace', ...
    [MODEL_NAME, '/Log_Data'], ...
    'VariableName', 'sim_data', ...
    'MaxDataPoints', 'inf', ...
    'SampleTime', num2str(T_sample), ...
    'SaveFormat', 'Timeseries', ...
    'Position', [1100, 300, 1250, 360]);

% Bus creator for all logged signals
add_block('simulink/Signal Routing/Bus Creator', ...
    [MODEL_NAME, '/BusCreator'], ...
    'Inputs', '8', ...   % V1_abc, I1_abc, V2_abc, I2_abc, Vdc, P1, Q1, mode
    'Position', [950, 260, 970, 400]);

%% ========== 10. CONTROLLER REFERENCE (subsystem) ==========
% The controller is built as a separate subsystem (hpt_controller.slx)
% Add a Model block that references the controller
add_block('simulink/Signal Routing/Model', ...
    [MODEL_NAME, '/HPT_Controller'], ...
    'ModelFile', 'hpt_controller', ...
    'Position', POS_CTRL);

%% ========== CONNECT BLOCKS ==========
% Primary connections
add_line(MODEL_NAME, 'Grid_Source/1', 'Meas_Primary/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'Meas_Primary/1', 'T_main/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'T_main/2', 'Meas_Secondary/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'Meas_Secondary/1', 'Load/1', 'autorouting', 'on');

% Shunt converter connections (secondary side)
add_line(MODEL_NAME, 'Meas_Secondary/1', 'T_sh/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'T_sh/2', 'L_sh_a/1', 'autorouting', 'on');
% (b, c phases connected similarly)

% DC bus connections (C_dc between VSC_sh and VSC_se DC sides)
add_line(MODEL_NAME, 'Meas_Vdc/1', 'BusCreator/5', 'autorouting', 'on');

% Power measurement connections
add_line(MODEL_NAME, 'Meas_Primary/1', 'Power_Primary/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'Meas_Primary/2', 'Power_Primary/2', 'autorouting', 'on');
add_line(MODEL_NAME, 'Meas_Secondary/1', 'Power_Secondary/1', 'autorouting', 'on');
add_line(MODEL_NAME, 'Meas_Secondary/2', 'Power_Secondary/2', 'autorouting', 'on');

% Bus creator → Log
add_line(MODEL_NAME, 'BusCreator/1', 'Log_Data/1', 'autorouting', 'on');

%% ========== SAVE MODEL ==========
save_system(MODEL_NAME);
fprintf('\n=== Model "%s.slx" created successfully ===\n', MODEL_NAME);
fprintf('Open with: open_system(''%s'')\n', MODEL_NAME);
fprintf('To simulate: sim(''%s'')\n', MODEL_NAME);
fprintf('\nNEXT STEPS:\n');
fprintf('1. Run hpt_controller.m to build the controller subsystem\n');
fprintf('2. Connect remaining signals manually in Simulink GUI\n');
fprintf('3. Run run_scenarios.m to collect training data\n');
