%% build_hpt_ee.m
% Build HPT Simscape Electrical average circuit model using ee_lib
% Port names confirmed via PortConnectivity inspection.
% Run: matlab -batch "cd simulink; run('build_hpt_ee.m')"

clear; clc;
MODEL = 'hpt_ee';

if bdIsLoaded(MODEL), close_system(MODEL, 0); end
new_system(MODEL);

set_param(MODEL, ...
    'Solver',    'ode23t', ...
    'StopTime',  '2.0', ...
    'MaxStep',   '5e-5', ...
    'RelTol',    '1e-3', ...
    'AbsTol',    '1e-6');

%% ── Layout helpers ───────────────────────────────────────────────────────────
function pos = blkpos(x, y, w, h)
    pos = [x y x+w y+h];
end

%% ── Solver Configuration ─────────────────────────────────────────────────────
add_block('nesl_utility/Solver Configuration', [MODEL '/SC'], ...
    'Position', blkpos(10,10,90,40));

%% ── 10 kV Three-Phase Voltage Source ─────────────────────────────────────────
add_block('ee_lib/Sources/Voltage Source (Three-Phase)', [MODEL '/Grid'], ...
    'vline_rms',       '10000', ...
    'freq',            '50', ...
    'shift',           '0', ...
    'impedance_option','0', ...   % no internal impedance (separate line_Z block)
    'Position', blkpos(50,200,90,80));

%% ── Grounded Neutral for source (neutral → ground) ───────────────────────────
add_block('ee_lib/Connectors & References/Grounded Neutral (Three-Phase)', ...
    [MODEL '/GndN_src'], 'Position', blkpos(50,310,50,30));

%% ── Electrical Reference for Solver Configuration ────────────────────────────
add_block('ee_lib/Connectors & References/Electrical Reference', ...
    [MODEL '/GndSC'], 'Position', blkpos(10,70,40,30));

%% ── Primary Sensor ───────────────────────────────────────────────────────────
add_block('ee_lib/Sensors & Transducers/Current and Voltage Sensor (Three-Phase)', ...
    [MODEL '/Sens1'], ...
    'SRated', '400e3', 'VRated', '10000', ...
    'vMeasurementType', 'ee.enum.vmeasurement.lg', 'outputUnit', 'ee.enum.unit.si', ...
    'Position', blkpos(190,200,90,80));

%% ── Main Transformer (10 kV / 400 V, 400 kVA) ────────────────────────────────
add_block('ee_lib/Passive/Transformers/Two-Winding Transformer (Three-Phase)', ...
    [MODEL '/T_main'], ...
    'SRated', '400e3', 'FRated', '50', ...
    'Winding1Connection', 'ee.enum.windingconnection.delta11', ...
    'VRated1', '10000', ...
    'Winding2Connection', 'ee.enum.windingconnection.Yg', ...
    'VRated2', '400', ...
    'pu_Rw1', '0.005', 'pu_Rw2', '0.005', ...
    'pu_Xl1', '0.04',  'pu_Xl2', '0.04', ...
    'pu_Rm', '200', 'pu_Xm', '50', ...
    'Position', blkpos(340,200,90,120));

%% ── Secondary Sensor ─────────────────────────────────────────────────────────
add_block('ee_lib/Sensors & Transducers/Current and Voltage Sensor (Three-Phase)', ...
    [MODEL '/Sens2'], ...
    'SRated', '400e3', 'VRated', '400', ...
    'vMeasurementType', 'ee.enum.vmeasurement.lg', 'outputUnit', 'ee.enum.unit.si', ...
    'Position', blkpos(490,200,90,80));

%% ── Load (Three-Phase RLC, 320 kW at 400 V, parallel) ────────────────────────
add_block('ee_lib/Passive/RLC Assemblies/RLC (Three-Phase)', [MODEL '/Load'], ...
    'R', '1.5', 'L', 'Inf', 'C', 'Inf', ...
    'component_structure', 'ee.enum.rlc.structure.R', ...
    'Position', blkpos(650,200,90,80));

add_block('ee_lib/Connectors & References/Grounded Neutral (Three-Phase)', ...
    [MODEL '/GndN_load'], 'Position', blkpos(650,310,50,30));

%% ── VSC_sh: Controlled Current Source (Three-Phase) ──────────────────────────
add_block('ee_lib/Sources/Controlled Current Source (Three-Phase)', ...
    [MODEL '/VSC_sh'], ...
    'FRated', '50', ...
    'Position', blkpos(650,80,90,80));

add_block('ee_lib/Connectors & References/Grounded Neutral (Three-Phase)', ...
    [MODEL '/GndN_sh'], 'Position', blkpos(800,80,50,30));

%% ── Fault (Three-Phase) — AC short circuit ───────────────────────────────────
add_block('ee_lib/Utilities/Fault (Three-Phase)', [MODEL '/Fault_AC'], ...
    'fault_type_option',    'ee.enum.fault_type_option.abcg', ...
    'enable_temporal_fault','true', ...
    'fault_start_time',     '1.5', ...   % outside normal window → disabled by default
    'fault_duration',       '0.0', ...   % overridden per scenario
    'R_pn_fault',           '0.01', ...
    'R_ng_fault',           '0.01', ...
    'Position', blkpos(650,370,90,80));

%% ── PS-Simulink Converters for sensor outputs ────────────────────────────────
% Sens1: V1 (RConn2), I1 (RConn3)
add_block('nesl_utility/PS-Simulink Converter', [MODEL '/PSC_V1'], ...
    'Position', blkpos(330,90,60,30));
add_block('nesl_utility/PS-Simulink Converter', [MODEL '/PSC_I1'], ...
    'Position', blkpos(330,130,60,30));
% Sens2: V2 (RConn2), I2 (RConn3)
add_block('nesl_utility/PS-Simulink Converter', [MODEL '/PSC_V2'], ...
    'Position', blkpos(590,90,60,30));
add_block('nesl_utility/PS-Simulink Converter', [MODEL '/PSC_I2'], ...
    'Position', blkpos(590,130,60,30));

%% ── Controller MATLAB Function ───────────────────────────────────────────────
% Computes: Ish_abc (VSC_sh reference) + fault_label + Vdc_approx
add_block('simulink/User-Defined Functions/MATLAB Function', [MODEL '/Controller'], ...
    'Position', blkpos(900,130,120,150));

%% ── Simulink-PS Converter (Ish_abc → CCS) ───────────────────────────────────
add_block('nesl_utility/Simulink-PS Converter', [MODEL '/SPC_Ish'], ...
    'Position', blkpos(800,140,60,30));

%% ── Constant blocks (scenario parameters) ────────────────────────────────────
add_block('simulink/Commonly Used Blocks/Constant', [MODEL '/Sc_id'], ...
    'Value', '0', 'OutDataTypeStr', 'double', 'Position', blkpos(850,100,60,30));
add_block('simulink/Commonly Used Blocks/Constant', [MODEL '/T_fault_in'], ...
    'Value', '1.0', 'OutDataTypeStr', 'double', 'Position', blkpos(850,60,60,30));
add_block('simulink/Sources/Clock', [MODEL '/Clock'], ...
    'Position', blkpos(850,190,50,30));

%% ── Data logging ─────────────────────────────────────────────────────────────
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_V1'], ...
    'VariableName', 'log_V1', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,60,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_I1'], ...
    'VariableName', 'log_I1', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,100,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_V2'], ...
    'VariableName', 'log_V2', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,140,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_I2'], ...
    'VariableName', 'log_I2', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,180,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_Vdc'], ...
    'VariableName', 'log_Vdc', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,220,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_lbl'], ...
    'VariableName', 'log_lbl', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,260,100,30));
add_block('simulink/Sinks/To Workspace', [MODEL '/Log_Ish'], ...
    'VariableName', 'log_Ish', 'SaveFormat', 'Array', 'SampleTime', '5e-5', ...
    'Position', blkpos(1100,300,100,30));

%% ── CONNECT: Main electrical chain ──────────────────────────────────────────
% Grid/LConn1 → Sens1/LConn1 → Sens1/RConn1 → T_main/LConn1 → T_main/RConn1
%   → Sens2/LConn1 → Sens2/RConn1 → (400V bus)
add_line(MODEL, 'Grid/LConn1',    'Sens1/LConn1',  'autorouting','on');
add_line(MODEL, 'Sens1/RConn1',   'T_main/LConn1', 'autorouting','on');
add_line(MODEL, 'T_main/RConn1',  'Sens2/LConn1',  'autorouting','on');

% Neutral connections
add_line(MODEL, 'Grid/RConn1',    'GndN_src/LConn1',  'autorouting','on');

% 400V bus → Load, VSC_sh, Fault_AC (all parallel)
add_line(MODEL, 'Sens2/RConn1',   'Load/LConn1',    'autorouting','on');
add_line(MODEL, 'Sens2/RConn1',   'VSC_sh/LConn1',  'autorouting','on');
add_line(MODEL, 'Sens2/RConn1',   'Fault_AC/LConn1','autorouting','on');

% Neutral/ground connections
add_line(MODEL, 'Load/RConn1',    'GndN_load/LConn1','autorouting','on');
add_line(MODEL, 'VSC_sh/LConn2',  'GndN_sh/LConn1',  'autorouting','on');

%% ── CONNECT: Solver Configuration ───────────────────────────────────────────
% SC connects to an Electrical Reference (single-phase ground) in the network
add_line(MODEL, 'SC/RConn1', 'GndSC/LConn1', 'autorouting','on');

%% ── CONNECT: Sensor PS outputs → PS-Simulink Converters ─────────────────────
add_line(MODEL, 'Sens1/RConn2',  'PSC_V1/LConn1', 'autorouting','on');
add_line(MODEL, 'Sens1/RConn3',  'PSC_I1/LConn1', 'autorouting','on');
add_line(MODEL, 'Sens2/RConn2',  'PSC_V2/LConn1', 'autorouting','on');
add_line(MODEL, 'Sens2/RConn3',  'PSC_I2/LConn1', 'autorouting','on');

%% ── CONNECT: Controller ──────────────────────────────────────────────────────
% Inputs to controller
add_line(MODEL, 'Clock/1',      'Controller/1', 'autorouting','on');
add_line(MODEL, 'Sc_id/1',      'Controller/2', 'autorouting','on');
add_line(MODEL, 'T_fault_in/1', 'Controller/3', 'autorouting','on');
add_line(MODEL, 'PSC_V2/1',     'Controller/4', 'autorouting','on');
add_line(MODEL, 'PSC_I2/1',     'Controller/5', 'autorouting','on');

% Controller outputs
add_line(MODEL, 'Controller/1', 'SPC_Ish/1',  'autorouting','on');  % Ish_abc
add_line(MODEL, 'Controller/2', 'Log_Vdc/1',  'autorouting','on');  % Vdc
add_line(MODEL, 'Controller/3', 'Log_lbl/1',  'autorouting','on');  % fault_label
add_line(MODEL, 'Controller/1', 'Log_Ish/1',  'autorouting','on');  % Ish (same as ctrl out 1)

% SPC → VSC_sh control (PS)
add_line(MODEL, 'SPC_Ish/RConn1', 'VSC_sh/RConn1', 'autorouting','on');

%% ── CONNECT: Sensor Simulink outputs → Log blocks ────────────────────────────
add_line(MODEL, 'PSC_V1/1', 'Log_V1/1', 'autorouting','on');
add_line(MODEL, 'PSC_I1/1', 'Log_I1/1', 'autorouting','on');
add_line(MODEL, 'PSC_V2/1', 'Log_V2/1', 'autorouting','on');
add_line(MODEL, 'PSC_I2/1', 'Log_I2/1', 'autorouting','on');

%% ── Set Controller script ────────────────────────────────────────────────────
ctrl_code = sprintf([...
'function [Ish_abc, Vdc, fault_lbl] = controller(t, sc_id, t_fault, V2, I2)\n' ...
'%% HPT VSC_sh average controller with fault injection\n' ...
'persistent xVdc;\n' ...
'if isempty(xVdc), xVdc = 800; end\n' ...
'\n' ...
'f = 50; w = 2*pi*f;\n' ...
'theta = w * t;\n' ...
'I_nom = 150;  %% A peak shunt current amplitude\n' ...
'Ish_abc = -I_nom * [sin(theta); sin(theta-2*pi/3); sin(theta+2*pi/3)];\n' ...
'fault_lbl = 0;\n' ...
'\n' ...
'%% V_dc first-order model\n' ...
'tau = 0.02;\n' ...
'Vdc_ref = 800;\n' ...
'Vdc_pert = 0;\n' ...
'\n' ...
'in_fault = (t >= t_fault);\n' ...
'in_fw    = in_fault && (t < t_fault + 0.1);\n' ...
't_s      = max(0, t - t_fault);\n' ...
'\n' ...
'switch int32(sc_id)\n' ...
'  case 3  %% IGBT OC VSC_sh\n' ...
'    if in_fault\n' ...
'      fault_lbl = 1;\n' ...
'      Ish_abc(1) = Ish_abc(1) * 0.05;\n' ...
'      Vdc_pert = 25 * (1 - exp(-t_s/0.08));\n' ...
'    end\n' ...
'  case 4  %% IGBT OC VSC_se\n' ...
'    if in_fault\n' ...
'      fault_lbl = 2;\n' ...
'      Ish_abc(2) = Ish_abc(2) * 0.12;\n' ...
'    end\n' ...
'  case 5  %% DC cap fault\n' ...
'    if in_fault\n' ...
'      fault_lbl = 3;\n' ...
'      decay = exp(-t_s/0.08);\n' ...
'      Vdc_pert = -80*decay + 55*sin(2*pi*300*t)*decay;\n' ...
'    end\n' ...
'  case 6  %% SC 1-phase — handled by Fault_AC block\n' ...
'    if in_fw, fault_lbl = 4; end\n' ...
'  case 7  %% SC 3-phase — handled by Fault_AC block\n' ...
'    if in_fw, fault_lbl = 5; end\n' ...
'  case 8  %% Cascade\n' ...
'    if in_fault\n' ...
'      fault_lbl = 6;\n' ...
'      Ish_abc(1) = Ish_abc(1) * 0.05;\n' ...
'      Vdc_pert = min(t_s * 65, 135);\n' ...
'    end\n' ...
'end\n' ...
'\n' ...
'%% Euler step for Vdc\n' ...
'dt = 5e-5;\n' ...
'dVdc = (Vdc_ref - xVdc) / tau;\n' ...
'xVdc = xVdc + dVdc * dt;\n' ...
'Vdc = xVdc + Vdc_pert + randn() * 2.0;\n' ...
'Vdc = max(Vdc, 20);\n' ...
]);

try
    set_param([MODEL '/Controller'], 'MatlabFunctionScript', ctrl_code);
catch e
    fprintf('Warning setting controller script: %s\n', e.message);
end

%% ── Save model ────────────────────────────────────────────────────────────────
slx_path = fullfile(fileparts(mfilename('fullpath')), [MODEL '.slx']);
save_system(MODEL, slx_path);
fprintf('\n=== %s.slx saved ===\n', MODEL);
