%% design_pi_controller.m
% Builds the HPT PI hierarchical controller as a Simulink subsystem.
%
% Controller Architecture (from Song Xing thesis, 混合式电力变压器多工作模式控制策略):
%
%   DEVICE LEVEL:
%     - PLL: grid synchronization → θ_grid, ω_grid
%     - VSC_sh inner loop: dq-decoupled PI → gate signals g_sh[6]
%       outer: V_dc → I_sh_d_ref; Q_sh → I_sh_q_ref
%       inner: (I_sh_dq_ref - I_sh_dq) → V_sh_dq → SPWM
%     - VSC_se inner loop: dq-decoupled PI → gate signals g_se[6 per phase × 3]
%       outer: (V_bus_ref - V_bus) → V_se_d_ref, V_se_q_ref
%       inner: V_se_dq → current control → SPWM
%
%   MULTI-MODE (outer loop, selects based on mode_flag):
%     Mode 1 — Voltage Regulation:   V_bus_error → I_sh_q + V_se
%     Mode 2 — Reactive Compensation: Q_ref → I_sh_q
%     Mode 3 — Power Flow Control:   P_line_ref → V_se phase angle

clear; clc;
run('parameters.m');

MODEL_NAME = 'hpt_controller';
if bdIsLoaded(MODEL_NAME)
    close_system(MODEL_NAME, 0);
end
new_system(MODEL_NAME, 'Library');
open_system(MODEL_NAME);

%% ========== PLL SUBSYSTEM ==========
% Synchronous reference frame PLL (SRF-PLL)
% Input: V_abc_secondary (3-phase voltages)
% Output: theta (grid angle), omega (grid frequency)

pll_path = [MODEL_NAME, '/PLL'];
add_block('simulink/Ports & Subsystems/Subsystem', pll_path, ...
    'Position', [50, 50, 200, 130]);

% Inside PLL subsystem
add_block('powerlib/Control and Measurements/abc_to_dq0', ...
    [pll_path, '/abc_dq0'], ...
    'Position', [50, 50, 150, 100]);
add_block('simulink/Continuous/Integrator', ...
    [pll_path, '/Integrator'], ...
    'InitialCondition', '0', ...
    'Position', [300, 60, 340, 100]);
add_block('simulink/Math Operations/Gain', ...
    [pll_path, '/Kp_pll'], ...
    'Gain', '100', ...   % PLL proportional gain
    'Position', [200, 50, 260, 80]);
add_block('simulink/Continuous/Transfer Fcn', ...
    [pll_path, '/Ki_pll'], ...
    'Numerator', '1000', ...  % PLL integral gain
    'Denominator', '[1 0]', ...
    'Position', [200, 100, 260, 130]);

%% ========== dq CURRENT CONTROLLER (generic — reused for both VSC_sh and VSC_se) ==========
% Inputs:  Id_ref, Iq_ref, Id_meas, Iq_meas, theta, Vd_ff, Vq_ff
% Outputs: Vd_cmd, Vq_cmd (voltage references in dq)
% Implements cross-decoupling + PI (Eq from Song Xing thesis, Chapter 3)

dq_ctrl_path = [MODEL_NAME, '/dq_Current_Controller'];
add_block('simulink/Ports & Subsystems/Subsystem', dq_ctrl_path, ...
    'Position', [250, 50, 450, 180]);

% PI for d-axis current
add_block('simulink/Math Operations/Sum', [dq_ctrl_path, '/Sum_d'], ...
    'Inputs', '+-', 'Position', [80, 60, 100, 80]);
add_block('simulink/Continuous/PID Controller', [dq_ctrl_path, '/PI_d'], ...
    'P', num2str(Kp_ish), ...
    'I', num2str(Ki_ish), ...
    'D', '0', ...
    'Position', [130, 50, 220, 90]);
% Cross-decoupling: Vd_cmd += -ω·L·Iq
add_block('simulink/Math Operations/Sum', [dq_ctrl_path, '/Decoupling_d'], ...
    'Inputs', '+++', 'Position', [260, 60, 280, 80]);

% PI for q-axis current
add_block('simulink/Math Operations/Sum', [dq_ctrl_path, '/Sum_q'], ...
    'Inputs', '+-', 'Position', [80, 120, 100, 140]);
add_block('simulink/Continuous/PID Controller', [dq_ctrl_path, '/PI_q'], ...
    'P', num2str(Kp_ish), ...
    'I', num2str(Ki_ish), ...
    'D', '0', ...
    'Position', [130, 110, 220, 150]);
% Cross-decoupling: Vq_cmd += +ω·L·Id
add_block('simulink/Math Operations/Sum', [dq_ctrl_path, '/Decoupling_q'], ...
    'Inputs', '+++', 'Position', [260, 120, 280, 140]);

% Saturation (prevent voltage command exceeding DC bus capability)
add_block('simulink/Discontinuities/Saturation', [dq_ctrl_path, '/Sat_d'], ...
    'UpperLimit', num2str(V_dc_ref/2 * 0.85), ...
    'LowerLimit', num2str(-V_dc_ref/2 * 0.85), ...
    'Position', [310, 50, 360, 90]);
add_block('simulink/Discontinuities/Saturation', [dq_ctrl_path, '/Sat_q'], ...
    'UpperLimit', num2str(V_dc_ref/2 * 0.85), ...
    'LowerLimit', num2str(-V_dc_ref/2 * 0.85), ...
    'Position', [310, 110, 360, 150]);

%% ========== VSC_sh OUTER LOOPS ==========
% DC voltage outer loop: V_dc_ref - V_dc → Id_sh_ref (d-axis = active power)
vsh_outer = [MODEL_NAME, '/VSC_sh_Outer'];
add_block('simulink/Ports & Subsystems/Subsystem', vsh_outer, ...
    'Position', [50, 250, 250, 370]);

add_block('simulink/Math Operations/Sum', [vsh_outer, '/Sum_Vdc'], ...
    'Inputs', '+-', 'Position', [60, 80, 80, 100]);
add_block('simulink/Continuous/PID Controller', [vsh_outer, '/PI_Vdc'], ...
    'P', num2str(Kp_vdc), ...
    'I', num2str(Ki_vdc), ...
    'D', '0', ...
    'Position', [110, 70, 200, 110]);
add_block('simulink/Discontinuities/Saturation', [vsh_outer, '/Sat_Id'], ...
    'UpperLimit', num2str(I_sh_max), ...
    'LowerLimit', num2str(-I_sh_max), ...
    'Position', [220, 70, 270, 110]);

% Reactive power outer loop: Q_ref - Q_meas → Iq_sh_ref
add_block('simulink/Math Operations/Sum', [vsh_outer, '/Sum_Q'], ...
    'Inputs', '+-', 'Position', [60, 160, 80, 180]);
add_block('simulink/Continuous/PID Controller', [vsh_outer, '/PI_Q'], ...
    'P', num2str(Kp_q), ...
    'I', num2str(Ki_q), ...
    'D', '0', ...
    'Position', [110, 150, 200, 190]);
add_block('simulink/Discontinuities/Saturation', [vsh_outer, '/Sat_Iq'], ...
    'UpperLimit', num2str(I_sh_max), ...
    'LowerLimit', num2str(-I_sh_max), ...
    'Position', [220, 150, 270, 190]);

%% ========== VSC_se OUTER LOOPS ==========
% Series voltage regulation: V_bus_ref - V_bus → V_se_d_ref, V_se_q_ref
% This injects V_se to compensate for voltage deviation at controlled node

vse_outer = [MODEL_NAME, '/VSC_se_Outer'];
add_block('simulink/Ports & Subsystems/Subsystem', vse_outer, ...
    'Position', [50, 420, 250, 550]);

% Voltage error → V_se_d command (amplitude)
add_block('simulink/Math Operations/Sum', [vse_outer, '/Sum_Vbus'], ...
    'Inputs', '+-', 'Position', [60, 80, 80, 100]);
add_block('simulink/Continuous/PID Controller', [vse_outer, '/PI_Vbus'], ...
    'P', num2str(Kp_vac), ...
    'I', num2str(Ki_vac), ...
    'D', '0', ...
    'Position', [110, 70, 200, 110]);
add_block('simulink/Discontinuities/Saturation', [vse_outer, '/Sat_Vse'], ...
    'UpperLimit', num2str(V_se_max), ...
    'LowerLimit', num2str(-V_se_max), ...
    'Position', [220, 70, 270, 110]);

% Power flow control: P_line_ref - P_line → V_se phase angle (θ_se)
add_block('simulink/Math Operations/Sum', [vse_outer, '/Sum_Pflow'], ...
    'Inputs', '+-', 'Position', [60, 160, 80, 180]);
add_block('simulink/Continuous/PID Controller', [vse_outer, '/PI_Pflow'], ...
    'P', num2str(Kp_pf), ...
    'I', num2str(Ki_pf), ...
    'D', '0', ...
    'Position', [110, 150, 200, 190]);
add_block('simulink/Discontinuities/Saturation', [vse_outer, '/Sat_Theta_se'], ...
    'UpperLimit', 'pi', ...
    'LowerLimit', '-pi', ...
    'Position', [220, 150, 270, 190]);

%% ========== MULTI-MODE SELECTOR ==========
% mode_flag: 1=VoltageReg, 2=ReactiveComp, 3=PowerFlow
% Uses Multiport Switch to select reference commands

mode_sel = [MODEL_NAME, '/Mode_Selector'];
add_block('simulink/Ports & Subsystems/Subsystem', mode_sel, ...
    'Position', [300, 300, 500, 450]);

add_block('simulink/Signal Routing/Multiport Switch', [mode_sel, '/Switch_Qref'], ...
    'Inputs', '3', ...
    'Position', [200, 60, 250, 130]);
add_block('simulink/Signal Routing/Multiport Switch', [mode_sel, '/Switch_Vse'], ...
    'Inputs', '3', ...
    'Position', [200, 160, 250, 230]);

% Mode 1 (VoltageReg): Q_sh=0, V_se controls voltage
% Mode 2 (ReactiveComp): Q_sh tracks Q_ref, V_se=0
% Mode 3 (PowerFlow): Q_sh=0, V_se phase controls line power
add_block('simulink/Sources/Constant', [mode_sel, '/Zero'], ...
    'Value', '0', 'Position', [80, 90, 110, 110]);
add_block('simulink/Sources/Constant', [mode_sel, '/Zero2'], ...
    'Value', '0', 'Position', [80, 190, 110, 210]);

%% ========== SPWM GENERATORS ==========
% Converts dq voltage commands → 3-phase gate signals
% Using MATLAB's existing SPWM blocks from powerlib

% VSC_sh SPWM
add_block('powerlib/Control and Measurements/PWM Generator (2-Level)', ...
    [MODEL_NAME, '/SPWM_sh'], ...
    'GeneratorType', '3-phase bridge (6 pulses)', ...
    'Carrier_Frequency', num2str(f_sw_sh), ...
    'SampleTime', num2str(T_sim_step), ...
    'Position', [550, 60, 700, 140]);

% VSC_se SPWM (3 single-phase, one per phase)
for ph = {'a', 'b', 'c'}
    ph_idx = find(strcmp({'a','b','c'}, ph{1}));
    add_block('powerlib/Control and Measurements/PWM Generator (2-Level)', ...
        [MODEL_NAME, '/SPWM_se_', ph{1}], ...
        'GeneratorType', '1-phase bridge (H-bridge)', ...
        'Carrier_Frequency', num2str(f_sw_se), ...
        'SampleTime', num2str(T_sim_step), ...
        'Position', [550, 200+(ph_idx-1)*100, 700, 280+(ph_idx-1)*100]);
end

%% ========== SAVE ==========
save_system(MODEL_NAME);
fprintf('\n=== Controller model "%s.slx" built ===\n', MODEL_NAME);
fprintf('Controller features:\n');
fprintf('  - SRF-PLL (100 rad/s bandwidth)\n');
fprintf('  - VSC_sh: V_dc control + Q compensation (Kp=%.4f, Ki=%.2f)\n', Kp_vdc, Ki_vdc);
fprintf('  - VSC_se: Voltage regulation + Power flow (Kp=%.2f, Ki=%.1f)\n', Kp_vac, Ki_vac);
fprintf('  - Multi-mode: {1:VoltageReg, 2:ReactiveComp, 3:PowerFlow}\n');
fprintf('  - dq decoupled inner loops (bandwidth: ~500 Hz)\n');
fprintf('  - SPWM: %.0f kHz carrier for both converters\n', f_sw_sh/1e3);
