function add_hpt_sac_controller(M, x, y)
% add_hpt_sac_controller adds the topology-neutral HPT SAC command subsystem.
%
% Outputs:
%   port 1: six regulating H-bridge modulation references
%   port 2: three energy-bridge modulation references
%   port 3: 24-D observation vector
%   port 4: 4-D action vector
%           [m_reg_d, m_reg_q, m_energy_d, m_energy_q]

P = @(a, b, w, h) [a b a+w b+h];
S = [M '/HPTSACController'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 240, 165));
set_param(S, 'ShowName', 'on');
open_system(S);

add_block('simulink/Sources/In1', [S '/Vlv'], 'Position', P(35, 35, 30, 18));
add_block('simulink/Sources/In1', [S '/Vdc'], 'Position', P(35, 70, 30, 18));
add_block('simulink/Sources/In1', [S '/Venergy'], 'Position', P(35, 105, 30, 18));
add_block('simulink/Sources/In1', [S '/Ienergy'], 'Position', P(35, 140, 30, 18));
add_block('simulink/Sources/In1', [S '/Vgrid'], 'Position', P(35, 175, 30, 18));

ctrl = [S '/HPT_SAC_HLC'];
add_block('simulink/User-Defined Functions/MATLAB Function', ctrl, ...
    'Position', P(125, 38, 210, 120));
set_hpt_sac_matlab_function_code(ctrl, hpt_sac_hlc_code());

paramNames = {'Ts', 'GridF0', 'VrefPhase', 'GridVrefPhase', 'VdcRef', 'PolicyMode', ...
    'ActorSelectMode', 'ActorFilterTau', 'RegMax', 'EnergyMax', 'IBasePeak', 'InjPhase', 'RegPolarity', ...
    'RegDGain', 'RegQGain', 'DynamicRegLimit', 'EnergyPolarity', ...
    'TopologyId', 'FixedRegD', 'FixedRegQ', 'FixedEnergyD', 'FixedEnergyQ', ...
    'GuardEnable', 'EnergyIdMax', 'EnergyCurrentKp', 'EnergyCurrentKi', ...
    'EnergyVffGain', 'EnergyControlSign', 'ConventionalRegScale', ...
    'ConventionalEnergyScale', 'ConventionalRegScaleSag', ...
    'ConventionalRegScaleSwell', 'ConventionalEnergyScaleSag', ...
    'ConventionalEnergyScaleSwell', 'ConventionalRecoveryRegGain', ...
    'ConventionalRecoveryRegMax', 'ConventionalRecoveryHoldS', ...
    'ConventionalVRegKp', 'ConventionalVRegKi', 'ConventionalVdcKp', ...
    'ConventionalVdcKi', 'GridNormStartupS', 'FaultTimeNormS', ...
    'RecoveryTimeNormS', 'PhaseOverrideEnable', 'PhaseFaultStartS', ...
    'PhaseFaultClearS', 'PhaseRecoveryEndS', 'TrajT', 'TrajAction'};
paramValues = {'hpt_ctrl_Ts', 'hpt_grid_f0', 'hpt_sac_vref_phase', ...
    'hpt_sac_grid_vref_phase', 'hpt_sac_vdc_ref', 'hpt_sac_policy_mode', 'hpt_sac_actor_select_mode', 'hpt_sac_actor_filter_tau', ...
    'hpt_sac_reg_max', 'hpt_sac_energy_max', 'hpt_sac_i_base_peak', 'hpt_inj_phase_offset', ...
    'hpt_sac_reg_polarity', 'hpt_sac_reg_d_gain', 'hpt_sac_reg_q_gain', ...
    'hpt_sac_dynamic_reg_limit', 'hpt_energy_bridge_polarity', 'hpt_sac_topology_id', 'hpt_sac_fixed_reg_d', ...
    'hpt_sac_fixed_reg_q', 'hpt_sac_fixed_energy_d', 'hpt_sac_fixed_energy_q', ...
    'hpt_sac_guard_enable', 'hpt_energy_id_max', 'hpt_energy_i_kp', ...
    'hpt_energy_i_ki', 'hpt_energy_vff_gain', 'hpt_energy_control_sign', ...
    'hpt_conventional_reg_scale', 'hpt_conventional_energy_scale', ...
    'hpt_conventional_reg_scale_sag', 'hpt_conventional_reg_scale_swell', ...
    'hpt_conventional_energy_scale_sag', 'hpt_conventional_energy_scale_swell', ...
    'hpt_conventional_recovery_reg_gain', 'hpt_conventional_recovery_reg_max', ...
    'hpt_conventional_recovery_hold_s', 'hpt_vreg_kp', 'hpt_vreg_ki', ...
    'hpt_vdc_kp', 'hpt_vdc_ki', 'hpt_sac_gridnorm_startup_s', ...
    'hpt_sac_fault_time_norm_s', 'hpt_sac_recovery_time_norm_s', ...
    'hpt_sac_phase_override_enable', 'hpt_sac_phase_fault_start_s', ...
    'hpt_sac_phase_fault_clear_s', 'hpt_sac_phase_recovery_end_s', ...
    'hpt_traj_t', 'hpt_traj_action'};
for pidx = 1:numel(paramNames)
    add_block('simulink/Sources/Constant', [S '/' paramNames{pidx}], ...
        'Position', P(35, 220 + (pidx-1)*30, 70, 20), ...
        'Value', paramValues{pidx});
    add_line(S, [paramNames{pidx} '/1'], sprintf('HPT_SAC_HLC/%d', pidx+5), ...
        'autorouting', 'on');
end

add_block('simulink/Sinks/Out1', [S '/m_reg6'], 'Position', P(390, 45, 30, 18));
add_block('simulink/Sinks/Out1', [S '/m_energy3'], 'Position', P(390, 80, 30, 18));
add_block('simulink/Sinks/Out1', [S '/obs24'], 'Position', P(390, 115, 30, 18));
add_block('simulink/Sinks/Out1', [S '/act4'], 'Position', P(390, 150, 30, 18));

add_line(S, 'Vlv/1', 'HPT_SAC_HLC/1', 'autorouting', 'on');
add_line(S, 'Vdc/1', 'HPT_SAC_HLC/2', 'autorouting', 'on');
add_line(S, 'Venergy/1', 'HPT_SAC_HLC/3', 'autorouting', 'on');
add_line(S, 'Ienergy/1', 'HPT_SAC_HLC/4', 'autorouting', 'on');
add_line(S, 'Vgrid/1', 'HPT_SAC_HLC/5', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/1', 'm_reg6/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/2', 'm_energy3/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/3', 'obs24/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/4', 'act4/1', 'autorouting', 'on');
end

function set_hpt_sac_matlab_function_code(blockPath, codeText)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = codeText;
end

function codeText = hpt_sac_hlc_code()
codeText = strjoin({ ...
    ['function [m_reg6, m_energy3, obs24, act4] = fcn(Vlv, Vdc, Venergy, Ienergy, Vgrid, ', ...
    'ts, grid_f0, vref_phase, grid_vref_phase, vdc_ref, policy_mode, actor_select_mode, actor_filter_tau, reg_max, energy_max, i_base_peak, inj_phase, reg_polarity, reg_d_gain, reg_q_gain, dynamic_reg_limit, energy_polarity, topology_id, fixed_reg_d, fixed_reg_q, fixed_energy_d, fixed_energy_q, guard_enable, energy_id_max, energy_i_kp, energy_i_ki, energy_vff_gain, energy_control_sign, conventional_reg_scale, conventional_energy_scale, conventional_reg_scale_sag, conventional_reg_scale_swell, conventional_energy_scale_sag, conventional_energy_scale_swell, conventional_recovery_reg_gain, conventional_recovery_reg_max, conventional_recovery_hold_s, conventional_vreg_kp, conventional_vreg_ki, conventional_vdc_kp, conventional_vdc_ki, gridnorm_startup_s, fault_time_norm_s, recovery_time_norm_s, phase_override_enable, phase_fault_start_s, phase_fault_clear_s, phase_recovery_end_s, traj_t, traj_action)'], ...
    '%#codegen', ...
    'persistent theta xi_pll xi_eid xi_eiq xi_vreg xi_vq xi_vdc_cmd ba bb bi gba gbb gbi g_vpos_ref_f v_rms_f last_act t_clock fault_active recovery_active fault_start_t dyn_fault_start_t dyn_fault_kind recovery_start_t normal_band_t v_fault_min v_fault_max last_vpos last_vdc normal_seen', ...
    'if isempty(theta)', ...
    '    theta = 0;', ...
    '    xi_pll = 0;', ...
    '    xi_eid = 0;', ...
    '    xi_eiq = 0;', ...
    '    xi_vreg = 0;', ...
    '    xi_vq = 0;', ...
    '    xi_vdc_cmd = 0;', ...
    '    ba = zeros(512,1);', ...
    '    bb = zeros(512,1);', ...
    '    bi = int32(1);', ...
    '    gba = zeros(512,1);', ...
    '    gbb = zeros(512,1);', ...
    '    gbi = int32(1);', ...
    '    g_vpos_ref_f = 0;', ...
    '    v_rms_f = 0;', ...
    '    last_act = zeros(4,1);', ...
    '    t_clock = 0;', ...
    '    fault_active = 0;', ...
    '    recovery_active = 0;', ...
    '    fault_start_t = 0;', ...
    '    dyn_fault_start_t = 0;', ...
    '    dyn_fault_kind = 0;', ...
    '    recovery_start_t = 0;', ...
    '    normal_band_t = 0;', ...
    '    v_fault_min = 1;', ...
    '    v_fault_max = 1;', ...
    '    last_vpos = 1;', ...
    '    last_vdc = 1;', ...
    '    normal_seen = 0;', ...
    'end', ...
    'm_reg6 = zeros(6,1);', ...
    'm_energy3 = zeros(3,1);', ...
    'obs24 = zeros(24,1);', ...
    'act4 = zeros(4,1);', ...
    't_clock = t_clock + ts;', ...
    'va = Vlv(1); vb = Vlv(2); vc = Vlv(3);', ...
    'alpha = (2/3) * (va - 0.5*vb - 0.5*vc);', ...
    'beta = (sqrt(3)/3) * (vb - vc);', ...
    'theta_meas = atan2(beta, alpha);', ...
    'pll_err = atan2(sin(theta_meas - theta), cos(theta_meas - theta));', ...
    'xi_pll = xi_pll + 1200 * pll_err * ts;', ...
    'if xi_pll > 120; xi_pll = 120; elseif xi_pll < -120; xi_pll = -120; end', ...
    'omega = 2*pi*grid_f0 + 70 * pll_err + xi_pll;', ...
    'theta = theta + omega * ts;', ...
    'theta = theta - 2*pi*floor(theta/(2*pi));', ...
    'nb = int32(round(0.25 / max(grid_f0*ts, 1e-9)));', ...
    'if nb < 1; nb = int32(1); elseif nb > 512; nb = int32(512); end', ...
    'iad = ba(bi); ibd = bb(bi);', ...
    'ba(bi) = alpha; bb(bi) = beta;', ...
    'bi = bi + 1; if bi > nb; bi = int32(1); end', ...
    'vbase_peak = sqrt(2) * max(vref_phase, 1);', ...
    'v1a = 0.5*(alpha - ibd); v1b = 0.5*(beta + iad);', ...
    'v2a = 0.5*(alpha + ibd); v2b = 0.5*(beta - iad);', ...
    'vpos = sqrt(v1a*v1a + v1b*v1b) / vbase_peak;', ...
    'vneg = sqrt(v2a*v2a + v2b*v2b) / vbase_peak;', ...
    'gva = Vgrid(1); gvb = Vgrid(2); gvc = Vgrid(3);', ...
    'galpha = (2/3) * (gva - 0.5*gvb - 0.5*gvc);', ...
    'gbeta = (sqrt(3)/3) * (gvb - gvc);', ...
    'gvbase_peak = sqrt(2) * max(grid_vref_phase, 1);', ...
    'giad = gba(gbi); gibd = gbb(gbi);', ...
    'gba(gbi) = galpha; gbb(gbi) = gbeta;', ...
    'gbi = gbi + 1; if gbi > nb; gbi = int32(1); end', ...
    'gv1a = 0.5*(galpha - gibd); gv1b = 0.5*(gbeta + giad);', ...
    'gv2a = 0.5*(galpha + gibd); gv2b = 0.5*(gbeta - giad);', ...
    'g_vpos_raw = sqrt(gv1a*gv1a + gv1b*gv1b) / gvbase_peak;', ...
    'g_vneg_raw = sqrt(gv2a*gv2a + gv2b*gv2b) / gvbase_peak;', ...
    'if g_vpos_ref_f == 0; g_vpos_ref_f = max(g_vpos_raw, 0.1); end', ...
    'if t_clock < gridnorm_startup_s', ...
    '    alpha_gref = min(max(ts / 0.010, 0), 1);', ...
    '    g_vpos_ref_f = g_vpos_ref_f + alpha_gref * (g_vpos_raw - g_vpos_ref_f);', ...
    'end', ...
    'g_vpos = g_vpos_raw / max(g_vpos_ref_f, 0.1);', ...
    'g_vneg = g_vneg_raw / max(g_vpos_ref_f, 0.1);', ...
    'v_rms = sqrt(max((va*va + vb*vb + vc*vc) / 3, 0));', ...
    'if v_rms_f == 0; v_rms_f = v_rms; end', ...
    'alpha_v = min(max(ts / 0.005, 0), 1);', ...
    'v_rms_f = v_rms_f + alpha_v * (v_rms - v_rms_f);', ...
    'vpu = v_rms_f / max(vref_phase, 1);', ...
    'vdcpu = Vdc / max(vdc_ref, 1);', ...
    'ea = Ienergy(1); eb = Ienergy(2); ec = Ienergy(3);', ...
    'ialpha = (2/3) * (ea - 0.5*eb - 0.5*ec);', ...
    'ibeta = (sqrt(3)/3) * (eb - ec);', ...
    'ct = cos(theta); st = sin(theta);', ...
    'vd_lv = alpha*ct + beta*st;', ...
    'vq_lv = -alpha*st + beta*ct;', ...
    'id_e = (ialpha*ct + ibeta*st) / max(i_base_peak, 1);', ...
    'iq_e = (-ialpha*st + ibeta*ct) / max(i_base_peak, 1);', ...
    'reg_mag_prev = sqrt(last_act(1)*last_act(1) + last_act(2)*last_act(2));', ...
    'energy_mag_prev = sqrt(last_act(3)*last_act(3) + last_act(4)*last_act(4));', ...
    'fault_entry = double((g_vpos < 0.92) || (g_vpos > 1.10) || (g_vneg > 0.06));', ...
    'normal_band = double((g_vpos >= 0.90) && (g_vpos <= 1.10) && (g_vneg <= 0.06));', ...
    'recovery_reentry_fault = double((g_vpos < 0.86) || (g_vpos > 1.22) || (g_vneg > 0.12));', ...
    'if t_clock < gridnorm_startup_s', ...
    '    fault_entry = 0;', ...
    '    normal_band = 1;', ...
    '    recovery_reentry_fault = 0;', ...
    '    fault_active = 0;', ...
    '    recovery_active = 0;', ...
    '    dyn_fault_start_t = 0;', ...
    '    recovery_start_t = 0;', ...
    '    normal_band_t = 0;', ...
    'end', ...
    'if normal_band >= 0.5 && t_clock > 0.015', ...
    '    normal_seen = 1;', ...
    'end', ...
    'clear_drop_candidate = double((v_fault_max > 1.08) && ((t_clock - fault_start_t) >= 0.065) && (g_vpos <= 1.09) && ((v_fault_max - g_vpos) >= 0.070) && (g_vneg <= 0.08));', ...
    'clear_candidate = double((normal_band >= 0.5) || (clear_drop_candidate >= 0.5));', ...
    'if clear_candidate < 0.5', ...
    '    normal_band_t = 0;', ...
    'end', ...
    'if fault_active >= 0.5 && clear_candidate >= 0.5', ...
    '    if normal_band_t == 0; normal_band_t = t_clock; end', ...
    '    if (t_clock - fault_start_t) >= 0.02 && (((normal_band >= 0.5) && ((t_clock - normal_band_t) >= 0.010)) || (clear_drop_candidate >= 0.5))', ...
    '        fault_active = 0;', ...
    '        recovery_active = 1;', ...
    '        recovery_start_t = t_clock;', ...
    '        normal_band_t = 0;', ...
    '    end', ...
    'elseif recovery_active >= 0.5', ...
    '    fault_active = 0;', ...
    '    if normal_band >= 0.5 && (t_clock - recovery_start_t) >= 0.08', ...
    '        recovery_active = 0;', ...
    '        normal_band_t = 0;', ...
    '        v_fault_min = 1;', ...
    '        v_fault_max = 1;', ...
    '    elseif recovery_reentry_fault >= 0.5 && (t_clock - recovery_start_t) >= 0.08', ...
    '        fault_active = 1;', ...
    '        recovery_active = 0;', ...
    '        fault_start_t = t_clock;', ...
    '        normal_band_t = 0;', ...
    '        if dyn_fault_start_t == 0 && t_clock > 0.02; dyn_fault_start_t = t_clock; if vpos > 1; dyn_fault_kind = 1; else; dyn_fault_kind = -1; end; end', ...
    '        if dyn_fault_start_t > 0; fault_start_t = dyn_fault_start_t; end', ...
    '        v_fault_min = g_vpos;', ...
    '        v_fault_max = g_vpos;', ...
    '    end', ...
    'elseif fault_entry >= 0.5', ...
    '    if fault_active < 0.5', ...
    '        fault_start_t = t_clock;', ...
    '        normal_band_t = 0;', ...
    '        if dyn_fault_start_t == 0 && t_clock > 0.02; dyn_fault_start_t = t_clock; if vpos > 1; dyn_fault_kind = 1; else; dyn_fault_kind = -1; end; end', ...
    '        if dyn_fault_start_t > 0; fault_start_t = dyn_fault_start_t; end', ...
    '        v_fault_min = g_vpos;', ...
    '        v_fault_max = g_vpos;', ...
    '    end', ...
    '    fault_active = 1;', ...
    '    recovery_active = 0;', ...
    '    v_fault_min = min(v_fault_min, g_vpos);', ...
    '    v_fault_max = max(v_fault_max, g_vpos);', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.02 && v_fault_min < 0.94; dyn_fault_kind = -1; end', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.02 && v_fault_min > 0.97 && g_vpos > 1.02; dyn_fault_kind = 1; end', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.03 && v_fault_min > 0.97 && vdcpu > 1.12; dyn_fault_kind = 1; end', ...
    'end', ...
    'tfault = 0; if fault_active >= 0.5; tfault = min(max((t_clock - fault_start_t)/max(fault_time_norm_s, ts), 0), 1); end', ...
    'trec = 0; if recovery_active >= 0.5; trec = min(max((t_clock - recovery_start_t)/max(recovery_time_norm_s, ts), 0), 1); end', ...
    'dynamic_fault = double(dyn_fault_start_t > 0.02);', ...
    'dvpos = (g_vpos - last_vpos) / max(ts, 1e-9) / 50;', ...
    'dvdc = (vdcpu - last_vdc) / max(ts, 1e-9) / 50;', ...
    'last_vpos = g_vpos;', ...
    'last_vdc = vdcpu;', ...
    'obs_sag = double(g_vpos < 0.92);', ...
    'obs_swell = double(g_vpos > 1.08);', ...
    'obs_fault_active = fault_active;', ...
    'obs_recovery_active = recovery_active;', ...
    'obs_tfault = tfault;', ...
    'obs_trec = trec;', ...
    'if phase_override_enable >= 0.5', ...
    '    scheduled_fault = double((t_clock >= phase_fault_start_s) && (t_clock < phase_fault_clear_s));', ...
    '    scheduled_recovery = double((t_clock >= phase_fault_clear_s) && (t_clock < phase_recovery_end_s));', ...
    '    obs_sag = double(scheduled_fault >= 0.5 && g_vpos <= 1.0);', ...
    '    obs_swell = double(scheduled_fault >= 0.5 && g_vpos > 1.0);', ...
    '    obs_fault_active = scheduled_fault;', ...
    '    obs_recovery_active = scheduled_recovery;', ...
    '    obs_tfault = 0; if scheduled_fault >= 0.5; obs_tfault = min(max((t_clock - phase_fault_start_s)/max(fault_time_norm_s, ts), 0), 1); end', ...
    '    obs_trec = 0; if scheduled_recovery >= 0.5; obs_trec = min(max((t_clock - phase_fault_clear_s)/max(recovery_time_norm_s, ts), 0), 1); end', ...
    'end', ...
    'obs24 = [vpu; g_vpos; g_vneg; vdcpu; 1-vdcpu; 1-vpu; id_e; iq_e; last_act; obs_sag; obs_swell; double(topology_id < 1.5); double(topology_id >= 1.5); obs_fault_active; obs_recovery_active; obs_tfault; obs_trec; v_fault_min; v_fault_max; dvpos; dvdc];', ...
    'for k=1:24; if obs24(k)>5; obs24(k)=5; elseif obs24(k)<-5; obs24(k)=-5; end; end', ...
    'if policy_mode <= -1.5', ...
    '    nt = int32(numel(traj_t));', ...
    '    idx = int32(1);', ...
    '    for kk = 1:nt', ...
    '        if t_clock >= traj_t(kk); idx = int32(kk); end', ...
    '    end', ...
    '    act4 = [traj_action(idx,1); traj_action(idx,2); traj_action(idx,3); traj_action(idx,4)];', ...
    'elseif policy_mode <= -0.5', ...
    '    act4 = [fixed_reg_d; fixed_reg_q; fixed_energy_d; fixed_energy_q];', ...
    'elseif policy_mode >= 0.5', ...
    '    use_dynamic_actor = false;', ...
    '    if actor_select_mode >= 3.5', ...
    '        deep_lvrt_actor = double((topology_id < 1.5) && ((g_vpos <= 0.885) || (v_fault_min <= 0.885)) && ((fault_active >= 0.5) || (recovery_active >= 0.5)));', ...
    '        use_dynamic_actor = deep_lvrt_actor >= 0.5;', ...
    '    elseif actor_select_mode >= 2.5', ...
    '        use_dynamic_actor = true;', ...
    '    elseif actor_select_mode >= 1.5', ...
    '        if dynamic_reg_limit < 0.90 * reg_max', ...
    '            use_dynamic_actor = dynamic_fault >= 0.5;', ...
    '        else', ...
    '            use_dynamic_actor = true;', ...
    '        end', ...
    '    elseif actor_select_mode >= 0.5', ...
    '        use_dynamic_actor = normal_seen >= 0.5 && t_clock > 0.02;', ...
    '    end', ...
    '    if use_dynamic_actor', ...
    '        W = coder.load(''hpt_sac_actor_weights_dynamic.mat'');', ...
    '    else', ...
    '        W = coder.load(''hpt_sac_actor_weights.mat'');', ...
    '    end', ...
    '    H = 256; OBS_DIM = 24; N_ACT = 4;', ...
    '    W0 = reshape(W.latent_pi_0_weight, H, OBS_DIM); b0 = reshape(W.latent_pi_0_bias, H, 1);', ...
    '    W2 = reshape(W.latent_pi_2_weight, H, H); b2 = reshape(W.latent_pi_2_bias, H, 1);', ...
    '    W4 = reshape(W.latent_pi_4_weight, H, H); b4 = reshape(W.latent_pi_4_bias, H, 1);', ...
    '    Wm = reshape(W.mu_weight, N_ACT, H); bm = reshape(W.mu_bias, N_ACT, 1);', ...
    '    alo = reshape(W.act_low, N_ACT, 1); ahi = reshape(W.act_high, N_ACT, 1);', ...
    '    h = max(0, W0*obs24 + b0);', ...
    '    h = max(0, W2*h + b2);', ...
    '    h = max(0, W4*h + b4);', ...
    '    mu = Wm*h + bm;', ...
    '    act4 = alo + 0.5*(tanh(mu)+1).*(ahi-alo);', ...
    'else', ...
    '    act4 = zeros(4,1);', ...
    '    v_err_pu = 1 - vpu;', ...
    '    q_err_pu = -vq_lv / max(vbase_peak, 1);', ...
    '    dc_err_pu = 1 - vdcpu;', ...
    '    conv_active = double((fault_active >= 0.5) || (recovery_active >= 0.5) || abs(v_err_pu) > 0.010 || abs(dc_err_pu) > 0.010 || g_vneg > 0.025);', ...
    '    reg_kp = conventional_vreg_kp;', ...
    '    reg_ki = conventional_vreg_ki;', ...
    '    reg_lim = reg_max;', ...
    '    if recovery_active >= 0.5', ...
    '        reg_kp = min(reg_kp, max(0.1, conventional_recovery_reg_gain));', ...
    '        reg_ki = 0.45 * reg_ki;', ...
    '        reg_lim = min(reg_lim, max(0.05, conventional_recovery_reg_max));', ...
    '    elseif fault_active >= 0.5 && g_vpos < 0.97', ...
    '        reg_kp = 1.12 * reg_kp;', ...
    '    elseif fault_active >= 0.5 && g_vpos > 1.03', ...
    '        reg_kp = 0.85 * reg_kp;', ...
    '        reg_lim = min(reg_lim, max(0.05, 0.80*reg_max));', ...
    '    end', ...
    '    dc_reg_scale = 1;', ...
    '    if vdcpu < 0.94', ...
    '        dc_reg_scale = min(max((vdcpu - 0.78)/0.16, 0), 1);', ...
    '        if v_err_pu > 0; reg_lim = min(reg_lim, reg_max * dc_reg_scale); end', ...
    '    elseif vdcpu > 1.14', ...
    '        dc_reg_scale = min(max((1.24 - vdcpu)/0.10, 0), 1);', ...
    '        if v_err_pu < 0; reg_lim = min(reg_lim, reg_max * dc_reg_scale); end', ...
    '    end', ...
    '    if conv_active >= 0.5 && t_clock > gridnorm_startup_s', ...
    '        xi_vreg = xi_vreg + reg_ki * v_err_pu * ts;', ...
    '        xi_vq = xi_vq + 0.35 * reg_ki * q_err_pu * ts;', ...
    '        xi_vdc_cmd = xi_vdc_cmd + conventional_vdc_ki * dc_err_pu * ts;', ...
    '    else', ...
    '        xi_vreg = 0.98 * xi_vreg;', ...
    '        xi_vq = 0.98 * xi_vq;', ...
    '        xi_vdc_cmd = 0.98 * xi_vdc_cmd;', ...
    '    end', ...
    '    reg_unsat = reg_kp * v_err_pu + xi_vreg;', ...
    '    reg_cmd = min(max(reg_unsat, -reg_lim), reg_lim);', ...
    '    if reg_cmd ~= reg_unsat; xi_vreg = reg_cmd - reg_kp * v_err_pu; end', ...
    '    q_gain_eff = 0.28;', ...
    '    q_i_damp = 0.06;', ...
    '    q_lim = min(0.45*reg_max, reg_lim);', ...
    '    if g_vneg <= 0.020', ...
    '        q_gain_eff = 0.10;', ...
    '        q_i_damp = 0.03;', ...
    '        q_lim = min(q_lim, 0.20*reg_max);', ...
    '    end', ...
    '    q_unsat = q_gain_eff * reg_kp * q_err_pu + xi_vq - q_i_damp * iq_e;', ...
    '    if g_vneg > 0.025; q_unsat = q_unsat - 0.10 * sign(q_err_pu + 1e-9) * g_vneg; end', ...
    '    q_cmd = min(max(q_unsat, -q_lim), q_lim);', ...
    '    if q_cmd ~= q_unsat; xi_vq = q_cmd - q_gain_eff * reg_kp * q_err_pu; end', ...
    '    if g_vneg <= 0.010 && abs(q_err_pu) < 0.0025 && abs(iq_e) < 0.01; q_cmd = 0; xi_vq = 0.98 * xi_vq; end', ...
    '    if conv_active >= 0.5', ...
    '        act4(1) = reg_cmd;', ...
    '        act4(2) = q_cmd;', ...
    '    end', ...
    '    dc_lim = energy_max;', ...
    '    dc_unsat = conventional_vdc_kp * dc_err_pu + xi_vdc_cmd;', ...
    '    if vdcpu < 0.90; dc_unsat = max(dc_unsat, min(dc_lim, 0.10 + 1.6*(0.90-vdcpu))); end', ...
    '    if vdcpu > 1.10; dc_unsat = min(dc_unsat, -min(dc_lim, 0.06 + 1.3*(vdcpu-1.10))); end', ...
    '    dc_cmd = min(max(dc_unsat, -dc_lim), dc_lim);', ...
    '    if dc_cmd ~= dc_unsat; xi_vdc_cmd = dc_cmd - conventional_vdc_kp * dc_err_pu; end', ...
    '    if abs(dc_err_pu) < 0.006 && fault_active < 0.5; dc_cmd = 0; xi_vdc_cmd = 0.98 * xi_vdc_cmd; end', ...
    '    act4(3) = dc_cmd;', ...
    '    eq_cmd = min(max(-0.35 * iq_e - 0.08 * q_err_pu, -0.45*energy_max), 0.45*energy_max);', ...
    '    if abs(iq_e) < 0.006 && abs(q_err_pu) < 0.0025; eq_cmd = 0; end', ...
    '    act4(4) = eq_cmd;', ...
    'end', ...
    'if policy_mode > -0.5 && policy_mode < 0.5', ...
    '    conv_reg_scale = conventional_reg_scale;', ...
    '    conv_energy_scale = conventional_energy_scale;', ...
    '    if fault_active >= 0.5 && g_vpos < 0.97', ...
    '        conv_reg_scale = conv_reg_scale * conventional_reg_scale_sag;', ...
    '        conv_energy_scale = conv_energy_scale * conventional_energy_scale_sag;', ...
    '    elseif fault_active >= 0.5 && g_vpos > 1.03', ...
    '        conv_reg_scale = conv_reg_scale * conventional_reg_scale_swell;', ...
    '        conv_energy_scale = conv_energy_scale * conventional_energy_scale_swell;', ...
    '    end', ...
    '    act4(1) = conv_reg_scale * act4(1);', ...
    '    act4(2) = conv_reg_scale * act4(2);', ...
    '    act4(3) = conv_energy_scale * act4(3);', ...
    '    act4(4) = conv_energy_scale * act4(4);', ...
    '    reg_norm4 = sqrt(act4(1)*act4(1) + act4(2)*act4(2));', ...
    '    if reg_norm4 > reg_max && reg_norm4 > 0', ...
    '        act4(1) = act4(1) * reg_max / reg_norm4;', ...
    '        act4(2) = act4(2) * reg_max / reg_norm4;', ...
    '    end', ...
    '    energy_norm4 = sqrt(act4(3)*act4(3) + act4(4)*act4(4));', ...
    '    if energy_norm4 > energy_max && energy_norm4 > 0', ...
    '        act4(3) = act4(3) * energy_max / energy_norm4;', ...
    '        act4(4) = act4(4) * energy_max / energy_norm4;', ...
    '    end', ...
    '    alpha_conv_act = min(max(ts / 0.0015, 0), 1);', ...
    '    act4 = last_act + alpha_conv_act * (act4 - last_act);', ...
    'end', ...
    'if guard_enable >= 0.5', ...
        '    if g_vpos < 0.92 && act4(1) < 0; act4(1) = 0; end', ...
        '    if g_vpos > 1.08 && act4(1) > 0; act4(1) = 0; end', ...
    '    if vpu < 0.98 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vdcpu < 0.95', ...
    '        dc_scale = min(max((vdcpu - 0.75)/0.20, 0), 1);', ...
    '        act4(1) = dc_scale * act4(1);', ...
    '        act4(3) = max(act4(3), min(energy_max, 0.20 + 1.2*(0.82-vdcpu)));', ...
    '    elseif vdcpu > 1.12', ...
    '        act4(3) = min(act4(3), -0.05);', ...
    '    end', ...
    'end', ...
    'if guard_enable >= 0.5 && policy_mode >= 0.5 && topology_id < 1.5 && actor_select_mode < 1.5', ...
    '    top1_reg = 0.32 + 2.35*(1 - vpu);', ...
    '    if vpu > 0.995; top1_reg = 0.26; end', ...
    '    if top1_reg < 0.22; top1_reg = 0.22; elseif top1_reg > 0.46; top1_reg = 0.46; end', ...
    '    act4(1) = top1_reg;', ...
    '    act4(2) = 0;', ...
    '    act4(3) = 0;', ...
    '    act4(4) = 0;', ...
    'end', ...
    'if guard_enable >= 0.5 && policy_mode >= 0.5 && actor_select_mode >= 1.5 && topology_id >= 1.5', ...
    '    dyn_lim0 = min(max(dynamic_reg_limit, 0), reg_max);', ...
    '    dyn_cmd0 = 20.0 * (1 - vpu);', ...
    '    if dyn_cmd0 > dyn_lim0; dyn_cmd0 = dyn_lim0; elseif dyn_cmd0 < -dyn_lim0; dyn_cmd0 = -dyn_lim0; end', ...
    '    act4(1) = dyn_cmd0;', ...
    '    act4(2) = 0;', ...
    '    act4(3) = 0;', ...
    '    act4(4) = 0;', ...
    'end', ...
    'if guard_enable >= 0.5 && actor_select_mode >= 1.5 && (dynamic_fault >= 0.5 && (fault_active >= 0.5 || recovery_active >= 0.5))', ...
    '    dyn_lim = min(max(dynamic_reg_limit, 0), reg_max);', ...
    '    if act4(1) > dyn_lim; act4(1) = dyn_lim; elseif act4(1) < -dyn_lim; act4(1) = -dyn_lim; end', ...
    '    if act4(2) > dyn_lim; act4(2) = dyn_lim; elseif act4(2) < -dyn_lim; act4(2) = -dyn_lim; end', ...
    '    if topology_id >= 1.5', ...
    '        dyn_cmd = 20.0 * (1 - vpu);', ...
    '        if dyn_cmd > dyn_lim; dyn_cmd = dyn_lim; elseif dyn_cmd < -dyn_lim; dyn_cmd = -dyn_lim; end', ...
    '        act4(1) = dyn_cmd;', ...
    '        act4(2) = 0;', ...
    '        act4(3) = 0;', ...
    '        act4(4) = 0;', ...
    '    end', ...
    '    if g_vpos < 0.92 && act4(1) < 0; act4(1) = 0; end', ...
    '    if g_vpos > 1.08 && act4(1) > 0; act4(1) = 0; end', ...
    '    if vpu < 0.98 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vdcpu < 0.95', ...
    '        dc_scale = min(max((vdcpu - 0.75)/0.20, 0), 1);', ...
    '        act4(1) = dc_scale * act4(1);', ...
    '    end', ...
    'end', ...
    'act4(1) = min(max(act4(1), -reg_max), reg_max);', ...
    'act4(2) = min(max(act4(2), -reg_max), reg_max);', ...
    'act4(3) = min(max(act4(3), -energy_max), energy_max);', ...
    'act4(4) = min(max(act4(4), -energy_max), energy_max);', ...
    'if policy_mode >= 0.5 && actor_select_mode >= 1.5', ...
    '    if actor_filter_tau <= 0', ...
    '        alpha_act = 1;', ...
    '    else', ...
    '        alpha_act = min(max(ts / actor_filter_tau, 0), 1);', ...
    '    end', ...
    '    act4 = last_act + alpha_act * (act4 - last_act);', ...
    'end', ...
    'md = reg_polarity * reg_d_gain * act4(1); mq = reg_polarity * reg_q_gain * act4(2);', ...
    'phase_cmd = inj_phase;', ...
    'if guard_enable >= 0.5 && topology_id >= 1.5 && actor_select_mode >= 1.5 && act4(1) < 0', ...
    '    phase_cmd = inj_phase + 0.55;', ...
    'end', ...
    'pa = theta + phase_cmd;', ...
    'pb = theta + phase_cmd - 2*pi/3;', ...
    'pc = theta + phase_cmd + 2*pi/3;', ...
    'ma = md*sin(pa) + mq*cos(pa);', ...
    'mb = md*sin(pb) + mq*cos(pb);', ...
    'mc = md*sin(pc) + mq*cos(pc);', ...
    'm_reg6 = [ma; -ma; mb; -mb; mc; -mc];', ...
    'eva = Venergy(1); evb = Venergy(2); evc = Venergy(3);', ...
    'eia = Ienergy(1); eib = Ienergy(2); eic = Ienergy(3);', ...
    'evalpha = (2/3) * (eva - 0.5*evb - 0.5*evc);', ...
    'evbeta = (sqrt(3)/3) * (evb - evc);', ...
    'eialpha = (2/3) * (eia - 0.5*eib - 0.5*eic);', ...
    'eibeta = (sqrt(3)/3) * (eib - eic);', ...
    'evd = evalpha*ct + evbeta*st;', ...
    'evq = -evalpha*st + evbeta*ct;', ...
    'eid = eialpha*ct + eibeta*st;', ...
    'eiq = -eialpha*st + eibeta*ct;', ...
    'eid_ref = energy_id_max * act4(3);', ...
    'eiq_ref = energy_id_max * act4(4);', ...
    'eeid = eid_ref - eid;', ...
    'eeiq = eiq_ref - eiq;', ...
    'xi_eid = xi_eid + energy_i_ki * eeid * ts;', ...
    'xi_eiq = xi_eiq + energy_i_ki * eeiq * ts;', ...
    'ed_ctrl = energy_i_kp * eeid + xi_eid;', ...
    'eq_ctrl = energy_i_kp * eeiq + xi_eiq;', ...
    'evconv_d = energy_vff_gain * evd - energy_control_sign * ed_ctrl;', ...
    'evconv_q = energy_vff_gain * evq - energy_control_sign * eq_ctrl;', ...
    'econv_alpha = evconv_d*ct - evconv_q*st;', ...
    'econv_beta = evconv_d*st + evconv_q*ct;', ...
    'ema_unsat = 2 * econv_alpha / max(abs(Vdc), 50);', ...
    'emb_unsat = 2 * (-0.5*econv_alpha + (sqrt(3)/2)*econv_beta) / max(abs(Vdc), 50);', ...
    'emc_unsat = 2 * (-0.5*econv_alpha - (sqrt(3)/2)*econv_beta) / max(abs(Vdc), 50);', ...
    'ema = min(max(ema_unsat, -energy_max), energy_max);', ...
    'emb = min(max(emb_unsat, -energy_max), energy_max);', ...
    'emc = min(max(emc_unsat, -energy_max), energy_max);', ...
    'if abs(ema) >= energy_max || abs(emb) >= energy_max || abs(emc) >= energy_max', ...
    '    xi_eid = xi_eid - energy_i_ki * eeid * ts;', ...
    '    xi_eiq = xi_eiq - energy_i_ki * eeiq * ts;', ...
    'end', ...
    'm_energy3 = energy_polarity * [ema; emb; emc];', ...
    'last_act = act4;', ...
    'end' ...
    }, newline);
end
