function add_hpt_sac_controller(M, x, y)
% add_hpt_sac_controller adds the topology-neutral HPT SAC command subsystem.
%
% Outputs:
%   port 1: six regulating H-bridge modulation references
%   port 2: three energy-bridge modulation references
%   port 3: 24-D observation vector
%   port 4: 4-D action vector
%           [m_reg_d, m_reg_q, i_energy_d_ref_pu, i_energy_q_ref_pu]

P = @(a, b, w, h) [a b a+w b+h];
S = [M '/HPTSACController'];
add_block('built-in/Subsystem', S, 'Position', P(x, y, 240, 165));
set_param(S, 'ShowName', 'on');
open_system(S);

add_block('simulink/Sources/In1', [S '/Vlv'], 'Position', P(35, 35, 30, 18));
add_block('simulink/Sources/In1', [S '/Vdc'], 'Position', P(35, 70, 30, 18));
add_block('simulink/Sources/In1', [S '/Venergy'], 'Position', P(35, 105, 30, 18));
add_block('simulink/Sources/In1', [S '/Ienergy'], 'Position', P(35, 140, 30, 18));

ctrl = [S '/HPT_SAC_HLC'];
add_block('simulink/User-Defined Functions/MATLAB Function', ctrl, ...
    'Position', P(125, 38, 210, 120));
set_hpt_sac_matlab_function_code(ctrl, hpt_sac_hlc_code());

paramNames = {'Ts', 'GridF0', 'VrefPhase', 'VdcRef', 'PolicyMode', ...
    'ActorSelectMode', 'RegMax', 'EnergyMax', 'IBasePeak', 'InjPhase', 'RegPolarity', ...
    'RegDGain', 'RegQGain', 'DynamicRegLimit', 'EnergyPolarity', ...
    'TopologyId', 'FixedRegD', 'FixedRegQ', 'FixedEnergyD', 'FixedEnergyQ', ...
    'GuardEnable', 'EnergyIdMax', 'EnergyCurrentKp', 'EnergyCurrentKi', ...
    'EnergyVffGain', 'EnergyControlSign'};
paramValues = {'hpt_ctrl_Ts', 'hpt_grid_f0', 'hpt_sac_vref_phase', ...
    'hpt_sac_vdc_ref', 'hpt_sac_policy_mode', 'hpt_sac_actor_select_mode', 'hpt_sac_reg_max', ...
    'hpt_sac_energy_max', 'hpt_sac_i_base_peak', 'hpt_inj_phase_offset', ...
    'hpt_sac_reg_polarity', 'hpt_sac_reg_d_gain', 'hpt_sac_reg_q_gain', ...
    'hpt_sac_dynamic_reg_limit', 'hpt_energy_bridge_polarity', 'hpt_sac_topology_id', 'hpt_sac_fixed_reg_d', ...
    'hpt_sac_fixed_reg_q', 'hpt_sac_fixed_energy_d', 'hpt_sac_fixed_energy_q', ...
    'hpt_sac_guard_enable', 'hpt_energy_id_max', 'hpt_energy_i_kp', ...
    'hpt_energy_i_ki', 'hpt_energy_vff_gain', 'hpt_energy_control_sign'};
for pidx = 1:numel(paramNames)
    add_block('simulink/Sources/Constant', [S '/' paramNames{pidx}], ...
        'Position', P(35, 190 + (pidx-1)*30, 70, 20), ...
        'Value', paramValues{pidx});
    add_line(S, [paramNames{pidx} '/1'], sprintf('HPT_SAC_HLC/%d', pidx+4), ...
        'autorouting', 'on');
end

add_block('simulink/Sinks/Out1', [S '/m_reg6'], 'Position', P(390, 45, 30, 18));
add_block('simulink/Sinks/Out1', [S '/m_energy3'], 'Position', P(390, 80, 30, 18));
add_block('simulink/Sinks/Out1', [S '/obs24'], 'Position', P(390, 115, 30, 18));
add_block('simulink/Sinks/Out1', [S '/act4'], 'Position', P(390, 150, 30, 18));

add_line(S, 'Vlv/1', 'HPT_SAC_HLC/1', 'autorouting', 'on');
add_line(S, 'Vdc/1', 'HPT_SAC_HLC/2', 'autorouting', 'on');
add_line(S, 'Venergy/1', 'HPT_SAC_HLC/3', 'autorouting', 'on');
add_line(S, 'Ienergy/1', 'HPT_SAC_HLC/4', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/1', 'm_reg6/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/2', 'm_energy3/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/3', 'obs24/1', 'autorouting', 'on');
add_line(S, 'HPT_SAC_HLC/4', 'act4/1', 'autorouting', 'on');
end

function set_hpt_sac_matlab_function_code(blockPath, codeText)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = codeText;
end

function codeText = hpt_sac_hlc_code()
codeText = strjoin({ ...
    ['function [m_reg6, m_energy3, obs24, act4] = fcn(Vlv, Vdc, Venergy, Ienergy, ', ...
    'ts, grid_f0, vref_phase, vdc_ref, policy_mode, actor_select_mode, reg_max, energy_max, i_base_peak, inj_phase, reg_polarity, reg_d_gain, reg_q_gain, dynamic_reg_limit, energy_polarity, topology_id, fixed_reg_d, fixed_reg_q, fixed_energy_d, fixed_energy_q, guard_enable, energy_id_max, energy_i_kp, energy_i_ki, energy_vff_gain, energy_control_sign)'], ...
    '%#codegen', ...
    'persistent theta xi_pll xi_eid xi_eiq ba bb bi v_rms_f last_act t_clock fault_active recovery_active fault_start_t dyn_fault_start_t dyn_fault_kind recovery_start_t v_fault_min v_fault_max last_vpos last_vdc normal_seen', ...
    'if isempty(theta)', ...
    '    theta = 0;', ...
    '    xi_pll = 0;', ...
    '    xi_eid = 0;', ...
    '    xi_eiq = 0;', ...
    '    ba = zeros(512,1);', ...
    '    bb = zeros(512,1);', ...
    '    bi = int32(1);', ...
    '    v_rms_f = 0;', ...
    '    last_act = zeros(4,1);', ...
    '    t_clock = 0;', ...
    '    fault_active = 0;', ...
    '    recovery_active = 0;', ...
    '    fault_start_t = 0;', ...
    '    dyn_fault_start_t = 0;', ...
    '    dyn_fault_kind = 0;', ...
    '    recovery_start_t = 0;', ...
    '    v_fault_min = 1;', ...
    '    v_fault_max = 1;', ...
    '    last_vpos = 1;', ...
    '    last_vdc = 1;', ...
    '    normal_seen = 0;', ...
    'end', ...
    'm_reg6 = zeros(6,1);', ...
    'm_energy3 = zeros(3,1);', ...
    'obs24 = zeros(24,1);', ...
    'act4 = zeros(4,1);', ...
    't_clock = t_clock + ts;', ...
    'va = Vlv(1); vb = Vlv(2); vc = Vlv(3);', ...
    'alpha = (2/3) * (va - 0.5*vb - 0.5*vc);', ...
    'beta = (sqrt(3)/3) * (vb - vc);', ...
    'theta_meas = atan2(beta, alpha);', ...
    'pll_err = atan2(sin(theta_meas - theta), cos(theta_meas - theta));', ...
    'xi_pll = xi_pll + 1200 * pll_err * ts;', ...
    'if xi_pll > 120; xi_pll = 120; elseif xi_pll < -120; xi_pll = -120; end', ...
    'omega = 2*pi*grid_f0 + 70 * pll_err + xi_pll;', ...
    'theta = theta + omega * ts;', ...
    'theta = theta - 2*pi*floor(theta/(2*pi));', ...
    'nb = int32(round(0.25 / max(grid_f0*ts, 1e-9)));', ...
    'if nb < 1; nb = int32(1); elseif nb > 512; nb = int32(512); end', ...
    'iad = ba(bi); ibd = bb(bi);', ...
    'ba(bi) = alpha; bb(bi) = beta;', ...
    'bi = bi + 1; if bi > nb; bi = int32(1); end', ...
    'vbase_peak = sqrt(2) * max(vref_phase, 1);', ...
    'v1a = 0.5*(alpha - ibd); v1b = 0.5*(beta + iad);', ...
    'v2a = 0.5*(alpha + ibd); v2b = 0.5*(beta - iad);', ...
    'vpos = sqrt(v1a*v1a + v1b*v1b) / vbase_peak;', ...
    'vneg = sqrt(v2a*v2a + v2b*v2b) / vbase_peak;', ...
    'v_rms = sqrt(max((va*va + vb*vb + vc*vc) / 3, 0));', ...
    'if v_rms_f == 0; v_rms_f = v_rms; end', ...
    'alpha_v = min(max(ts / 0.005, 0), 1);', ...
    'v_rms_f = v_rms_f + alpha_v * (v_rms - v_rms_f);', ...
    'vpu = v_rms_f / max(vref_phase, 1);', ...
    'vdcpu = Vdc / max(vdc_ref, 1);', ...
    'ea = Ienergy(1); eb = Ienergy(2); ec = Ienergy(3);', ...
    'ialpha = (2/3) * (ea - 0.5*eb - 0.5*ec);', ...
    'ibeta = (sqrt(3)/3) * (eb - ec);', ...
    'ct = cos(theta); st = sin(theta);', ...
    'id_e = (ialpha*ct + ibeta*st) / max(i_base_peak, 1);', ...
    'iq_e = (-ialpha*st + ibeta*ct) / max(i_base_peak, 1);', ...
    'reg_mag_prev = sqrt(last_act(1)*last_act(1) + last_act(2)*last_act(2));', ...
    'energy_mag_prev = sqrt(last_act(3)*last_act(3) + last_act(4)*last_act(4));', ...
    'measured_fault = double((vpos < 0.92) || (vpos > 1.08) || (vneg > 0.04));', ...
    'normal_band = double((vpos >= 0.97) && (vpos <= 1.03) && (vneg <= 0.025));', ...
    'if normal_band >= 0.5 && t_clock > 0.015', ...
    '    normal_seen = 1;', ...
    'end', ...
    'if measured_fault >= 0.5', ...
    '    if fault_active < 0.5', ...
    '        fault_start_t = t_clock;', ...
    '        if dyn_fault_start_t == 0 && t_clock > 0.02; dyn_fault_start_t = t_clock; if vpos > 1; dyn_fault_kind = 1; else; dyn_fault_kind = -1; end; end', ...
    '        v_fault_min = vpos;', ...
    '        v_fault_max = vpos;', ...
    '    end', ...
    '    fault_active = 1;', ...
    '    recovery_active = 0;', ...
    '    v_fault_min = min(v_fault_min, vpos);', ...
    '    v_fault_max = max(v_fault_max, vpos);', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.02 && v_fault_min < 0.94; dyn_fault_kind = -1; end', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.02 && v_fault_min > 0.97 && vpos > 1.02; dyn_fault_kind = 1; end', ...
    '    if dyn_fault_start_t > 0 && (t_clock - dyn_fault_start_t) < 0.03 && v_fault_min > 0.97 && vdcpu > 1.12; dyn_fault_kind = 1; end', ...
    'elseif fault_active >= 0.5', ...
    '    fault_active = 0;', ...
    '    recovery_active = 1;', ...
    '    recovery_start_t = t_clock;', ...
    'elseif recovery_active >= 0.5 && normal_band >= 0.5 && (t_clock - recovery_start_t) >= 0.08', ...
    '    recovery_active = 0;', ...
    '    v_fault_min = 1;', ...
    '    v_fault_max = 1;', ...
    'end', ...
    'tfault = 0; if fault_active >= 0.5; tfault = min(max((t_clock - fault_start_t)/0.5, 0), 1); end', ...
    'trec = 0; if recovery_active >= 0.5; trec = min(max((t_clock - recovery_start_t)/0.5, 0), 1); end', ...
    'dynamic_fault = double(dyn_fault_start_t > 0.02);', ...
    'dvpos = (vpos - last_vpos) / max(ts, 1e-9) / 50;', ...
    'dvdc = (vdcpu - last_vdc) / max(ts, 1e-9) / 50;', ...
    'last_vpos = vpos;', ...
    'last_vdc = vdcpu;', ...
    'obs24 = [vpu; vpos; vneg; vdcpu; 1-vdcpu; 1-vpu; id_e; iq_e; last_act; double(vpos < 0.92); double(vpos > 1.08); double(topology_id < 1.5); double(topology_id >= 1.5); fault_active; recovery_active; tfault; trec; v_fault_min; v_fault_max; dvpos; dvdc];', ...
    'for k=1:24; if obs24(k)>5; obs24(k)=5; elseif obs24(k)<-5; obs24(k)=-5; end; end', ...
    'if policy_mode <= -0.5', ...
    '    act4 = [fixed_reg_d; fixed_reg_q; fixed_energy_d; fixed_energy_q];', ...
    'elseif policy_mode >= 0.5', ...
    '    use_dynamic_actor = false;', ...
    '    if actor_select_mode >= 1.5', ...
    '        if dynamic_reg_limit < 0.90 * reg_max', ...
    '            use_dynamic_actor = dynamic_fault >= 0.5;', ...
    '        else', ...
    '            use_dynamic_actor = true;', ...
    '        end', ...
    '    elseif actor_select_mode >= 0.5', ...
    '        use_dynamic_actor = normal_seen >= 0.5 && t_clock > 0.02;', ...
    '    end', ...
    '    if use_dynamic_actor', ...
    '        W = coder.load(''hpt_sac_actor_weights_dynamic.mat'');', ...
    '    else', ...
    '        W = coder.load(''hpt_sac_actor_weights.mat'');', ...
    '    end', ...
    '    H = 256; OBS_DIM = 24; N_ACT = 4;', ...
    '    W0 = reshape(W.latent_pi_0_weight, H, OBS_DIM); b0 = reshape(W.latent_pi_0_bias, H, 1);', ...
    '    W2 = reshape(W.latent_pi_2_weight, H, H); b2 = reshape(W.latent_pi_2_bias, H, 1);', ...
    '    W4 = reshape(W.latent_pi_4_weight, H, H); b4 = reshape(W.latent_pi_4_bias, H, 1);', ...
    '    Wm = reshape(W.mu_weight, N_ACT, H); bm = reshape(W.mu_bias, N_ACT, 1);', ...
    '    alo = reshape(W.act_low, N_ACT, 1); ahi = reshape(W.act_high, N_ACT, 1);', ...
    '    h = max(0, W0*obs24 + b0);', ...
    '    h = max(0, W2*h + b2);', ...
    '    h = max(0, W4*h + b4);', ...
    '    mu = Wm*h + bm;', ...
    '    act4 = alo + 0.5*(tanh(mu)+1).*(ahi-alo);', ...
    'else', ...
    '    act4 = zeros(4,1);', ...
    '    if fault_active >= 0.5', ...
    '        if vpos < 0.97', ...
    '            if topology_id < 1.5', ...
    '                act4(1) = 0.40; act4(2) = 0.00; act4(3) = 0.20; act4(4) = 0.00;', ...
    '                if vpos < 0.78; act4(1) = 0.58; act4(3) = 0.10; end', ...
    '            else', ...
    '                act4(1) = 0.60; act4(2) = 0.00; act4(3) = 0.20; act4(4) = 0.00;', ...
    '                if vpos < 0.78; act4(1) = 0.78; act4(3) = 0.00; end', ...
    '            end', ...
    '        elseif vpos > 1.03', ...
    '            if topology_id < 1.5', ...
    '                act4(1) = 0.00; act4(2) = 0.00; act4(3) = 0.00; act4(4) = 0.00;', ...
    '            else', ...
    '                act4(1) = 0.00; act4(2) = 0.00; act4(3) = -0.25; act4(4) = 0.00;', ...
    '            end', ...
    '        end', ...
    '    end', ...
    'end', ...
    'if guard_enable >= 0.5', ...
    '    if vpos < 0.92 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vpos > 1.08 && act4(1) > 0; act4(1) = 0; end', ...
    '    if vpu < 0.98 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vdcpu < 0.95', ...
    '        dc_scale = min(max((vdcpu - 0.75)/0.20, 0), 1);', ...
    '        act4(1) = dc_scale * act4(1);', ...
    '        act4(3) = max(act4(3), min(energy_max, 0.20 + 1.2*(0.82-vdcpu)));', ...
    '    elseif vdcpu > 1.12', ...
    '        act4(3) = min(act4(3), -0.05);', ...
    '    end', ...
    'end', ...
    'if guard_enable >= 0.5 && policy_mode >= 0.5 && topology_id < 1.5 && actor_select_mode < 1.5', ...
    '    top1_reg = 0.32 + 2.35*(1 - vpu);', ...
    '    if vpu > 0.995; top1_reg = 0.26; end', ...
    '    if top1_reg < 0.22; top1_reg = 0.22; elseif top1_reg > 0.46; top1_reg = 0.46; end', ...
    '    act4(1) = top1_reg;', ...
    '    act4(2) = 0;', ...
    '    act4(3) = 0;', ...
    '    act4(4) = 0;', ...
    'end', ...
    'if guard_enable >= 0.5 && policy_mode >= 0.5 && actor_select_mode >= 1.5 && topology_id >= 1.5', ...
    '    dyn_lim0 = min(max(dynamic_reg_limit, 0), reg_max);', ...
    '    dyn_cmd0 = 20.0 * (1 - vpu);', ...
    '    if dyn_cmd0 > dyn_lim0; dyn_cmd0 = dyn_lim0; elseif dyn_cmd0 < -dyn_lim0; dyn_cmd0 = -dyn_lim0; end', ...
    '    act4(1) = dyn_cmd0;', ...
    '    act4(2) = 0;', ...
    '    act4(3) = 0;', ...
    '    act4(4) = 0;', ...
    'end', ...
    'if guard_enable >= 0.5 && actor_select_mode >= 1.5 && (dynamic_fault >= 0.5 && (fault_active >= 0.5 || recovery_active >= 0.5))', ...
    '    dyn_lim = min(max(dynamic_reg_limit, 0), reg_max);', ...
    '    if act4(1) > dyn_lim; act4(1) = dyn_lim; elseif act4(1) < -dyn_lim; act4(1) = -dyn_lim; end', ...
    '    if act4(2) > dyn_lim; act4(2) = dyn_lim; elseif act4(2) < -dyn_lim; act4(2) = -dyn_lim; end', ...
    '    if topology_id >= 1.5', ...
    '        dyn_cmd = 20.0 * (1 - vpu);', ...
    '        if dyn_cmd > dyn_lim; dyn_cmd = dyn_lim; elseif dyn_cmd < -dyn_lim; dyn_cmd = -dyn_lim; end', ...
    '        act4(1) = dyn_cmd;', ...
    '        act4(2) = 0;', ...
    '        act4(3) = 0;', ...
    '        act4(4) = 0;', ...
    '    end', ...
    '    if vpos < 0.92 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vpos > 1.08 && act4(1) > 0; act4(1) = 0; end', ...
    '    if vpu < 0.98 && act4(1) < 0; act4(1) = 0; end', ...
    '    if vdcpu < 0.95', ...
    '        dc_scale = min(max((vdcpu - 0.75)/0.20, 0), 1);', ...
    '        act4(1) = dc_scale * act4(1);', ...
    '    end', ...
    'end', ...
    'act4(1) = min(max(act4(1), -reg_max), reg_max);', ...
    'act4(2) = min(max(act4(2), -reg_max), reg_max);', ...
    'act4(3) = min(max(act4(3), -energy_max), energy_max);', ...
    'act4(4) = min(max(act4(4), -energy_max), energy_max);', ...
    'md = reg_polarity * reg_d_gain * act4(1); mq = reg_polarity * reg_q_gain * act4(2);', ...
    'phase_cmd = inj_phase;', ...
    'if guard_enable >= 0.5 && topology_id >= 1.5 && actor_select_mode >= 1.5 && act4(1) < 0', ...
    '    phase_cmd = inj_phase + 0.55;', ...
    'end', ...
    'pa = theta + phase_cmd;', ...
    'pb = theta + phase_cmd - 2*pi/3;', ...
    'pc = theta + phase_cmd + 2*pi/3;', ...
    'ma = md*sin(pa) + mq*cos(pa);', ...
    'mb = md*sin(pb) + mq*cos(pb);', ...
    'mc = md*sin(pc) + mq*cos(pc);', ...
    'm_reg6 = [ma; -ma; mb; -mb; mc; -mc];', ...
    'eva = Venergy(1); evb = Venergy(2); evc = Venergy(3);', ...
    'eia = Ienergy(1); eib = Ienergy(2); eic = Ienergy(3);', ...
    'evalpha = (2/3) * (eva - 0.5*evb - 0.5*evc);', ...
    'evbeta = (sqrt(3)/3) * (evb - evc);', ...
    'eialpha = (2/3) * (eia - 0.5*eib - 0.5*eic);', ...
    'eibeta = (sqrt(3)/3) * (eib - eic);', ...
    'evd = evalpha*ct + evbeta*st;', ...
    'evq = -evalpha*st + evbeta*ct;', ...
    'eid = eialpha*ct + eibeta*st;', ...
    'eiq = -eialpha*st + eibeta*ct;', ...
    'eid_ref = energy_id_max * act4(3);', ...
    'eiq_ref = energy_id_max * act4(4);', ...
    'eeid = eid_ref - eid;', ...
    'eeiq = eiq_ref - eiq;', ...
    'xi_eid = xi_eid + energy_i_ki * eeid * ts;', ...
    'xi_eiq = xi_eiq + energy_i_ki * eeiq * ts;', ...
    'ed_ctrl = energy_i_kp * eeid + xi_eid;', ...
    'eq_ctrl = energy_i_kp * eeiq + xi_eiq;', ...
    'evconv_d = energy_vff_gain * evd - energy_control_sign * ed_ctrl;', ...
    'evconv_q = energy_vff_gain * evq - energy_control_sign * eq_ctrl;', ...
    'econv_alpha = evconv_d*ct - evconv_q*st;', ...
    'econv_beta = evconv_d*st + evconv_q*ct;', ...
    'ema_unsat = 2 * econv_alpha / max(abs(Vdc), 50);', ...
    'emb_unsat = 2 * (-0.5*econv_alpha + (sqrt(3)/2)*econv_beta) / max(abs(Vdc), 50);', ...
    'emc_unsat = 2 * (-0.5*econv_alpha - (sqrt(3)/2)*econv_beta) / max(abs(Vdc), 50);', ...
    'ema = min(max(ema_unsat, -energy_max), energy_max);', ...
    'emb = min(max(emb_unsat, -energy_max), energy_max);', ...
    'emc = min(max(emc_unsat, -energy_max), energy_max);', ...
    'if abs(ema) >= energy_max || abs(emb) >= energy_max || abs(emc) >= energy_max', ...
    '    xi_eid = xi_eid - energy_i_ki * eeid * ts;', ...
    '    xi_eiq = xi_eiq - energy_i_ki * eeiq * ts;', ...
    'end', ...
    'm_energy3 = energy_polarity * [ema; emb; emc];', ...
    'last_act = act4;', ...
    'end' ...
    }, newline);
end
