"""
ppo_hpt_simulink.py  — PPO trained on real Simulink 1400-scenario data.

Data source: results/strategy_lvrt_data.csv (350 scenarios x 4 strategies,
generated by data_collection/generate_strategy_data.m using MATLAB MCP).

This is the highest-fidelity PPO training possible without running Simulink
online during training: uses actual Simulink switching-model LVRT results
for all strategy/scenario combinations as a lookup table.
"""

from __future__ import annotations
import json, sys
from pathlib import Path

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

sys.path.insert(0, str(Path(__file__).parent))
from hpt_sim_env import SC_NAMES, SC_IDS, SC_ID_TO_IDX, scenario_obs

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR    = PROJECT_ROOT / 'data' / 'models'
RESULTS_DIR  = PROJECT_ROOT / 'results'
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# ── Load real Simulink data ────────────────────────────────────────────────────

def load_simulink_table(
    csv_path: Path = RESULTS_DIR / 'strategy_lvrt_data.csv',
    scen_path: Path = PROJECT_ROOT / 'data_collection' / 'scenario_table_hpt_v2.csv',
) -> tuple[np.ndarray, pd.DataFrame]:
    """Load 350x4 LVRT lookup table from real Simulink batch results."""
    data = pd.read_csv(csv_path)
    scen = pd.read_csv(scen_path).reset_index(drop=True)
    N = 350; NS = 4
    table = np.zeros((N, NS, 4), dtype=np.float32)
    for _, row in data.iterrows():
        i = int(row.scenario_idx) - 1
        s = int(row.strategy)
        table[i, s, 0] = float(row.vdc_min_pu)
        table[i, s, 1] = float(row.vdc_max_pu)
        table[i, s, 2] = float(row.i2_max_pu)
        table[i, s, 3] = float(row.lvrt_pass)
    return table, scen

# ── Reward ─────────────────────────────────────────────────────────────────────

def reward_fn(vmin, vmax, i2, lvrt, strategy):
    r  = 10.0 * float(lvrt)
    r += 4.0  * min(1.0, max(0.0, vmin / 0.75))
    r += 3.0  * min(1.0, max(0.0, (1.25 - vmax) / 0.25))
    r += 2.0  * min(1.0, max(0.0, (3.0  - i2)   / 2.0))
    r -= 0.15 * strategy    # small conservative bias
    return float(r)

# ── Gymnasium environment ──────────────────────────────────────────────────────

class HPTSimulinkEnv(gym.Env):
    metadata = {'render_modes': []}
    def __init__(self, table: np.ndarray, scen: pd.DataFrame, seed: int = 42):
        super().__init__()
        self.table = table
        self.scen  = scen
        self.rng   = np.random.default_rng(seed)
        self._cur  = 0
        self.observation_space = spaces.Box(-np.inf, np.inf, shape=(14,), dtype=np.float32)
        self.action_space = spaces.Discrete(4)

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        self._cur = int(self.rng.integers(len(self.scen)))
        return scenario_obs(self.scen.iloc[self._cur]), {}

    def step(self, action: int):
        m   = self.table[self._cur, int(action)]
        r   = reward_fn(m[0], m[1], m[2], bool(m[3]), int(action))
        obs = scenario_obs(self.scen.iloc[self._cur])
        return obs, r, True, False, {}

    def render(self): pass

# ── Evaluation ─────────────────────────────────────────────────────────────────

def eval_ppo(model, table, scen):
    passes = 0
    for i, (_, row) in enumerate(scen.iterrows()):
        obs = scenario_obs(row).reshape(1, -1)
        a, _ = model.predict(obs, deterministic=True)
        passes += int(table[i, int(a[0]), 3])
    return 100.0 * passes / len(scen)

# ── Training ───────────────────────────────────────────────────────────────────

def train(total_steps: int = 300_000, n_envs: int = 8, eval_freq: int = 20_000):
    print('=' * 58)
    print('PPO Training on Real Simulink Data (1400 scenarios)')
    print('=' * 58)

    table, scen = load_simulink_table()
    N = len(scen)

    dq_rate    = 100.0 * table[:, 0, 3].mean()
    oracle_rate = 100.0 * np.max(table[:, :, 3], axis=1).mean()
    print(f'\nS0 (dq baseline): {dq_rate:.2f}%')
    print(f'Oracle upper:     {oracle_rate:.2f}%\n')

    def make_env():
        return HPTSimulinkEnv(table, scen, seed=int(np.random.randint(99999)))

    vec_env = make_vec_env(make_env, n_envs=n_envs)

    ppo = PPO('MlpPolicy', vec_env,
              learning_rate=3e-4, n_steps=2048, batch_size=256,
              n_epochs=10, gamma=0.99, gae_lambda=0.95,
              ent_coef=0.01, clip_range=0.20, vf_coef=0.5,
              policy_kwargs=dict(net_arch=[128, 128]),
              verbose=0, seed=42)

    best = 0.0
    steps_done = 0
    while steps_done < total_steps:
        chunk = min(eval_freq, total_steps - steps_done)
        ppo.learn(total_timesteps=chunk, reset_num_timesteps=False)
        steps_done += chunk
        rate = eval_ppo(ppo, table, scen)
        if rate > best:
            best = rate
            ppo.save(str(MODEL_DIR / 'ppo_hpt_simulink_best.zip'))
        print(f'  step={steps_done:7d}  LVRT={rate:.2f}%  (best={best:.2f}%)')

    ppo.save(str(MODEL_DIR / 'ppo_hpt_simulink_final.zip'))

    # ── Final evaluation ────────────────────────────────────────────────────
    from stable_baselines3 import PPO as PPO2
    best_ppo = PPO2.load(str(MODEL_DIR / 'ppo_hpt_simulink_best.zip'))

    print('\n' + '=' * 58)
    print('Final Results (Real Simulink Switching-Model Data)')
    print('=' * 58)
    print(f'S0 dq baseline: {dq_rate:.2f}%')
    print(f'PPO best:       {best:.2f}%')
    print(f'Oracle upper:   {oracle_rate:.2f}%')

    # Per-class breakdown
    sc_decisions = {sc: [] for sc in SC_IDS}
    for i, (_, row) in enumerate(scen.iterrows()):
        sc = int(row.sc_id)
        obs = scenario_obs(row).reshape(1, -1)
        a, _ = best_ppo.predict(obs, deterministic=True)
        s = int(a[0])
        lvrt = bool(table[i, s, 3])
        sc_decisions[sc].append((s, lvrt))

    print()
    print(f"{'Class':<14}  {'S0%':>5}  {'PPO%':>5}  {'Oracle%':>7}  Strategy distribution")
    print('-' * 70)
    for sc in sorted(SC_NAMES):
        if sc not in sc_decisions or not sc_decisions[sc]:
            continue
        name = SC_NAMES[sc]
        sc_mask = scen.sc_id == sc
        s0_pass  = 100.0 * table[sc_mask.values, 0, 3].mean()
        orc_pass = 100.0 * np.max(table[sc_mask.values, :, 3], axis=1).mean()
        ppo_pass = 100.0 * np.mean([x[1] for x in sc_decisions[sc]])
        dist = {}
        for s, _ in sc_decisions[sc]:
            dist[s] = dist.get(s, 0) + 1
        print(f'{name:<14}  {s0_pass:5.1f}  {ppo_pass:5.1f}  {orc_pass:7.1f}  {dict(sorted(dist.items()))}')

    # Save result
    result = {
        'source':      'real_simulink_1400_sims',
        'n_scenarios': N,
        'n_strategies': 4,
        'dq_pass_pct':     round(dq_rate,    2),
        'ppo_pass_pct':    round(best,        2),
        'oracle_pass_pct': round(oracle_rate, 2),
        'gain_vs_dq_pp':   round(best - dq_rate, 2),
    }
    out = RESULTS_DIR / 'ppo_hpt_simulink_result.json'
    out.write_text(json.dumps(result, indent=2), encoding='utf-8')
    print(f'\nSaved -> {out}')


if __name__ == '__main__':
    train(total_steps=300_000)
